### ISSUE TITLE
[BUG] Docker images are not published automatically

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1008]
[Apalache docker images](https://hub.docker.com/r/apalache/mc/tags?page=1&ordering=last_updated) at hub.docker.com are 2-3 months old. It looks like something is broken in the CI.

**Comment by shonfeder** [comment]
Apparently docker changed the terms of service covering their automated build service without sending any clear notifications or warnings. (There was an email about changes to Docker Desktop, but I just checked the email now and there is no mention of "build" in it).

It should be relatively easy to tweak the CI to start pushing images to docker hub, and maybe we want to look at an alternative container registry (perhaps using GitHubs?).

**Comment by shonfeder** [comment]
In the meantime, I've pushed a new image up for the unstable and latest tags
