### ISSUE TITLE
Store original transitions in the ModelChecker execution stack

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/apalache#101]
Currently, during the ModelChecker execution, it's stack stores states and oracles, the latter representing the transition picked to reach the state. This transition is represented, though, as a relative index in the array of transitions enabled in the previous state.

For reporting purposes (e.g. printing a counterexample) we need the stack to contain references to the original transitions from the specification. Please refactor ModelChecker for that purpose.

**Comment by konnov** [comment]
This will be resolved in the multicore version, as it completely changes `ModelChecker`

**Comment by konnov** [comment]
This is fixed long time ago in `TransitionExecutor`.
