### ISSUE TITLE
[BUG] Types for model values

### ISSUE THREAD

**Issue by banhday** [informalsystems/apalache#1029]
## Description

Type checking was successful, but I received the following error message 
```
The types of p1 (PID) and OVERRIDE_p1 (Str) do not match. 
Configuration error (see the manual): The types of p1 (PID) and OVERRIDE_p1 (Str) do not match.
```
when checking the file `ex1_MC.tla`. This specification contains a constant Proc, and it is a set of a model value p1.

## Input specification

See  [ex1.zip](https://github.com/informalsystems/apalache/files/7312890/ex1.zip).

## The command line parameters used to run the tool

```
apalache-mc typecheck ex1_MC.tla 
apalache-mc check --length=2 ex1_MC.tla 
```

## System information

- Apalache version [`apalache-mc version`]: version 0.16.2
- OS [e.g. Ubuntu Linux or Mac OS, and the current version]: Ubuntu 20.04
- JDK version [e.g. OpenJDK 0.8.0]: OpenJDK version 1.8.0_292

**Comment by konnov** [comment]
The issue is that type annotations are not support in the TLC configuration files. So the configuration parser ignores the comment in:

```
CONSTANTS
\* @type: PID;
p1 = p1
```

@shonfeder, @Kukovec, what shall we do? In principle, we could add type annotations in the TLC configuration files, but these files are more like backward compatibility with TLC. I would prefer not doing it.

**Comment by banhday** [comment]
I see your point. If I want to annotate Proc with type Set(PID), what is an appropriate way to initialize Proc? For example, let Proc be a set of 2 unique process IDs P1 and P2. I tried to write 
```
\* CONSTANT definitions @modelParameterConstants:6Proc
\* @type: Set(PID);
const_163386629483563000 == 
{ P1, P2 }
```
but the parser says P1 is an unknown operator. I also tried 
```
\* CONSTANT definitions @modelParameterConstants:6Proc
\* @type: Set(PID);
const_163386629483563000 == 
{ "P1", "P2" }
```
but there exists an error when computing the type of Proc.

**Comment by konnov** [comment]
Looks like a stall issue, since we do not want to use uninterpreted types in TLC configs.
