### ISSUE TITLE
Fail CI on compiler errors

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#1064]
Compiler warnings create noise during the build, they can undermine the confidence of contributors or users, and sometimes they signal serious problems that can lead to runtime errors (e.g., for unmatched patterns). So, to improve the hygiene and reliability of our development, it would be a good idea to start failing the build for any unsilenced warnings.

If we decide that there are some cases where we don't want to, e.g., handle all possible match cases, we should explicitly silence the warnings for those cases. Otherwise, we should clean up all that cruft. 

- [x] #1526
  - [x] #1471
  - [x] #1472
- [x] #1473
- [x] Add linting CI task that runs with `set scalacOptions ++= Seq("-Ywarn-unused", "-Xlint:unused", "-Xfatal-warnings")` to fail when new warnings are introduced.

**Comment by thpani** [comment]
@shonfeder Looks like all current compiler warnings are squashed :tada:

I'm not quite sure what's left to do for the last point:

> Add linting CI task that runs with set scalacOptions ++= Seq("-Ywarn-unused", "-Xlint:unused", "-Xfatal-warnings") to fail when new warnings are introduced

Should we just enable `-Xfatal-warnings` on all builds? Feel free to take this issue from here on if you want.

**Comment by shonfeder** [comment]
I'll take this up! 

I think you're right that we should enable fatal warnings on all builds. And in fact iiuc the linting cannot enable fatal-warnings, or else scalafix won't be able to work it's magic.
