### ISSUE TITLE
[BUG] Polymorphic operator types are not instantiated correctly

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#1084]
## Description

When using a polymorphic operator twice in the same context, the type of the 1st application instance is considered when computing the 2nd application instance, even though they should be instantiated independently.

## Input specification

```
---------- MODULE test ----------

EXTENDS Integers

Init == TRUE

Next == TRUE

\* @type: (a -> Int) => Set(a);
X(f) == DOMAIN f

f1 == [a \in {1} |-> 1]
fa == [a \in {"a"} |-> 1]

Inv1 ==
  /\ X(fa) = {"a"}
  /\ X(f1) = {1}

Inv2 ==
  /\ X(f1) = {1}
  /\ X(fa) = {"a"}

Inv3 == 
  LET
    A == X(fa)
  IN LET
    B == X(f1)
  IN 
  /\ A = {"a"}
  /\ B = {1}
====================
```

## The command line parameters used to run the tool

`--inv=Inv[N] --length=1`

## Expected behavior

No type error for any of the invariants

## Additional context

Returns
```
[test.tla:41:6-41:10]: No match between operator signature (((Str -> Int)) => Set(Str)) and argument (Int -> Int) E@11:32:49.829
```
When checking `Inv1`,
```
[test.tla:41:6-41:10]: No match between operator signature (((Int -> Int)) => Set(Int)) and argument (Str -> Int) E@11:35:24.173
```
When checking `Inv2`, and no error when checking the workaround `Inv3`

**Comment by konnov** [comment]
It's weird, because I have fixed exactly the same issue a few months ago.
