### ISSUE TITLE
[FEATURE] Benchmarking setup for the arrays encoding

### ISSUE THREAD

**Issue by rodrigo7491** [informalsystems/apalache#1099]
As described in the [ADR11](https://apalache.informal.systems/docs/adr/011adr-smt-arrays.html), the purpose of the arrays encoding is to improve performance. In order to evaluate the impact of the new encoding the benchmarking setup in [apalache-tests](https://github.com/informalsystems/apalache-tests) needs to be able to do the following:

- [x] Select different SMT encodings.
- [x] Select specific (sets of) benchmarks to run.
- [x] Select `unreleased`or another Apalache branch to run the evaluation on.

The last point is optional, but it would make doing the evaluation easier, since now it can only be carried out with Apalache releases.

**Comment by shonfeder** [comment]
The benchmarks do run against `unreleased` currently. I'll take a look at this today or tomorrow.

**Comment by rodrigo7491** [comment]
When I tried to run locally, I could only make it work on the latest release, but maybe I missed something.

**Comment by shonfeder** [comment]
Try `make version=unreleased strate=001indinv` ?

**Comment by rodrigo7491** [comment]
The command you suggested is not valid, I think you mean `make run strat=001lindinv version=unreleased` and it does indeed work! I had a look here and I was using `version=unstable` as stated in the `README`. Do executions from GitHub Actions and local executions behave differently?

**Comment by shonfeder** [comment]
Yep, that's the command. Sorry.

I don't see anywhere in the repo where it says to set `version=unstable` could you provide a link?

> Do executions from GitHub Actions and local executions behave differently?

They should not, modulo differences in your environment.

**Comment by rodrigo7491** [comment]
It is not written `version=unstable` explicitly, but it is implied int the [README.md](https://github.com/informalsystems/apalache-tests/blob/master/README.md) under `Usage`. `unreleased` is not mentioned anywhere there, nor when using `make help`.

**Comment by shonfeder** [comment]
Ah, I see how it could be read like that now that you mention it. I'll make to update the README too.

- [ ] Add note on how to run specific versions (esp. from the head) to README.

**Comment by shonfeder** [comment]
@rodrigo7491 and I had a quick meeting today. We agreed that in the short term we can use the existing benchmarking framework to get some feedback on the performance of the array encoding. However,  the current graph generation and experiment configuration is not well suited for testing and reporting different configurations of the same version of Apalache. So for the mid term, we expect we'll want to introduce a new benchmarking approach that will support these needs.

**Comment by shonfeder** [comment]
Closed by https://github.com/informalsystems/apalache-tests/pull/80
