### ISSUE TITLE
[FEATURE] Better diagnostics in the assignment finder

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#111]
When the assignment solver fails, Apalache just writes:

> Assignment error: Failed to find assignments and symbolic transitions in ...

As a result, the users have to bisect their specs manually, in order to find the missing assignments. The errors are often caused by copy-paste and wrong use of `UNCHANGED`. It would be great to have the following enhancements:

1. When the assignment finder fails, it should show the variables, for which it could not find assignments. As a first approximation, we could run the assignment finder on singleton sets, to see, whether it is possible to find assignments without considering cyclic dependencies.

1. When the assignment finder fails, we can extract an UNSAT core and point to the parts of the specification that are touched by the core. This will give the user at least some ideas of where to look for problems.

**Comment by konnov** [comment]
We should fix this to improve usability

**Comment by konnov** [comment]
@Kukovec is it still relevant?

**Comment by Kukovec** [comment]
Nope, kill it.
