### ISSUE TITLE
[FEATURE] Change the format of uninterpreted constants

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1130]
In the current format, we have to write uninterpreted constants as `uval_TYPE_name`, e.g.:

```tla
  /\ tmState = "uval_SORT_STATE_init"
```

See [TwoPhaseUFO](https://github.com/informalsystems/apalache/blob/unstable/test/tla/TwoPhaseUFO.tla) for more examples.

I find the current notation to be verbose and hard to read. I am proposing to change it to the more readable format:

```
name_OF_TYPE
```

So the above example would look like follows:

```tla
  /\ tmState = "init_OF_SORT_STATE"
```

The benefit of this new format is that the most important part of the constant appears on the left, that is, `init`. Moreover, the type and the infix `_OF_` are both capitalized, and they appear on the right, which is more convenient to type and read. It is also more consistent with our type annotations.

**Comment by konnov** [comment]
This is a purely usability feature. @Kukovec what do you think?

**Comment by Kukovec** [comment]
I have no strong attachments to either syntax, if you like this one more we can easily change it.
