### ISSUE TITLE
[DESIGN] Write an ADR about the UFO fragment

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1132]
We have work planned on the efficient checking of the restricted fragment of TLA+. This fragment contains uninterpreted first-order logic, which is used, e.g., in Ivy. We should write the design document that explains this fragment and its relation to efficient SMT techniques. This is a summary of the preliminary discussions with @Kukovec:

 - Who is the user? It is not the systems engineer, but a verification engineer.
 - What's included:
   - Boolean connectives,
   - uninterpreted functions (to Booleans and uninterpreted sorts),
   - quantifiers over special sets that capture sorts, e.g, `\A x \in Values_FOO: P` and `\E x \in Values_BAR`. The set `Values_X` captures all values of the sort `X`,
   - operators and let-in definitions, potentially inlined by the preprocessing steps,
   - potentially, flat sets as syntax sugar for predicates.

An example of two-phase commit in this fragment: [TwoPhaseUFO](https://github.com/informalsystems/apalache/blob/unstable/test/tla/TwoPhaseUFO.tla)

This fragment would require us to develop special rewriting rules (which are much simpler than what we have) and write a custom model checker. Alternatively, we could translate specs of this fragment into [VMT](https://nuxmv.fbk.eu/pmwiki.php?n=Languages.VMT) and use the tools that support this format. For instance, we could run [nuxmv](https://nuxmv.fbk.eu/) or [ic3po](https://github.com/aman-goel/ic3po).

We need an ADR to describe this fragment in more detail and to scope the work in Apalache.

**Comment by konnov** [comment]
@Kukovec , this is done, right?

**Comment by konnov** [comment]
@Kukovec shall we close this issue?

**Comment by Kukovec** [comment]
This was closed by #1246 I suppose
