### ISSUE TITLE
[FEATURE] Reflect  CLI tool commands in documentation

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/apalache#1135]
The documentation about commands available in Apalache is quite outdated. In particular, the following subcommands available to the user are not reflected in [Running the tool](https://apalache.informal.systems/docs/apalache/running.html):

- config
- typecheck
- test

What's especially unpleasant is that the `test` command already provides quite useful functionality, which could be employed by the users to their benefits, but they don't know about its existence or how to use it properly. Here is the excrept from the tool help info:

```sh
apalache test [command options] <file> <before> <action> <assertion> : Quickly test a TLA+ specification
      --cinit=STRING : the name of an operator that initializes CONSTANTS,
                       default: None
      <file>    : a file containing a TLA+ specification (.tla or .json)
      <before>  : the name of an operator to prepare the test, similar to Init
      <action>  : the name of an action to execute, similar to Next
      <assertion> : the name of an operator that should evaluate to true after executing `action`
```

This clearly goes into the direction of [RFC 06 Unit testing](https://apalache.informal.systems/docs/adr/006rfc-unit-testing.html), and although not implementing it in the nicest form, still is pretty good for unit testing the specs; I've used it e.g. for [unit testing of the Agoric kernel model](https://github.com/informalsystems/agoric-kernel-models/blob/main/kernel/kernel_test.tla).

**Comment by konnov** [comment]
@shonfeder proposes to auto-generate this

**Comment by shonfeder** [comment]
As part of this, let's also auto generate the default configuration file, and include that in the docs.

**Comment by thpani** [comment]
No auto-generation yet, but docs on the mentioned commands have been added in #1852.
