### ISSUE TITLE
Integrate all CLI options into the configuration management system

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#1177]
With #1160, it should be quite simple to add new configurations through the configuration system. We should expose all configurations that are currently configurable via CLI via the configuration files too.

In particular, the tuning options are a good fit for this.

I propose making this work item dependent on #1174: once we have moved the configuration parameters into a class, it will be trivial to drop the class into the the class targeted by PureConfig.

Suggested by @konnov https://github.com/informalsystems/apalache/pull/1160/files#r769408346

**Comment by thpani** [comment]
Just leaving a note to document that we currently have two kinds of boolean commandline flags:

- binary flags, e.g., `--debug` and `--smtprof`, and
- tri-state flags, e.g., `--profiling` and `--write-intermediate`

The latter are 3-state to enable overriding env vars + config options. These should probably be unified as part of this effort.

**Comment by shonfeder** [comment]
The problem @thpani identified should be fixed by https://github.com/informalsystems/apalache/pull/2041
