### ISSUE TITLE
Draft guidelines on project coordination

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#1180]
This is just to track ongoing work by @gabrielamafra and myself on iterating on and evolving our project planning, coordination, and communication processes.

- [x] Create milestones to group ongoing work on features (see https://github.com/informalsystems/apalache/milestone/47)
- [x] Create new project board that uses milestones and views to provide more focused insights into our plans and WIP (see https://github.com/orgs/informalsystems/projects/30/views/1)
- [x] Draft guidelines on how to interpret and utilize the various github features for project management, and how to prioritize work

**Comment by shonfeder** [comment]
@konnov Note that one implication of the suggestion made here around use of milestones and labels is that https://github.com/informalsystems/apalache/milestone/47 shouldn't be a milestone. However, according to the proposed usage here it _would_ make sense to create milestones for distinct documentation or tutorial efforts that required multiple smaller units of work to complete. But "Tutorials and documentation" is a shared quality of work, and not something that can be finished or completed.

**Comment by konnov** [comment]
True. This milestone sounds like "write code". My main reason for having that milestone was to make it a look like a piece of work to move it forward. Nobody likes writing docs :)
