### ISSUE TITLE
Feature FLINT: A linter for TLA+

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#120]
TLA+ as a language has a few annoying issues that could be found statically by using a set of simple rules. This could be done by implementing a simple linter over IR. Below we enumerate several issues that occur in practice. Feel free to submit your own ideas.

1. Fruitless set operations that involve an empty set: `X \union {}` and `X \setminus {}`.
1. Typos in constant names, e.g., `"Foo"` and `"foo"`.
1. Cardinality overkill: `Cardinality(S) = 0` instead of writing `S = {}`.

**Comment by lemmy** [comment]
@konnov Will this functionality be implemented in a way such that the Toolbox can use it?

**Comment by konnov** [comment]
Yes, we create do an independent jar that depends on the IR and the parser.

**Comment by andrey-kuprianov** [comment]
The linter should also support conversions between TLA+ and JSON (TLA+ to JSON is already implemented in unstable; the reverse direction is missing)

**Comment by konnov** [comment]
Why should that be a part of linter?

**Comment by andrey-kuprianov** [comment]
because I don't know where else to have this functionality?;)

but seriously, these conversions are lightweight, and do not depend on anything model-checker specific. we could consider the linter to be a general tool for lightweight code analysis and transformations; i.e. smth. that can be used in the development routine, with guaranteed runtime < 1 minute.

**Comment by konnov** [comment]
We have `apalache parse` for quick parsing. Similarly, we can introduce `apalache import` for all kinds of import functions. It actually looks like a good idea to process JSON files via SANY, in order to catch semantic errors, see [this reddit post](https://www.reddit.com/r/tlaplus/comments/fwniyc/does_tla_have_tools_to_process_inputs_in_the_json/). We could do: JSON import -> IR -> pretty printing in TLA+ -> SANY -> parser -> IR -> pretty printing in TLA+.

**Comment by andrey-kuprianov** [comment]
sure, we can do that as well. I am only more in favor of having several small specialized tools, instead of growing one big tool... but it's a matter of taste. Also, as soon as we have this functionality, we can always shuffle the pieces around, and see what makes more sense

**Comment by konnov** [comment]
Currently, we have a good decomposition into module jars, which could be published at Maven Central (there was no need so far).

**Comment by konnov** [comment]
Closing this issue. This should be done outside of the Apalache.
