### ISSUE TITLE
[FEATURE] JSON importer

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#121]
Similar to #77, we should introduce an importer from Apalache IR in the JSON format into Apalache IR. Optionally, we could invoke semantic checks by SANY as follows: JSON import -> IR -> pretty printing in TLA+ -> SANY -> SanyImporter -> IR.

This feature will be useful for testing frameworks and other tools, e.g., see [this Reddit post](https://www.reddit.com/r/tlaplus/comments/fwniyc/does_tla_have_tools_to_process_inputs_in_the_json/).

**Comment by andrey-kuprianov** [comment]
Closing this issue for now; the JSON encoding works fine, but **NB! will need to be changed in the near future**: see #153
