### ISSUE TITLE
[BUG] Simplificiation of neutral arithmetic expression can be inconsistent

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#1235]
## Description

Initially reported by @Kukovec on #1228, the recent changes to the `ConstSimplifierBase` in #1231 seem to introduce some non-confluent arithmetical simplifications.

## Failing test

```scala
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running at.forsyte.apalache.tla.pp.TestDesugarer
Tests run: 28, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.729 sec
Running at.forsyte.apalache.tla.pp.TestExprOptimizer
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.065 sec
Running at.forsyte.apalache.tla.pp.TestNormalizer
Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.049 sec
Running at.forsyte.apalache.tla.pp.TestParameterNormalizer
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec
Running at.forsyte.apalache.tla.pp.TestConstSimplifier
Tests run: 19, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 25.014 sec <<< FAILURE!
simplifies arithmetical operations with their neutral values(at.forsyte.apalache.tla.pp.TestConstSimplifier)  Time elapsed: 0.388 sec  <<< ERROR!
org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException: TestFailedException was thrown during property evaluation.
  Message: 1930172387802112260 was not equal to 1930172387802112377 when simplifying (-1926341659 * -1001988603) ^ 1
  Location: (TestConstSimplifier.scala:59)
  Occurred when passed generated values (
    arg0 = -1926341659 * -1001988603
  )
```

## Expected behavior

In the property test `simplifies arithmetical operations with their neutral values` we expect that the simplification of an arbitrary expression is always the same as the simplification of that expression with a neutral value applied (e.g. if our base expression is `x`, then `x + 0 = x`). However, we are seeing divergence  between the simplified base expression and the simplification derived by applying `f x = x ^ 1`.

I believe this is because the base of exponentiation now goes through doubles: https://github.com/informalsystems/apalache/blob/unstable/tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ConstSimplifierBase.scala#L104-L117

Here's a small example from the scala repl showing how this causes the simplified values to diverge: 

```
scala> BigDecimal(Math.pow((BigInt(-1926341659) * BigInt(-1001988603)).toDouble, 1)).setScale(0, BigDecimal.RoundingMode.DOWN).toBigInt
res20: scala.math.BigInt = 1930172387802112260

scala> (BigInt(-1926341659) * BigInt(-1001988603))
res21: scala.math.BigInt = 1930172387802112377
```

My gut feeling here is that, contrary to the conclusion we reached here last week, this shows that we probably **don't** want to route simplification via floats. I think that the issues around slow computation of large exponents probably doesn't justify introducing floating-point errors into people specs.

**Comment by gabrielamafra** [comment]
What if we do something like
1. Check that the float result for the exponentiation is within limit
2. Calculate using `BigInt#pow`

This way we can still have a nice way of limiting size and the result is always correct. The only non-determinism would be on the edge cases (Double min and max values), where sometimes an error is raised and sometimes the computation goes through. WDYT?

**Comment by konnov** [comment]
Just a copy from #1228:

**Comment by konnov** [comment]
> What if we do something like
> 
> 1. Check that the float result for the exponentiation is within limit
> 2. Calculate using `BigInt#pow`
> 
> This way we can still have a nice way of limiting size and the result is always correct. The only non-determinism would be on the edge cases (Double min and max values), where sometimes an error is raised and sometimes the computation goes through. WDYT?

@gabrielamafra, I did not read your comment. I am totally for this solution!
