### ISSUE TITLE
[BUG] Staking model example, a confusing behavior of the solver

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/apalache#1245]
## Description

I was going through [the Atomkraft staking example](https://github.com/informalsystems/atomkraft/blob/main/examples/cosmos-sdk/generator/README.md), in particular, the predicate [`NoUnbondAndTransfer`](https://github.com/informalsystems/atomkraft/blob/b335f7edc5ccc20174ece3117f259c05dc492bfd/examples/cosmos-sdk/generator/MC_Staking.tla#L87). 
The predicate says that some property should hold for `state1`, `state2` and `state3` defined as 
```
     LET state1 == trace[2] IN
     LET state2 == trace[3] IN
     LET state3 == trace[4] IN
     LET Example ==            
           ...
     IN ~EXAMPLE  
```
And, as expected, running 
`apalache check --inv=NoUnbondAndTransfer --run-dir=exp22 --max-error=3 --view=TxView MC_Staking.tla`
produces 3 counterexamples.

Then I created a modification of it, `NoUnbondAndTransferPickSteps`
where I changed the relevant part into 
```
\E i, j, k \in 2..5: 
        /\ i < j
        /\ j < k
        /\ 
            LET state1 == trace[i] IN
            LET state2 == trace[j] IN
            LET state3 == trace[k] IN
            LET Example ==            
           ...
           IN ~EXAMPLE  
```

This time, however, Apalache did not find any counterexample.

For a sanity check, I created another modification, called `NoUnbondAndTransferPickStepsFake`, in which I fixed the values of `i`, `j`, and `k`. The relevant part is 
```
    \E i, j, k \in 2..5: 
        /\ i = 2
        /\ j = 3
        /\ k = 4
        /\ 
            LET state1 == trace[i] IN
            LET state2 == trace[j] IN
            LET state3 == trace[k] IN
            LET Example ==            
           ...
           IN ~EXAMPLE  
```
 
This time, the counterexample is again found.

Is this a bug or did I get something wrong here?

## Input specification
Attaching the .zip containing three documents necessary to reproduce the behaviour:
 - MC_Staking.tla
 - Staking.tla
 - Staking_typedefs.tla

## The command line parameters used to run the tool

- `--inv=NoUnbondAndTransfer  --max-error=3 --view=TxView MC_Staking.tla`
- `--inv=NoUnbondAndTransferPickSteps  --max-error=3 --view=TxView MC_Staking.tla`
- `--inv=NoUnbondAndTransferPickStepsFake  --max-error=3 --view=TxView MC_Staking.tla`

## System information

- Apalache version: 0.17.5
- OS: MacOS 12.0.1
- JDK version: 1.8.0

**Comment by rnbguy** [comment]
A minimal example which produces this.

```
---- MODULE test ----
EXTENDS TLC, Integers, Sequences

VARIABLES 
    \* @type: Int;
    x

Init == x = 0

Next == x' = x + 1 \/ x' = x + 3

\* @type: Seq([x: Int]) => Bool;
Inv(trace) ==
    \E i, j \in 2..5: 
        /\ i < j
        \* /\ i = 2
        \* /\ j = 3
        /\  LET state1 == trace[i] IN
            LET state2 == trace[j] IN
            LET Example ==
                /\ Len(trace) > 3
                /\ state1.x = 1
                /\ state2.x = 2
            IN
            ~Example

====
```

Weirdly enough, removing `Len(trace) > n` line, produces the counter-examples. (Also checked with `MC_Staking.tla`)

**Comment by rnbguy** [comment]
Looks like, you and both overlooked that the `~` should be outside of `\E`. It was a mistake, it should be as following,

```
\* @type: Seq([x: Int]) => Bool;
Inv(trace) ==
    ~\E i, j \in 2..5: 
        /\ i < j
        /\  LET state1 == trace[i] IN
            LET state2 == trace[j] IN
            LET Example ==
                /\ Len(trace) > 3
                /\ state1.x = 1
                /\ state2.x = 2
            IN
            Example
```

**Comment by konnov** [comment]
@rnbguy, I think your explanation is right. I usually introduce the upper level `Example` and then negate it. Otherwise, it is way too easy to get lost in quantifiers and negations. Especially given that TLA+ is sensitive to indentation.

**Comment by rnbguy** [comment]
Yea. I only realized when I noticed the quatifier turned `\A` inside `InvariantViolation` predicate at `counterexample.tla`.

**Comment by ivan-gavran** [comment]
Great, thanks, guys :)
