### ISSUE TITLE
[BUG] Typechecker complains about a level-1 predicate used as an argument

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/apalache#1254]
## Description

While experimenting with different ways to inherit TLA+ specs, I stumbled upon an interesting complaint by Snowcat. (And I am not sure if it is a bug or not)

The code example is as follows:

```
---- MODULE base ----
EXTENDS Integers
VARIABLES 
    \* @type: Int;
    x
\* This is a trivial implementation of the function FF. The goal is that this function is injected from the extensionA module
\* @type: (Int) => Bool;
FF(a) == TRUE

\* @type: ( Int, (Int) => Bool ) => Bool;
Check(a, func(_)) == func(a)

Next ==
    x' = IF Check(x, FF) THEN x + 1 ELSE x

Init ==
    x = 2

GOAL == 
    x < 3
====
```

`extensionA.tla`:
```
---- MODULE extensionA ----
EXTENDS Integers
VARIABLES 
    \* @type: Int;
    x


\* @type: (Int) => Bool;
CheckOrig(a) ==
    a < 4

GOAL == 
    x < 5

BASE == INSTANCE base
Next ==
    x' = IF BASE!Check(x, CheckOrig) THEN x + 1 ELSE x
Init == BASE!Init
====
```
The typechecker says: _No annotation found for FF. Make sure that you've put one in front of FF_. It says so pointing to the usage of `FF` inside the predicate `Next`. (As if it somehow disregarded the definition of `FF`).

## Input specification

 
All files are attached in [Archive.zip](https://github.com/informalsystems/apalache/files/7941523/Archive.zip).

## The command line parameters used to run the tool

I get the error when running `apalache typecheck extensionA.tla`. 
Curiously, I do not get the error when running `apalache typecheck base.tla` (which somehow suggests there is an interplay between `extensionA` and types of `base` which I di not understand). 

## System information

- Apalache version: 0.17.5
- OS: MacOS 12.0.1
- JDK version: 1.8.0

**Comment by konnov** [comment]
It looks like the annotations are not properly propagated for the operators in named instances. So yes, it is a bug in the integration with SANY.

**Comment by konnov** [comment]
This is the intermediate output after the parser:

```tla
(*
  @type:  (Int) => Bool;
*)
CheckOrig(a) == a < 4

(*
  @type:  (Int) => Bool;
*)
BASE_i_FF(a) == TRUE

(*
  @type:  ( Int, (Int) => Bool ) => Bool;
*)
BASE_i_Check(a, func(_)) == func(a)

GOAL == x < 5

BASE_i_GOAL == x < 3

BASE_i_Next == x' = (IF BASE_i_Check(x, FF) THEN x + 1 ELSE x)                   

BASE_i_Init == x = 2

Next == x' = (IF BASE_i_Check(x, CheckOrig) THEN x + 1 ELSE x)

Init == BASE_i_Init
```

For some reason, `FF` was not substituted with `BASE_i_FF`.
