### ISSUE TITLE
[BUG] Type variables clash with fresh variables when the type checker is applied twice

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1255]
An interesting bug has popped up in #1253. The type checker sometimes fails when it is applied to its own results. This is caused by polymorphic signatures. Concretely, `ToEtcExpr` is using a pool of fresh variables that collides with the type variables that were introduced by `ToEtcExpr` itself in the first run. The reason for this bug is that `ToEtcExpr` was first written under the assumption that user-defined operators are not polymorphic (back in 2020).

This test was found by a unit test in `TestTypeCheckerTool`. In #1253, the failing test is isolated in the test: `"the tool consumes its output on TlcSpec1"`

Since the new rewiring approach in #1253 is using polymorphic operators, this bug appears. I could not reproduce it on individual runs of `typecheck`, so the type checker is relatively safe to use in the CLI.

**Comment by rnbguy** [comment]
Hi @konnov, I am not sure if this bug is completely gone in `v0.20.2`. I am getting following error on following TLA+ spec.

```
[test.tla:14:8-14:12]: No match between operator signature ((c, c) => Bool) and arguments STATE and Int E@11:21:50.110
[test.tla:13:1-14:12]: Error when computing the type of Init      E@11:21:50.111
```

```
---- MODULE test ----
EXTENDS Integers

(*
@typeAlias: STATE = Int;
*)
typedefs == TRUE

VARIABLES 
    \* @type: STATE;
    x

Init ==
    /\ x = 0

Next == 
    /\ x' = x + 1

====
```

<sub>PS: I did not want to duplicate issues. I would open a new issue, if my bug is unrelated.</sub>
