### ISSUE TITLE
[BUG] Unexpected polymorphism in chains of LET-INs

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1259]
Here is an MWE:

```tla
------------------ MODULE Test ---------------------
VARIABLES
    \* @type: Str -> Int;
    fun

\* @type: (a -> b) => (a -> b);
Foo(f) ==
    LET \* @type: a -> b;
        f2 == f
    IN
    LET
        d == DOMAIN f2
    IN
    [ x \in d |-> f[x] ]

Init ==
    LET F == Foo([ x \in { "a" } |-> 1 ])
    IN
    fun = F

Next ==
    UNCHANGED fun
====================================================
```

The checker does not fail on this test. However, in the intermediate output after the type checker, the definition of `d` has its own independent free type variable:

```tla
(*
  @type: (((h -> i)) => (h -> i));
*)
Foo(f) ==
  LET (*@type: (() => (h -> i)); *) f2 == f IN
  LET (*@type: (() => Set(n)); *) d == DOMAIN f2 IN [ x \in d |-> f[x] ]
```

This causes the type checker to complain in more complex specs. Still have to come up with a small failing test.

**Comment by Kukovec** [comment]
Just posting this for future reference, this might also unblock #359.

**Comment by konnov** [comment]
Here is a variation of the above test that makes the type checker fail, though it should not:

```tla
------------------ MODULE Test ---------------------

VARIABLES
    \* @type: Str -> Int;
    fun

\* @type: (a -> b) => (a -> b);
Foo(f) ==
    LET \* @type: a -> b;
        f2 == f
    IN
    LET
        d == DOMAIN f2
    IN
    [ x \in d |-> f[x] ]

Init ==
    fun = Foo([ x \in { "a" } |-> 1 ])

Next ==
    UNCHANGED fun
====================================================
```

**Comment by konnov** [comment]
Here is the description of the actual bug. The type of f2 was inferred to be polymorphic and, as a result, the type of d also became polymorphic. It’s a bug, but it was impossible to see at the annotation level. I think we should make explicit the type quantifiers, which are currently implicit. With explicit quantifiers, I would have seen the bug immediately.
