### ISSUE TITLE
[FEATURE] Make apalache folds compatible with community folds

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1267]
As the next step toward #870, we should refactor folds in `Apalache.tla`. We cannot easily rewire [FiniteSetsExt.tla](https://github.com/tlaplus/CommunityModules/blob/master/modules/FiniteSetsExt.tla), because both `FiniteSetsExt` and `Apalache` define the operator `FoldSet`, and we have to use Apalache `FoldSet` in the rewired version of `FiniteSetsExt`. The same applies to [FiniteSeqsExt.tla](https://github.com/tlaplus/CommunityModules/blob/master/modules/SequencesExt.tla).

Moreover Apalache `FoldSet`

https://github.com/informalsystems/apalache/blob/7c7d5a56ba4f94a0c3ea6691e0de86e56ef6ac23/src/tla/Apalache.tla#L72-L83

differs from the community `FoldSet`

https://github.com/tlaplus/CommunityModules/blob/e081b9acb4491b3d3e74667a5b4a4eda675fe8ff/modules/FiniteSetsExt.tla#L7-L14

It looks like the difference is only in the order of the arguments: Apalache `FoldSet` accumulates the result in the first argument, whereas the community `FoldSet` accumulates the result in the second argument. Perhaps, it is more subtle.

I propose to prefix Apalache's `FoldSet` and `FoldSeq` e.g., with `Apa`, so we do not clash with `FiniteSetsExt`. In case, our definition of `FoldSet` is more general, we have to extend the one in the community modules.

@Kukovec, do you like to follow on this one, as you have implemented folds?

**Comment by shonfeder** [comment]
@Kukovec asked me to mention him on an issue to test notifications :)

**Comment by konnov** [comment]
This is resolved with [__apalache_folds.tla](https://github.com/informalsystems/apalache/blob/unstable/src/tla/__apalache_folds.tla)
