### ISSUE TITLE
[BUG] Generated JSON IR is not parsed back

### ISSUE THREAD

**Issue by craft095** [informalsystems/apalache#1281]
## Description

Json-file generated with `parse` command is not parsed.

## Input specification

```
---- MODULE D ----

VARIABLE 
    \* @type: Bool;
    x
Spec == x \in BOOLEAN

====
```

## The command line parameters used to run the tool

Two steps:
1) java -cp apalache.jar  parse --output=D.json D.tla
2) java -cp apalache.jar  parse D.json

## Expected behavior

D.json is successfully parsed

## Log files

```
12:08:02.224 [main] INFO  a.f.a.t.Tool$ - Parse D.json
12:08:02.224 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser
12:08:02.297 [main] ERROR a.f.a.t.i.p.SanyParserPassImpl -   > '(' expected but record field 'Untyped' found
12:08:02.297 [main] ERROR a.f.a.t.i.p.SanyParserPassImpl -   > Error parsing file C:\work\TLA\apalache\D.json
12:08:02.297 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser [FAIL]
12:08:02.297 [main] INFO  a.f.a.t.Tool$ - Parser has failed
12:08:02.298 [main] INFO  a.f.a.t.Tool$ - It took me 0 days  0 hours  0 min  0 sec
12:08:02.298 [main] INFO  a.f.a.t.Tool$ - Total time: 0.448 sec
```
## System information

- Apalache version [`apalache-mc version`]: 0.19.3 build 52f9fe2
- OS: Ubuntu Linux 20.04
- JDK version: OpenJDK Runtime Environment Zulu17.28+13-CA

**Comment by Kukovec** [comment]
Thanks for posting the report. The issue was that the JSON importer was expecting fully-typed JSON files, but the output of `parse` is untyped (since parsing doesn't invoke the type-checker). We've relaxed this input requirement, so `parse` should be idempotent now.

**Comment by craft095** [comment]
`parse` works now, but `typecheck` still fails with the same model:

```
$ java -jar apalache-new.jar typecheck D.json
# APALACHE
# version: 70aa270
# build  : 70aa270
#
# Usage statistics is OFF. We care about your privacy.
# If you want to help our project, consider enabling statistics with config --enable-stats=true.

Output directory: /mnt/c/work/TLA/apalache/_apalache-out/D.json/2022-02-04T17-16-10_7301352637637835910
Type checking D.json                                              I@17:16:11.269
PASS #0: SanyParser                                               I@17:16:11.276
PASS #1: TypeCheckerSnowcat                                       I@17:16:11.426
 > Running Snowcat .::.                                           I@17:16:11.426
Typing input error: Expected a type annotation for VARIABLE x     E@17:16:11.458
It took me 0 days  0 hours  0 min  0 sec                          I@17:16:11.459
Total time: 0.864 sec                                             I@17:16:11.460
EXITCODE: ERROR (255)```

**Comment by Kukovec** [comment]
Yes, that's expected, because you have to produce a JSON file that is typed. 
To do this, you first need to run `typecheck --output=D.json D.tla` (instead of `parse`), after which you can `typecheck D.json`, which should pass, since the JSON generated from `typecheck` is typed.

**Comment by shonfeder** [comment]
Note that the `--output` flag for `typecheck` has just been added, but should be in the release that is being cut now.

**Comment by konnov** [comment]
Right. The json serializer is not reading/writing general annotations. This is scheduled for #804. As @Kukovec mentioned, it does correctly output types, so the output of `typecheck` can be consumed by `parse` and `typecheck` again.

**Comment by craft095** [comment]
I see, thank you!
