### ISSUE TITLE
[FEATURE] Add integration tests for json 

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1282]
As shown in #1281, we could produce json by `parse` and `typecheck` from all the tests files that we have in `src/tla`. @shonfeder do you there is a simple solution that does not require us to copy & paste tests for all the files?

**Comment by konnov** [comment]
On a second thought, @Kukovec will first try to do it directly with ScalaCheck. This looks like a perfect case for PBT.

**Comment by konnov** [comment]
This is mainly done with Scalacheck in #1291 now. However, we have to add a few integration tests, just to make sure that things do not break somewhere else.

**Comment by shonfeder** [comment]
I’d just suggest not actually looking at the content of the json in the integration tests. You can check that the expected file is created, or that you can produce and then read in the file, but I wouldn’t recommend against inspecting the json itself. That amounts to testing the json serialization lib in the integration tests, and m might be brittle and not deliver much value.

**Comment by konnov** [comment]
Yes, I agree that we should not look inside just do parse-parse or typecheck-parse.

**Comment by konnov** [comment]
We have unit tests, ScalaCheck tests, and a few integration tests. So I am closing this issue.
