### ISSUE TITLE
[FEATURE] Move some operators to ApalacheInternalOper

### ISSUE THREAD

**Issue by rodrigo7491** [informalsystems/apalache#1287]
A number of new IR operators have been added to `ApalacheOper` when working towards #360. These new operators are not exposed to users and, as suggested by @konnov, could be moved to a new `SMTOper` class.

**Comment by konnov** [comment]
We have introduced the class `ApalacheInternalOper` for this. The following operators should be moved from `ApalacheOper` to `ApalacheInternalOper`:

 - `distinct`
 - `selectInSet`
 - `storeInSet`
 - `storeNotInSet`
 - `smtMap`
 - `unconstrainArray`
