### ISSUE TITLE
[BUG] Support for `--view` is broken by TLC rewiring

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1305]
We have migrated `:>` and `@@` to a custom TLC module in #1253. Hence, `:>` and `@@` should not appear in the code produced by Apalache. However, they do appear in counterexamples. As a result, generation of multiple counterexamples with `--view` got broken, as there is no SMT support for `:>` and `@@` anymore. Thus, we should expedite #1226 to fix this and support the MBT team.

**Comment by ivan-gavran** [comment]
wunderbar!
