### ISSUE TITLE
[FEATURE] Improving Snowcat error messages

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1341]
The current error messages by Snowcat refer to the type signatures, which are internal to the mechanics of Snowcat. As correctly pointed out in  #955, these messages are hard to understand.

On one hand, the type checker itself is unaware of the actual TLA+ operators, as it is working over `EtcExpr`. As a result, the type checker relies on the generic error reporting:

https://github.com/informalsystems/apalache/blob/dec42b8ba2ada9c8c306d320fe731f8a4787dcb9/tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala#L148-L154

On the other hand, [ToEtcExpr](https://github.com/informalsystems/apalache/blob/dec42b8ba2ada9c8c306d320fe731f8a4787dcb9/tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala) is in the best position to explain error messages. We could add an optional callback to [EtcExpr](https://github.com/informalsystems/apalache/blob/dec42b8ba2ada9c8c306d320fe731f8a4787dcb9/tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcExpr.scala) that receives the inferred types of the arguments (as in the general callback) and explains the mismatch. Then, the general callback in `EtcTypeChecker` could call the specialized callback, if it is defined.

I think the best course of action is to evaluate error messages by adding a few specialized callbacks in `ToEtcExpr` and, if it works well, adding callbacks to all the cases. @gabrielamafra what do you think about this?

**Comment by gabrielamafra** [comment]
I'm not sure I understand your proposal. `ToEtcExpr` and `EtcTypeChecker` are two entire different runs that are not connected by callbacks or anything else, I'm struggling to see how we cold connect them with callbacks.

Looking at the implementation, my idea to allow expression information to be used on type error reporting is to keep a map from expression ID to the original expression (similar to `sourceStore`) to be used by `EtcExpr` in `EtcTypeChecker` error callback, but this seems to deviate from your idea. I wonder if I'm missing something from your suggestion.

**Comment by konnov** [comment]
Source tracking is not an issue. `EtcExpr` is carrying `sourceRef` that is pointing to the source id.

What we are lacking is a user-friendly explanation that refers to the semantics of a particular operator. For instance, we have this translation in `ToExpr`:

https://github.com/informalsystems/apalache/blob/8a0a392f823d50f0d3575d921efb632ae2c412ee/tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala#L209-L213

We could introduce an optional callback in `EtcExpr`, which `EtcTypeChecker` would call, e.g., here:

https://github.com/informalsystems/apalache/blob/8a0a392f823d50f0d3575d921efb632ae2c412ee/tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala#L135-L141

The callback for the equality operator could look like:

```scala
def explainArgsMatchError(sig: OperT1, argTypes: Seq[TlaType1]): String = {
  "Equality expected two arguments of equal types, found: " + String.join(" and ", argTypes.map(_.toString))
}
```

We could attach the callback in `ToEtcExpr` like this:

```scala
mkExRefApp(opsig, args).setOnArgsMatchError(explainArgsMatchError)
```

This is all very schematic and it probably requires more thinking, but this is basically the idea. Not sure how much drop in the performance it would incur though.

**Comment by gabrielamafra** [comment]
I see. I thought the intention was to have explanations specific to the original TLA expression form, but seems like just using more of the ETC information can be sufficient. I'll try that, thanks!

**Comment by konnov** [comment]
oh, right. Mentioning the original expression would be perfect but that would require some serious rework of error reporting. It is somehow planned in #943.

**Comment by shonfeder** [comment]
@gabrielamafra  has noted that this issue can be refactored into a milestone and smaller issues.

**Comment by gabrielamafra** [comment]
After some exploration, I've break this down into two rather big issues with a more specific description of what to do from what we learned in this initial exploration. They are
- https://github.com/informalsystems/apalache/issues/1581
- https://github.com/informalsystems/apalache/issues/1582

If it makes sense, the tasks on the second issue can be turned into issues once we are executing them.

I'll close this in favor of the more specific issues just created.
