### ISSUE TITLE
[FEATURE] Add function operators to IrGenerators

### ISSUE THREAD

**Issue by thpani** [informalsystems/apalache#1355]
Extend `IrGenerators` to also apply function operators. This would be useful in property-based tests such as the ones added in #1344. Original request: https://github.com/informalsystems/apalache/pull/1344#discussion_r807066075

- [x] Extend `IrGenerators` to also apply function operators
- [x] Use them for PBT in `TestKeramelizer`
- [x] Identify other places these can be used

**Comment by thpani** [comment]
@konnov Keramelizer doesn't care about function operators, so it seems a bit overkill to implement this just for that. Would it be useful anywhere else?

**Comment by konnov** [comment]
right. They are probably less important for Keramelizer. However, these are important operators, and it would be good to have them in other ScalaCheck tests
