### ISSUE TITLE
[BUG] make package fails

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1368]
```
make package
...
[info] Unpacking package /Users/igor/devl/apalache/target/universal/apalache-0.20.4-SNAPSHOT.tgz
[error] tar: Option --overwrite is not supported
[error] Usage:
[error]   List:    tar -tf <archive-filename>
[error]   Extract: tar -xf <archive-filename>
[error]   Create:  tar -cf <archive-filename> [filenames...]
[error]   Help:    tar --help
[info] Symlinking /Users/igor/devl/apalache/target/universal/current-pkg -> /Users/igor/devl/apalache/target/universal/apalache-0.20.4-SNAPSHOT
[success] Total time: 59 s, completed Feb 18, 2022 9:06:30 AM
```

Platform: MacOS 12.1

The worst of it is that the command does not fail.

**Comment by konnov** [comment]
Related to that, I guess we have seriously restricted our building setup to Linux/MacOS. We could probably build the project on Windows with maven (never checked that).

**Comment by konnov** [comment]
If I remove the option `--overwrite`, `make package` produces another error:

```
[info] Unpacking package /Users/igor/devl/apalache/target/universal/apalache-0.20.4-SNAPSHOT.tgz
[error] x apalache-0.20.4-SNAPSHOT/
[error] x apalache-0.20.4-SNAPSHOT/LICENSE
[error] x apalache-0.20.4-SNAPSHOT/bin/
[error] x apalache-0.20.4-SNAPSHOT/lib/
[error] x apalache-0.20.4-SNAPSHOT/lib/apalache.jar
[error] x apalache-0.20.4-SNAPSHOT/bin/apalache-mc
[info] Symlinking /Users/igor/devl/apalache/target/universal/current-pkg -> /Users/igor/devl/apalache/target/universal/apalache-0.20.4-SNAPSHOT
[success] Total time: 27 s, completed Feb 18, 2022 9:14:38 AM
```

**Comment by thpani** [comment]
For now, you can probably just undo #1357 / 22517bdc27be22f60f9c5fc220a032945364a0a3 ?

**Comment by shonfeder** [comment]
@konnov FYI, sbt will prefix output to stderr with `error` log, but that doesn't mean the command has failed. See https://stackoverflow.com/questions/14504572/sbt-suppressing-logging-prefix-in-stdout 

Looks like I might be able to fix this to avoid future confusion.

**Comment by shonfeder** [comment]
Reguarding building on windows: I don't think anything about the move to SBT should impact windows users.

The task added in #1357 and the `tar` invocation is only about getting the runner script and jar in a place that is available on user's paths. Windows users *should* still be able to build using a different sbt target without any problems, and in any case, they can't use the runner script unless they are on WSL anyhow.

afaiu, we can always add a target for windows builds, or build windows-friendly packages if we want to add specific suppoort for windows.

**Comment by konnov** [comment]
One good thing about maven was cross-platforming. If we know that apalache does not build on windows, but it can run on windows, we should reflect that in the manual. Perhaps, sbt provides an equivalent of tar?

**Comment by shonfeder** [comment]
There is nothing that should prevent sbt from building on windows afaik.

**Comment by shonfeder** [comment]
Ah, but I see we also have windows info in the `Running in Java Virtual Machine`, I'll update this for now.

**Comment by shonfeder** [comment]
The other mention of windows is in `Running in Java Virtual Machine`, where we instruct people to download the latest release and run the jar :)

**Comment by konnov** [comment]
It looks like all is fixed, so we can close this issue 🎸
