### ISSUE TITLE
[FEATURE] Automate imports management

### ISSUE THREAD

**Issue by gabrielamafra** [informalsystems/apalache#1389]
It would be nice to use some tools to help us manage our imports, including:
- Removing unused imports
- Keeping a consistent order between imports

@thpani suggested [scalafix](https://scalacenter.github.io/scalafix/docs/rules/RemoveUnused.html)

**Comment by thpani** [comment]
Cool! Looks like [import sorting can be done through scalafmt](https://scalameta.org/scalafmt/docs/configuration.html#imports-sort--original).
