### ISSUE TITLE
[FEATURE] Rewrite `S \subseteq T`

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1408]
We now have two implementations of `S \subseteq T`:
 - [SetInclusionRule](https://github.com/informalsystems/apalache/blob/52b503ed5b260ea4fc698afecaabfa32c072beb7/tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInclusionRule.scala) for the default encoding, and
 - [SetInclusionRuleWithArrays](https://github.com/informalsystems/apalache/blob/52b503ed5b260ea4fc698afecaabfa32c072beb7/tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInclusionRuleWithArrays.scala) for the arrays encoding.

There is no need for these rules. When `S` and `T` are general sets, we can rewrite the `S \subseteq T` as `\A x \in S: x \in T`. When `S` is a general set and `T` is `SUBSET V`, we can rewrite `S \subseteq SUBSET V` as `\A x \in S: x \ in V`. This will open space for optimizations.

Related to #1103.

**Comment by p-offtermatt** [comment]
Could you double-check the second part of the issue?
 `\A x \in S: x \ in V` seems like the rewriting for `S \in SUBSET V`, not for `S \subseteq SUBSET V`.
A valid rewriting for `S \subseteq SUBSET V` that avoids expanding SUBSET might be via double quantification: `\A X \in S: \A x \in X: x \in V`.
But please correct me if I overlooked something!

**Comment by Kukovec** [comment]
```
\A x \in S: x \ in V <=>
S  \subseteq V
```
```
S \subseteq SUBSET V <=>
\A x \in S: x \in SUBSET V <=>
\A x \in S: x \subseteq V <=>
\A x \in S: \A y \in x: y \in V
```

**Comment by Kukovec** [comment]
Just remember to recursively call `rewrite`: 
```
rewrite(S \subseteq V) = rewrite(\A x \in rewrite(S): x \in rewrite(V))
```
