### ISSUE TITLE
[BUG] Incorrect parsing of recursive functions with 2 or more arguments

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#144]
**Describe the bug**
Parsing fails with 
`java.lang.IllegalArgumentException: requirement failed: unexpected arity 5 in rec-fun-def applied to ...`

**To Reproduce**
 - The command-line parameters that you use to run the tool `apalache-mc check GRanging.tla`
 - The problematic specification (if this cannot be submitted, try to come up with a minimal working example): http://list.cs.northwestern.edu/802.16/GRanging.tla

**Expected behavior**
What did you expect to see?
Absence of exceptions.

**Comment by konnov** [comment]
this is a rare feature, let's postpone the bugfix for a later milestone

**Comment by konnov** [comment]
Closed in #312
