### ISSUE TITLE
Non-exhautive match compiler error on TlcConfigParserApalache

### ISSUE THREAD

**Issue by thpani** [informalsystems/apalache#1471]
Blocks #1064 

`scalac` reports 2 warnings on non-exhaustive matches in `TlcConfigParserApalache`.
Unfortunately, I don't understand the parser code. @konnov do you want to take a look?

    [warn] apalache/tla-io/src/main/scala/at/forsyte/apalache/io/tlc/TlcConfigParserApalache.scala:144:37: match may not be exhaustive.
    [warn] It would fail on the following inputs: ~(~(IDENT(_), ACTION_CONSTRAINT()), IDENT(_)), ~(~(IDENT(_), ALIAS()), IDENT(_)), ~(~(IDENT(_), BOOLEAN(_)), IDENT(_)), ~(~(IDENT(_), CHECK_DEADLOCK()), IDENT(_)), ~(~(IDENT(_), COMMA()), IDENT(_)), ~(~(IDENT(_), CONST()), IDENT(_)), ~(~(IDENT(_), CONSTRAINT()), IDENT(_)), ~(~(IDENT(_), EQ()), IDENT(_)), ~(~(IDENT(_), IDENT(_)), IDENT(_)), ~(~(IDENT(_), INIT()), IDENT(_)), ~(~(IDENT(_), INVARIANT()), IDENT(_)), ~(~(IDENT(_), LEFT_BRACE()), IDENT(_)), ~(~(IDENT(_), NEXT()), IDENT(_)), ~(~(IDENT(_), NUMBER(_)), IDENT(_)), ~(~(IDENT(_), POSTCONDITION()), IDENT(_)), ~(~(IDENT(_), PROPERTY()), IDENT(_)), ~(~(IDENT(_), RIGHT_BRACE()), IDENT(_)), ~(~(IDENT(_), SPECIFICATION()), IDENT(_)), ~(~(IDENT(_), STRING(_)), IDENT(_)), ~(~(IDENT(_), SYMMETRY()), IDENT(_)), ~(~(IDENT(_), VIEW()), IDENT(_))
    [warn]     ident ~ LEFT_ARROW() ~ ident ^^ { case IDENT(lhs) ~ LEFT_ARROW() ~ IDENT(rhs) =>
    [warn]                                     ^                                     
    [warn] apalache/tla-io/src/main/scala/at/forsyte/apalache/io/tlc/TlcConfigParserApalache.scala:164:76: match may not be exhaustive.
    [warn] It would fail on the following inputs: ~(~(~(ACTION_CONSTRAINT(), IDENT(_)), _), IDENT(_)), ~(~(~(ALIAS(), IDENT(_)), _), IDENT(_)), ~(~(~(BOOLEAN(_), IDENT(_)), _), IDENT(_)), ~(~(~(CHECK_DEADLOCK(), IDENT(_)), _), IDENT(_)), ~(~(~(COMMA(), IDENT(_)), _), IDENT(_)), ~(~(~(CONST(), IDENT(_)), _), IDENT(_)), ~(~(~(CONSTRAINT(), IDENT(_)), _), IDENT(_)), ~(~(~(EQ(), IDENT(_)), _), IDENT(_)), ~(~(~(IDENT(_), IDENT(_)), _), IDENT(_)), ~(~(~(INVARIANT(), IDENT(_)), _), IDENT(_)), ~(~(~(LEFT_ARROW(), IDENT(_)), _), IDENT(_)), ~(~(~(LEFT_BRACE(), IDENT(_)), _), IDENT(_)), ~(~(~(NUMBER(_), IDENT(_)), _), IDENT(_)), ~(~(~(POSTCONDITION(), IDENT(_)), _), IDENT(_)), ~(~(~(PROPERTY(), IDENT(_)), _), IDENT(_)), ~(~(~(RIGHT_BRACE(), IDENT(_)), _), IDENT(_)), ~(~(~(SPECIFICATION(), IDENT(_)), _), IDENT(_)), ~(~(~(STRING(_), IDENT(_)), _), IDENT(_)), ~(~(~(SYMMETRY(), IDENT(_)), _), IDENT(_)), ~(~(~(VIEW(), IDENT(_)), _), IDENT(_))
    [warn]     (INIT() ~ ident ~ NEXT() ~ ident | NEXT() ~ ident ~ INIT() ~ ident) ^^ {
    [warn]                                                                            ^

**Comment by shonfeder** [comment]
I can get this one, if Igor doesn't want to. I've worked on the parser a bit.

**Comment by thpani** [comment]
@shonfeder Wanna take a stab at this then?

**Comment by shonfeder** [comment]
Yep, I'm happy to stab this! I'll look today :) Thanks.
