### ISSUE TITLE
Fix compiler deprecation and feature warnings

### ISSUE THREAD

**Issue by thpani** [informalsystems/apalache#1473]
Blocks #1064

`scalac` currently reports 7 deprecation and 14 feature warnings across our codebase. These become fatal when passing `-Xfatal-warnings` (https://github.com/informalsystems/apalache/issues/1473#issuecomment-1065161610) in #1064.

We should

- [x] enable `-feature` and `-deprecation`
- [x] #1481 
- [x] #1482

**Comment by shonfeder** [comment]
Presumably related to #1064, which is why I'm assigned/

**Comment by thpani** [comment]
@shonfeder Sorry, I meant to assign myself 😅

I don't know if the current warnings á la

    [warn] four deprecations (since 2.11.0); re-run with -deprecation for details
    
would fail with `-Xfatal-warnings`, so either this is blocked by #1064 or blocking it.

**Comment by shonfeder** [comment]
no worries! I'm happy to take the issue if you decide to change gears :)
