### ISSUE TITLE
Are model values supported?

### ISSUE THREAD

**Issue by craft095** [informalsystems/apalache#1488]
## Description

It is a question and not a bug report. I cannot figure out how to use model values in the specification.
Apalache manual seems to require that constant assigned in CFG file, must be of Str type:

```
\* CFG file fragment
CONSTANT C = C
```

```
\* TLA file fragment

CONSTANT 
   \* @type: Str;
    C
```

But if I do it this way, I cannot use it in expressions of other types:

```
\* @type: Seq(Bool);
C_1 == <<C>>
```

gives error:
```
Need annotation. Found 2 matching operator signatures ((i) => <<i>>) or ((i) => Seq(i)) for argument Str
```

I guess this error means "Bool does not match Str"

The most valuable property of a model value is that it has meaning "value different from any other value". For integers (or strings) 
 one can always choose some specific value, but for booleans it is not clear how to choose such a value.

**Comment by Kukovec** [comment]
> The most valuable property of a model value is that it has meaning "value different from any other value". For integers (or strings) one can always choose some specific value, but for booleans it is not clear how to choose such a value.

We don't support model values in the sense that TLC does. In particular, you can't invent an undetermined constant of any interpreted type (e.g. `Bool`), though you can generate arbitrary values of that type via [generators](https://apalache.informal.systems/docs/adr/006rfc-unit-testing.html#51-using-apalache-generators). What we do have are constants of [uninterpreted types](https://apalache.informal.systems/docs/HOWTOs/uninterpretedTypes.html). The way you use them is pretty simple, you just have to annotate the constant with an uninterpreted type 
```tla
CONSTANT 
   \* @type: CTYPE;
    C
```
then you can do something like
```
CInit == C = "v1_OF_CTYPE"
```

**Comment by konnov** [comment]
We also had a HOWTO on that, though it is not easy to find: https://apalache.informal.systems/docs/HOWTOs/uninterpretedTypes.html

**Comment by craft095** [comment]
@Kukovec , @konnov Thanks for the explanation, it is clear now.
