### ISSUE TITLE
Nitpicker: Leverage Scalacheck to compare different encodings

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1588]
@rodrigo7491 has been trying to debug an evasive bug in the arrays encoding for some time. I think we should approach this problem automatically.

We have `IrGenerators` for property-based testing. It should be possible to generate an expression `generated` of type `Set(genType)` and then check the following spec:

```tla
------ MODULE Oracle --------
VARIABLES
  \* @type: ${genType};
  result,
  \* @type: Bool;
  found

Init ==
  /\ result \in generated
  /\ found \in BOOLEAN

Next ==
  UNCHANGED <<result, found>>

NotFound ==
  ~found
======================
```

By checking the invariant `NotFound` of the spec `Oracle`, we will obtain a value `witness` of `result` that belongs to the set `generated`, if such a value exists. We can feed this value into the `Verifier` spec:

```tla
------ MODULE Verifier --------
VARIABLES
  \* @type: ${genType};
  result,
  \* @type: Bool;
  found

Init ==
  /\ result \in generated
  /\ result = ${witness}
  /\ found \in BOOLEAN

Next ==
  UNCHANGED <<result, found>>

NotFound ==
  ~found
======================
```

When checking the invariant `NotFound` of the spec `Verifier`, we can have two possible outcomes:

 1. There is a counterexample. We compare the value of `result` to `witness`. They should match. If they don't, there is a bug in one of the encodings.
 1. There is no counterexample. There is a bug in one of the encodings.

Obviously, there is no need to go through the whole Apalache pipeline. We can simply generate expressions with `IrGenerators` and call the model checker, as it is done in [BoundedCheckerPassImpl.scala](https://github.com/informalsystems/apalache/blob/a535522b39fe1e3d5815e7a4422a400fc48d5b51/tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/passes/BoundedCheckerPassImpl.scala).

Since `IrGenerators` may generate ill-typed expressions, we have to resolve #1379 first.

We can use the same approach to compare Apalache against TLC, though it will require a bit more boilerplate.

- [x] #1632
- [x] #1638
- [x] #1639
- [x] #1666
- [ ] #1667

**Comment by rodrigo7491** [comment]
For context on the elusive bug mentioned see #1589.

@konnov, it is not stated anywhere, but `Oracle` and `Verifier` would be checked on alternating encodings, right?

**Comment by konnov** [comment]
Yes, `Oracle` and `Verifier` should be checked on the alternative encodings. Though we could also check the encoding against itself, to check its correctness. Also, we could swap `Oracle` and `Verifier` to check the both directions.

I talked to @thpani. He would like to pick this work.
