### ISSUE TITLE
[FEATURE] Package apalache for popular systems

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#159]
Packaged tools have a lower barrier to entry than tools that must be checked out and built from source or used via Docker. As an added bonus, being listed in package repositories can improve discoverability.

Of course, this doesn't come for free, as we'd also then be obligated to maintain the packaging, to ensure users didn't have bad experiences. But at some point this will be worthwhile and desirable.

We'd probably want packages for, at least,

- MacOS via homebrew
- Ubuntu/Debian via apt

We might also consider a nix package, as this could be very valuable for development, and provides a cross platform packaging option.

**Comment by lemmy** [comment]
Apalache would get this for free if it were to be *packaged* with the Toolbox. @konnov and I already discussed a Toolbox *integration* and *packaging* would be a good first step.  The most difficult part is probably how to package z3.

**Comment by konnov** [comment]
Yeah, z3 is our most useful, though most annoying, dependency here :-)

**Comment by lemmy** [comment]
Homebrew has a [formula for z3 4.8.8](https://github.com/Homebrew/homebrew-core/blob/master/Formula/z3.rb) and Debian/Ubuntu have [z3 4.8.7 packages](https://packages.ubuntu.com/search?keywords=z3&searchon=names&suite=focal&section=all).  Both systems support optional/recommended dependencies.

**Comment by shonfeder** [comment]
Yes, in general I was thinking that it would be nice if we could use an existing installation of z3 instead of having to build it from source. But I don't know yet whether we use features tied to a specific featureset or build that makes it infeasible to use a minimum system version.

**Comment by lemmy** [comment]
FWIW, grabbing a [release](https://github.com/informalsystems/apalache/releases), extracting it to e.g. `/opt`, followed by `apt-get install libz3-java` works fine, provided `-Djava.library.path=/usr/lib/x86_64-linux-gnu/jni/` is `bin/apalache-mc`.

**Comment by shonfeder** [comment]
As we discussed internally today, installing libz3-java should be necessary since #219.

**Comment by shonfeder** [comment]
Closing in favor of the smaller issues.
