### ISSUE TITLE
[FEATURE] Explain the errors found during type inference

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#161]
In the new type inferer

**Comment by konnov** [comment]
As we discussed, this most likely requires an incremental approach to type inference.

**Comment by shonfeder** [comment]
Would this include showing the name of the operator which is failing to check? Currently a failing type

**Comment by shonfeder** [comment]
Closed by accident.

**Comment by Kukovec** [comment]
Closed, for the same reason as #93
