### ISSUE TITLE
'version' is not listed in 'apalache-mc --help', and standard way to obtain the version is 'foo --version', not 'foo version'

### ISSUE THREAD

**Issue by p-offtermatt** [informalsystems/apalache#1611]
The output of 'apalache-mc --help' does not list the 'version' command.

In addition, the command for obtaining the version as 'apalache-mc version' is non-standard.
The standard way to obtain the version appears to be as in 'apalache-mc --version', see e.g. 'grep --version', 'ls --version', 'java --version'

**Comment by thpani** [comment]
Yeah, we had a bunch of problems with that lately, including #1497.
Maybe we need to move on to another argument parser?

**Comment by thpani** [comment]
Since this and related issues keep coming up, I did some investigation and filed a summary issue to track this: #1624.
