### ISSUE TITLE
TlaConstInliner ignores ASSUME

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1623]
`TlaConstInliner` is skipping assumptions and thus produces a malformed spec, if it refers to a constant in `ASSUME`.

For example:

```tla
------------------ MODULE TestInlineConst ---------------------------            
EXTENDS Integers

CONSTANT
    \* @type: Int;
    N

ASSUME (N \in Nat)

VARIABLE
    \* @type: Int;
    x

Init ==
    x = N

Next ==
    \/ x > 0 /\ x' = x - 1
    \/ x = 0 /\ UNCHANGED x

Inv ==
    x >= 0
=====================================================================
```

Here is a configuration file `TestInlineConst.cfg`:

```
INIT                                                                             
Init
NEXT
Next
CONSTANTS
N = 4
```

Run Apalache as follows:

```sh
apalache-mc check --inv=Inv --write-intermediate=1 TestInlineConst.tla
...
TestInlineConst.tla:8:9-8:9: unexpected expression: undeclared operator N E@09:06:00.826
Unexpected expressions in the specification (see the error messages) E@09:06:00.826
...
EXITCODE: ERROR (255)
```

This example stems from a real specification. It should be easy to fix. @Kukovec do you like to prioritize it?

**Comment by Kukovec** [comment]
Ok, so what happens is that, when loading from `.cfg`, `ConfigurationPassImpl` will define a `TlaOperDecl(OVERRIDE_N,List(),4)`, but `TlaConstInliner` looks for `ConstInit` when building its map. This _is_ easily fixable, but we could also use this nice opportunity to drop TLC `.cfg`.

**Comment by konnov** [comment]
Ah, nice. So this is an interaction between two instantiation mechanisms. I would prefer to keep the support for TLC configuration files, as we are still getting them in the user reports.

**Comment by konnov** [comment]
Cool! I have tried the fix in the original spec, and it works nicely :)
