### ISSUE TITLE
[BUG] CI is not running on PRs or the unstable branch

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#165]
I see that we purposefully stopped running on PRs in 7cae97cae5cfe9cecfb97e48504375a5bf7f7a4b, but in 118e55e2c891781eadc9c3c36dbd9f38c45a2de5 we added `unstable`, and I'm not sure why that's not building.

I also suggest we begin running CI on all PRs, and requiring they pass before merging. If there are good reasons we're not doing that now, let's document them, so we can fix those blockers and get the CI in a good state.

**Comment by konnov** [comment]
True. We never built PRs. Let's do that!

**Comment by konnov** [comment]
I have enabled all branches in `.travis.yml` on `unstable`. There is no good reason to exclude all branches. Back then, we had too much unstable code.

**Comment by shonfeder** [comment]
We doubled up on work: #167

**Comment by shonfeder** [comment]
Fixed in d0846f9bfb03bd9c7a960b6f72664da1206ff57c
