### ISSUE TITLE
CLI option to ignore local cfg file

### ISSUE THREAD

**Issue by heidihoward** [informalsystems/apalache#1673]
**Is your feature request related to a problem? Please describe.**
I am unable to tell Apalache to ignore a local TLC config file with the name ```<file>.cfg```. The cfg file is there because I with to support both TLC and Apalache.

**Describe the solution you'd like**
A command line flag or similar to tell Apalache not to look for a cfg file

**Describe alternatives you've considered**
Changing the name of the cfg file and using ```-config``` to change the location that TLC uses but this requires modification to the existing workflow for TLC

**Additional context**
Not an important feature but would be nice to have

**Comment by konnov** [comment]
In retrospective, I would also prefer not to load the TLC config by default. But we don't know how many people are using this feature. An easy fix would be to interpret `--config=-` as a request to ignore the config file.

**Comment by heidihoward** [comment]
Agreed, this has caused me confusion before. However, ```-config=- ``` would work for my use case.

**Comment by konnov** [comment]
After all, we have decided not to load a TLC configuration file by default. This new behavior does not seem to break our internal workflows, but it may break somebody else's workflows. Most likely, it will be released in the next version 0.25.0 on Monday.
