### ISSUE TITLE
[FEATURE] Make unstable the default branch

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#169]
IMO the default branch should the one under active development, since the main function of having a default branch is to obviate a lot of meaningless choices in order to optimize for development: e.g., picking which branch to make PRs into, picking which branch to checkout, etc.

Alternative, we could just switch to developing on master (using the trunk based development model) and just used tagged releases, cutting off a specific release branch if/when we ever need long term support for backwards compatibility.

But either way, IMO the default branch of the repo should be optimized for development, not for stable releases: we can use docker, tags, and documentation to guide users to the table sources.

**Comment by konnov** [comment]
Hmm. Let me see how to do that.

**Comment by konnov** [comment]
Fixed. Now all PRs are rebased against unstable.

**Comment by shonfeder** [comment]
Awesome. Thanks!
