### ISSUE TITLE
Update Z3 version to 4.8.15

### ISSUE THREAD

**Issue by rodrigo7491** [informalsystems/apalache#1702]
Z3 4.8.14 has a bug in the handling of arrays whose domain and range are of sort Bool, which seems to be the cause of #1660. This was fixed in 4.8.15.

**Comment by shonfeder** [comment]
Requested a new release here: https://github.com/tudo-aqua/z3-turnkey/issues/13

To give ourselves more flexibility, I think we could explore vendoring  the package.
