### ISSUE TITLE
Notifications in .travis.yml

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#171]
The notifications section in `.travis.yml` points to an old email alias at `forsyte.at`, which is still working, but we cannot add new people. What is the best approach there?

**Comment by shonfeder** [comment]
Do we need email notifications?

**Comment by shonfeder** [comment]
Also, was thinking that if we'd like to implement automated via releases via github actions, we might also what to consider moving the CI to github actions. In that case, I think the PR author gets notified based on their notification settings.

**Comment by konnov** [comment]
> Also, was thinking that if we'd like to implement automated via releases via github actions, we might also what to consider moving the CI to github actions. In that case, I think the PR author gets notified based on their notification settings.

Sounds cool 👍

**Comment by lemmy** [comment]
Since I spent (wasted) a lot of time massaging yaml, you might want to reuser parts of what has been done for [TLAPM](https://github.com/tlaplus/tlapm/tree/master/.github/workflows) and [TLC/Toolbox](https://github.com/tlaplus/tlaplus/blob/master/.github/workflows/main.yml).

**Comment by shonfeder** [comment]
Thanks, @lemmy I will do. I'm sorry for your loss, but grateful for my future savings :)
