### ISSUE TITLE
Remove SetInclusionRule and SetInclusionRuleWithArrays

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1710]
Since `S \subseteq T` is rewritten by the Keramelizer in #1621, we can safely remove the two rewriting rules, which are now redundant. We also have to remove `\subseteq` as an acceptable operator in `KeraLanguagePred`.

@rodrigo7491 what do you think about that?
@thpani in case you have free refactoring cycles.

**Comment by rodrigo7491** [comment]
If the rules cannot be reached anymore, might as well remove them. I imagine this will not have a negative impact on solving performance.

**Comment by thpani** [comment]
We're using `\subseteq` in `SetInRule` and `CherryPick`.
@konnov should they use the same rewriting as in Keramelizer then?
