### ISSUE TITLE
CI isn't using cached builds of Z3

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#174]
Towards #172 

Not sure what's causing this exactly, as I'm still getting up to speed on our build and CI setup, but so far every build I've seen seems to building z3 fresh. Ensuring that we use the prebuilt binaries when possible should help shave a lot of time off the builds.

**Comment by shonfeder** [comment]
As an example: https://travis-ci.org/github/informalsystems/apalache/builds/707751029#L274

**Comment by konnov** [comment]
z3 builds were cached for sure before the move to informalsystems. I guess, the caching settings have been reset.

**Comment by konnov** [comment]
Oh, the PRs are going to build z3 from scratch. That is annoying. Maybe that should motivate us to publish z3 as a maven artifact.

**Comment by konnov** [comment]
Apparently, there is a new project: https://github.com/tudo-aqua/z3-turnkey

**Comment by shonfeder** [comment]
This should be closed by #219 

(lol, I missed your pointer to z3-turnkey all those months ago, @konnov! Too bad! it would have saved a bunch of time :|)
