### ISSUE TITLE
Run CI tests without `APALACHE_FATAL_WARNINGS`

### ISSUE THREAD

**Issue by thpani** [informalsystems/apalache#1741]
We're currently running unit and integration tests in CI with `APALACHE_FATAL_WARNINGS` set.

This sometimes makes all test jobs fail early, e.g, due to wrong formatting or compiler warnings, but not because the actual tests are broken. See for example: https://github.com/informalsystems/apalache/runs/6389502799?check_suite_focus=true

Ideally, we'd be alerted of both formatting errors *and* failing test on the first CI run.
Otherwise, especially with integration tests, there's considerable round-trip time for a second CI run.

I wonder if we should split off a separate build job to be run with `APALACHE_FATAL_WARNINGS` and disable it on unit/integration test jobs. @shonfeder WDYT?

**Comment by shonfeder** [comment]
Great idea.
