### ISSUE TITLE
Remove `recFunDef` and `recFunRef

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#1786]
Since recursive functions aren't supported any longer, we should clean up old unused code.

**Comment by konnov** [comment]
Wait, we are still supporting them in the type checker

**Comment by Kukovec** [comment]
For whom?

**Comment by konnov** [comment]
For people typechecking their specs without model checking them.

**Comment by Kukovec** [comment]
You don't need `recFun(Def|Ref)` for typechecking. Recall that they were introduced for model-checking (cell resolution).

**Comment by konnov** [comment]
I think they are produced by `SanyImporter`. If we removed them, we would not be able to even import specifications that are using recursive functions.

**Comment by Kukovec** [comment]
Yes, why wouldn't it be, nothing has changed?

**Comment by konnov** [comment]
I am going through the backlog to figure out where to put issues and whether some of them are actually closed.

**Comment by konnov** [comment]
I think `recFunDef` and `recFunRef` are produced by the SanyImporter:

https://github.com/informalsystems/apalache/blob/2ce9652f49b087db418fdce7177733fb4b30c36f/tla-io/src/main/scala/at/forsyte/apalache/tla/imp/OpApplTranslator.scala#L334-L342

So we still need them, as long as we want them supported by the type checker.
