### ISSUE TITLE
Providing multiple invariants on the command line

### ISSUE THREAD

**Issue by p-offtermatt** [informalsystems/apalache#1828]
**Is your feature request related to a problem? Please describe.**
Multiple invariants can be specified by using a conjunction, e.g.

```
BalanceIsNotNegative = ...
TokensDontDisappear = ...

Invariant = 
 /\ BalanceIsNotNegative 
 /\ TokensDontDisappear 
```

This has disadvantages:
* When `Invariant` is found to be violated, it's not immediately clear *which* invariant doesn't hold
* It's weird to have to adjust the Spec, i.e. alter the big invariant conjunction to check a different set of invariants

**Describe the solution you'd like**

The `--inv` flag can be specified multiple times, and an error is reported when any given invariant is violated.

**Describe alternatives you've considered**

Via providing a .cfg file, it's already possible to have multiple invariants, but the CLI rather than the config file should be the default way to interact with Apalache.

Instead of multiple `--inv` flags, different invariants could be separated by commas or semicolons; this seems to be mostly a matter of taste.

**Comment by shonfeder** [comment]
This was closed by #2074
