### ISSUE TITLE
Change the syntax for type aliases

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1843]
Our type checker uses the same syntax for type aliases and uninterpreted types, e.g., `PROC_SET`. It often leads to confusion, especially, when the users make a typo in the alias name.

We should introduce different syntax for uninterpreted types and type aliases. For instance, uninterpreted types should be in upper case, whereas type aliases should be in camel case.

**Comment by Kukovec** [comment]
Is `T` an uniterpreted type or an alias?

**Comment by Kukovec** [comment]
Consider that camel case might be hard to regex though.

**Comment by konnov** [comment]
Yes, lower case is also an option, though we have to be careful that they do not clash with type variables.
