### ISSUE TITLE
Make it possible to evaluate expressions over (ITF) traces

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#1845]
Often, it is difficult for humans to _evaluate_ or _inspect_ a counterexample and mine it for information. 
This is mainly due to the fact that invariants, for which counterexamples are found, are often sizeable and made up of numerous sub-components, or the states themselves contain a large number of variables.

We propose the following feature: Given an ITF trace and a collection of labeled (named) state-level TLA expressions , have Apalache output a mapping over the trace, where the expressions are evaluated at each state.

Example:
Assume a specification over two `Int` variables, `x,y` and an invariant `x < 10 /\ y < 10` produced a trace 
```
(x=1,y=2) -> (2,2) -> (4,2) -> (4,6) -> (10, 6)
Invariant violation: x >= 10 \/ y >= 10 
```
If we want to evaluate the expressions `A: x + y`, `B: x > y` and `C: y < 10` over the trace, we should see:
```
(A: 3, B: FALSE, C: TRUE) -> (4, FALSE, TRUE) -> (6, TRUE, TRUE) -> (10, FALSE, TRUE) -> (16, TRUE, TRUE)
```
or 
```
A: 3 -> 4 -> 6 -> 10 -> 16
B: ...
C: ...
```

**Comment by Kukovec** [comment]
@konnov @shonfeder @thpani @bugarela thoughts?

**Comment by konnov** [comment]
As an idea: This also has flavor of runtime monitoring.

**Comment by konnov** [comment]
adding @tesnimab to follow up on the discussion of input/output

**Comment by konnov** [comment]
Currently, this issue in the bugfixing milestone. If it's more than a week of work, we should probably make a separate milestone for it. @Kukovec what do you think?

**Comment by shonfeder** [comment]
Done! :tada:
