### ISSUE TITLE
Implement Python client library for Shai

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#1866]
We can use this for integration tests, and it will help make the server immediately available for use by MBT.

Discussed with Igor yesterday.

I'll fill this issue out as we go, and probably eventually break it into its own milestone.

I'll aim to also get PR reviews and input from MBT team.

Work is tracked in the [Chai milestone](https://github.com/informalsystems/apalache-chai/milestone/1).

**Comment by shonfeder** [comment]
I think this should probably be developed in a separate repo, as it will be a python package, and we have currently opted to follow a poly-repo approach with all other related projects.

I propose calling the client "Chai":tea: for "Client for Human-Apalache Interaction".

WDYT: @rnbguy and @thpani?

**Comment by thpani** [comment]
Separate repo SGTM, and I love the name! 🍵

**Comment by rnbguy** [comment]
I am also in favor of a separate repo. The name is cool :smile:

**Comment by shonfeder** [comment]
So this issue will remain open, to track the dependency on the work on Chai, but the tracking for on the client library will proceed in https://github.com/informalsystems/apalache-chai/milestone/1

**Comment by shonfeder** [comment]
This is done.
