### ISSUE TITLE
[FEATURE] Temporary solution for TLA_PATH

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#187]
We need a way to lookup for modules in the directories different from the working directory. [This PR](https://github.com/tlaplus/tlaplus/pull/493) solves the issue. However, it will take some time before the PR gets merged, tla2tools get released, etc.

To go ahead with #162, #181, #183, we will handle `TLA_PATH` right in `apalache-mc` by calling java with `-DTLA-Library=$TLA_PATH`. Once the PR is released, we will remove this kludge.

**Comment by konnov** [comment]
Followed up the lookup path in the branch https://github.com/informalsystems/apalache/tree/ik/standard-modules, to be a PR for several issues.

**Comment by konnov** [comment]
This is addressed in the PR #188

**Comment by lemmy** [comment]
It would be convenient if TLA_PATH would work with [CommunityModules.jar](https://modules.tlapl.us/).
