### ISSUE TITLE
[FEATURE] TLA_PATH when running the docker image?

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#189]
In #187, we introduced TLA_PATH that allows apalache to look for modules in the user-defined directories. However, TLA_PATH will not propagate when apalache runs in docker. Any ideas how to solve that?

**Comment by shonfeder** [comment]
I'll investigate this tomorrow, but just to sanity check, have you already been trying to run the docker container with `-e TLA_PATH` (as per https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file)?

**Comment by konnov** [comment]
Not yet. I am just worried now that the command-line will be quite long. We should think of introducing a script for running apalache in docker.

**Comment by shonfeder** [comment]
I've confirmed that, with the fix in #194 in place, the `TLA_PATH` propagates through using, e.g.:

```
TLA_PATH=./tla docker run -e TLA_PATH --rm -v $(pwd):/var/apalache apalache/mc:staged parse tla/y2k_override.tla
```

(Or, obviously, `TLA_PATH` could have been exported into the environment.)

A script to wrap this should be easy, but I'm wondering how we want to treat cases where people have directories on their `TLA_PATH` that aren't under the current working directory. E.g., suppose we have `TLA_PATH=/usr/opt/tla_libs` but the user runs the docker container from their home directory. `/user/opt/tla_libs` will be in the path, but it won't actually be available in the docker container.

Should we have the script ensure all directories in the `TLA_PATH` are mounted? Or does this seem like too surprising behavior from a user perspective?

**Comment by shonfeder** [comment]
I think if we add all directories in the TLA_PATH via [read only bind mounts](https://docs.docker.com/storage/bind-mounts/#use-a-read-only-bind-mount) that it shouldn't introduce any strange behavior. I'll proceed with that, unless I hear any objections.

**Comment by konnov** [comment]
Yes, read-only mounts should suffice. On second thought, I would be worried, if the tool mounted arbitrary paths to a docker container. I am not sure about how to make a compromise between verbosity and transparency :-)

**Comment by konnov** [comment]
How about having a script that does all the docker magic and has a flag like `--mount-tla-path`. The user will give the script permission to mount everything in `TLA_PATH`, and the script will do the hard work of mounting a list of directories.

The most interesting question is what language should we choose for scripting. Currently, Linux, MacOS, and Windows users can run apalache in docker.

**Comment by shonfeder** [comment]
That sounds good to me.

I know very little about supporting Windows. But it seems like Python scripts can be made sufficiently portable. Does that seem ok?

**Comment by shonfeder** [comment]
Now that we have the portable JAR, and are gearing up to work on packaging, I don't think we really have a need for this. If someone wants to do "advanced" stuff like include tla files not in their working directory, and they want to use docker, I think they can wire together the bind volumes themselves. I'd rather not invest in docker-as-a-delivery platform anymore than we need to.

**Comment by konnov** [comment]
yes, this looks like an outdated feature
