### ISSUE TITLE
No need for assignments when using Assert(FALSE, ...)

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#19]
There is a widely-used idiom in TLC that allows one to write tests like follows:

```tla
     \/ /\ Print("Starting Test 2", TRUE)
        /\ IF x' = 2 
             THEN y' = 1 
             ELSE Assert(FALSE, "Failed Test 2")
```

The assignment solver fails to find an assignment for the ELSE branch. One should treat `Assert(FALSE, ...)` as FALSE. The other kinds of assertions should not be affected.

**Comment by konnov** [comment]
Moved it to backlog, as it is still not clear how to interpret assert with SMT constraints

**Comment by Kukovec** [comment]
The new (#366) approach to assignment finding allows us to treat ASSERT as desired w.r.t. assignments quite easily. As to what to do with it, down the line, I think we need to discuss assertions some more.

**Comment by Kukovec** [comment]
Closing this, it seems clear, at this point, that we have no plans for supporting `Assert` in Apalache in the future.
