### ISSUE TITLE
Add Test command

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/apalache#191]
Besides the currently present `check` and `parse` commands it probably makes sense to add the `test` command. This command will be targeted at:

* quickly test the current model, and produce model instances for small scopes
* produce executions to be further used in generating model-based tests

Compared to the `check` command, which is optimized for finding proofs, the `test` command would be optimized for quickly finding model instances.

From the UI point of view, the user will specify not an invariant to check, but a model instance to generate. Technically it's a trivial transformation, i.e. in the first implementation to generate an instance `Instance` we will look for a violation of the invariant `~Instance`. But for the end user it's much simpler to think in positive terms, to describe the properties of the desired instance, and we should not force the user to apply negation to get an invariant out of it.

Besides, having the separate `test` command will open a road for introducing specialized instance/bug-finding optimizations: it's well known that a model instance can be found much faster than a proof can be produced.

For the end user we would then propose the following workflow, similar to the one used in Alloy:
1. develop a draft model
2. test the model quickly, examine the generated instances, and gain confidence in the model correctness
3. check the model exhaustively to get the proof (up to some depth)

**Comment by konnov** [comment]
Knowing a bit of Alloy, I kind of see what you mean. I agree it's an excellent idea. But let's try to clarify it a bit. Suppose you have the following (rather trivial) specification:

```tla
VARIABLE S
Init == S = {}
Next == \E x \in 1..10: S' = S \union {x} \/ S' = S \ {x}
```

Do you like to produce instances for `Init` and `Next` (just one step)?

Technically, there is one issue with that. Our translator to SMT dynamically computes overapproximations of all data structures (set, sequences, functions, etc.). So the user will have to give upper bounds on all CONSTANTS and VARIABLES. I guess, this is what Alloy does as well, so it will not be at all surprising. We could use a predicate similar to `TypeOK` to restrict the contents of all constants and variables. It looks like Hillel Wayne is [missing exactly this feature](https://www.reddit.com/r/tlaplus/comments/huhpsy/pltalk_practical_formal_methods_with_hillel_wayne/).

**Comment by konnov** [comment]
I am not sure I understand Point 3. Is not it exactly bounded model checking?

**Comment by andrey-kuprianov** [comment]
yes, point 3 is of course exactly bounded model checking :) It's just that the model checking, being rather heavy in execution, should be used from my point of view only at the end of the development iteration. The dream is of course to make the `test` command so fast that it could be integrated directly into an IDE, i.e. give the user a feedback (a model instance) within seconds. And actually TLC behaves quite well in that respect, much better than Apalache at least for small models, so we probably want a specialized version of "Apalache for tests" that will be targeted towards instance-generation.

As for you previous point, the user would need to describe exactly what he wants to get as an instance. In that case it would be smth. like "give me any instance with the first step satisfying `Init`, and each step satisfying `Next` for 5 steps".

In the first iteration it will be nothing more than BMC checking of an invariant. In the next iteration I suppose we will invent some convenient shortcuts allowing the user to concisely specify the desired instance shape.

**Comment by konnov** [comment]
Apalache is kind of tuned for instance generation already. Did you try the version with `--all-enabled` in ik/multicore? It does not check, whether transitions are enabled, so it is pure instance generation.

**Comment by konnov** [comment]
I mean, if everything you want is Init + 5 steps, it is already there. With `--all-enabled`, it should be also fast. However, I think Alloy does a bit more than that by allowing the user to set bounds on the size of the model. This is quite interesting, one can see the result of applying a single TLA+ action,

**Comment by andrey-kuprianov** [comment]
No, not tried yet, I will do. But as far as I can see, it doesn't include the latest JSON output changes, and I need them...

But besides not checking for transition enabledness, there are a lot of other heuristics we can implement, a la guided search, or even causality... ;)

**Comment by konnov** [comment]
you are free to merge unstable to ik/multicore

**Comment by andrey-kuprianov** [comment]
`ik` feels like a "owned-by" tag; isn't it that we are not supposed to merge into each other branches? A quick try revealed quite a lot of conflicts, as your structure there is quite different from what we have in `unstable`. I think for the time being I am fine with the `unstable` version, and will wait till you merge `ik/multicore` there

**Comment by andrey-kuprianov** [comment]
> I think Alloy does a bit more than that by allowing the user to set bounds on the size of the model. This is quite interesting, one can see the result of applying a single TLA+ action.

yes, I also have in mind exactly something like that :)

**Comment by konnov** [comment]
This symbolic execution is related to #445, which we should be able to implement in February. The Alloy-like behavior is very desirable, but that needs a redesign of the encoding. This is what we will do, but maybe in 2-3 months.

**Comment by konnov** [comment]
@andrey-kuprianov how far is #717 from what you liked to have?

**Comment by konnov** [comment]
The `test` command is there. We just have to update the documentation as scheduled in #1135
