### ISSUE TITLE
Add package javadoc for `at.forsyte.apalache.tla.typecomp`

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1912]
This package has a very minimal documentation. Given that it will be used everywhere in the project, we have to invest some effort in the dev's documentation.

**Comment by konnov** [comment]
Also #646 is related

**Comment by Kukovec** [comment]
Are you sure you want more documentation on `typecomp`? Every method as well as the package here has documentation, so I'd be interested to know what information you think is missing. 
I could maybe see elaborating in `types`, which is where the convenience builder instance is defined, and is the package people actually need to import to use the builder.

**Comment by Kukovec** [comment]
> When I looked at `ScopedBuilder`, the class itself is documented, but its methods are not.

That's just not true, literally every method has a doc.

**Comment by konnov** [comment]
Now I see. Interesting. For some reason, Scaladoc does not expand one-line comments by default. It would help, if you added a sentence like: `Builds a TLA+ expression: {{{args_0 /\ ... /\ args_n}}}`.

**Comment by Kukovec** [comment]
I think it's clearly implied that `ScopedBuilder`, which is documented with "Builder for TLA+ (TNT) IR expressions." has methods that build TLA+ expressions.

**Comment by konnov** [comment]
Could you maybe add a package-level documentation that points to `ScopedBuilder`? I can make a pass over the builder methods then.

**Comment by Kukovec** [comment]
I plan on adding a HOWTO for adding methods to ScopedBuilder and a HOWTO for using the builder to `typecmp` (the package)

**Comment by konnov** [comment]
Do you mean a HOWTO as Scaladoc, or HOWTO as in the manual?

**Comment by Kukovec** [comment]
The former.
