### ISSUE TITLE
Implement TypedBuilder for ApalacheInternalOper

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1916]
In the context of #1655. When it's done, fix three TODOs in `at.forsyte.apalache.tla.bmcmt.rules.aux.ValueGenerator`.

**Comment by konnov** [comment]
cc @Kukovec

**Comment by Kukovec** [comment]
Those will be addressed when we start using the builder, IDK why Igor brought up those TODOs in an issue about builder features.

**Comment by konnov** [comment]
I tried to use the builder yesterday, with partial success. The TODOs refer to the points, where the API was insufficient.

**Comment by Kukovec** [comment]
Yes, but the sub issues of #1655 were previously all about builder _features_, and this one includes a bit about builder _usage_ for some reason.

**Comment by konnov** [comment]
Well, you asked me to use the new builder in on of my PRs. It did not work as expected, so I left a bit of work for you :)

**Comment by Kukovec** [comment]
That's not the point. The point is that "Implement TypedBuilder for ApalacheInternalOper" and "fix three TODOs in at.forsyte.apalache.tla.bmcmt.rules.aux.ValueGenerator." should have been 2 separate issues.

**Comment by konnov** [comment]
Good point! Feel free to separate them.

**Comment by Kukovec** [comment]
Closed by #1924
