### ISSUE TITLE
Protect against Sany's lack of thread safety by ensuring any access to Sany is synchronized

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#1963]
See @thpani's suggestion at https://github.com/informalsystems/apalache/pull/1855#discussion_r918669410

This is to address the problem identified at https://github.com/informalsystems/apalache/issues/1114#issuecomment-1180534894

Note that this probably is not the only thread-unsafe chunk of code in Apalache (the singleton object used for the output manager comes to mind, and we also have #1872), so this could open a bigger can of worms.

**Comment by konnov** [comment]
@shonfeder, is it a stale issue. I thought, it was resolved

**Comment by thpani** [comment]
@konnov Currently, we're only synchronizing on code paths through Shai, not inside Apalache itself.

**Comment by shonfeder** [comment]
Yep. This is still relevant. In fact, I only realized yesterday how relevant: since pretty much all our pass chains call the parser, and there’s currently no way of factoring parts of passes chains, the parser’s lack of thread safety pollutes every pass chain, making them all thread unsafe.

**Comment by shonfeder** [comment]
These are the options of which I'm currently aware:

- Wrap all calls to SANY in some sort of mutex to ensure it never runs concurrently.
- Push for an upstream fix to make SANY thread safe.
- Remove the dependency on sany.

**Comment by thpani** [comment]
IIRC an upstream fix would require to change the way SANY uses JavaCC (which was set up with globally mutable parser state). If this is impacting us now, I think a mutex is a reasonable short-term fix, while we push for an upstream fix in the long term?
