### ISSUE TITLE
Update `ScopedBuilder` testing framework to test for (well-typed) malformed expressions

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#1965]
`BuilderTest` offers testing templates, which accept a sequence constructor for a sequence of ill-typed expressions (`mkIllTyped`), then check that attempting to build any of them causes a `TBuilderTypeException`.
The templates should also take sequence constructors for expressions that trigger `TBuilderScopeException`s (shadowing) or `IllegalArgumentException` (`require` checks) in the same fashion.

**Comment by shonfeder** [comment]
Removing this from the typed builder milestone, as that stone has been well set :tada:

we can always pick this up as a subsequent minor improvement. Tho I'd be probably be in favor of closing it in preference for #2580.

**Comment by Kukovec** [comment]
This has been implemented at some point (see e.g. `BuilderTest::assertThrowsBoundVarIntroduction-` methods), but since most methods don't have the potential to cause shadowing, having a separate test to call should suffice, and there's no need to make this part of `run-` methods.
