### ISSUE TITLE
Model Checking Tutorial should include a zip of all files

### ISSUE THREAD

**Issue by hwayne** [informalsystems/apalache#1996]
For https://apalache.informal.systems/docs/tutorials/entry-tutorial.html

There's 11 versions of `BinSearch` and 9 versions of `MC_8`, plus patch diffs. If the user could download all of the files at once it would be easier to follow the tutorial.

**Comment by konnov** [comment]
> Perhaps we should do it for all the tutorials?

We should definitely do this.

> ...we could facilitate [download-directory/download-directory.github.io](https://github.com/download-directory/download-directory.github.io) for this.

Yes! I did not know it even existed :)
