### ISSUE TITLE
Performance regression outputting an example trace

### ISSUE THREAD

**Issue by thpani** [informalsystems/apalache#2039]
We added default output of an example trace in #1838. It is implemented by the call to `trex.sat()` below.

https://github.com/informalsystems/apalache/blob/eb92cc88883ca2134c06ba6ab644b8d60585d4bf/tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SeqModelChecker.scala#L95

This may cause a significant performance regression, as witnessed by #2019, where producing the example trace takes one hour.

In addition, when Apalache is run with `--discard-disabled`, it might overshoot the actually feasible trace length. This essentially causes an unsat query in the `trex.sat()` call that takes substantial time. Also, the reason for the delayed behavior is not obvious from the tool output:

```
$ apalache-mc check --features=rows --length=9 --inv=Mutex --discard-disabled=false --no-deadlock --tuning-options='search.transitionFilter=(0->.*|[1-6]->.*|7->3|[8-9]->.*|[1-9][0-9]+->.*)' test/tla/MC_LamportMutexTyped.tla
...
13:12:43.344 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #9, transition #5
13:12:43.345 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT...
13:12:43.442 [main] INFO  a.f.a.t.b.t.TransitionExecutorImpl - Step 9: picking a transition out of 6 transition(s)
<<note the delay here>>
13:16:34.672 [main] INFO  a.f.a.t.b.p.BoundedCheckerPassImpl - The outcome is: NoError
13:16:34.672 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #13: BoundedChecker [OK]
```

**Comment by shonfeder** [comment]
> producing the example trace takes one hour.

Oh man! One of those performance regressions that is obvious in retrospect, lol! :rofl: 

Seems like this at least indicates that we should provide a flag to *disable* this behavior? Do you agree?

Do you think we could use a heuristic to determine when it would be cheap enough to generate a trace by default? Like, if we have some metric we can get in constant time for the size of the trace, perhaps we could *not* generate the trace if it's over some size?

**Comment by thpani** [comment]
> Seems like this at least indicates that we should provide a flag to _disable_ this behavior? Do you agree?

Yeah, I think we need a flag, at least until we have a smarter solution.
Not sure if it should be default on or off – we can discuss on Monday
