### ISSUE TITLE
[FEATURE] Develop a web-based sandbox/IDE

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#207]
This was suggested by @ebuchman.

This issue would probably involve a separate project that leveraged Apalache, but this seems to be a good place to the track the idea for the issue, just to get started.

Some eventual features might include:

- In browser IDE support (at least basic linting and syntax highlighting)
- Basic file management
- Running checks on our backend server
- Export/import of `.tla` files
- Production of counter-examples

**Comment by lemmy** [comment]
This has already been build.  See screencast at http://tla.msr-inria.inria.fr/kuppe/TLAExamplesGitpod3cut.mp4 and https://github.com/lemmy/BlockingQueue/tree/apalache  for apalache specifically.  Works with gitpod (GCE), VSCode codespaces, and Github codespaces.

**Comment by shonfeder** [comment]
Nice! Then this may be closer to hand then initially thought. Perhaps we only need some documentation and accessible and visible on-ramp to get people taking advantage of these.

**Comment by lemmy** [comment]
Can apalache be installed from an apt repository?  If yes, the gitpod & vscode setup could be simplified by removing docker entirely.

**Comment by konnov** [comment]
We definitely should not duplicate work. As for apt, it looks like the [standard packages](https://packages.ubuntu.com/focal/z3) for z3 do not include java bindings.

**Comment by lemmy** [comment]
What about https://packages.ubuntu.com/focal/libz3-java ?

**Comment by konnov** [comment]
We should understand, whether we need two build environments instead of one. Our current build environment is tuned towards development. We cannot depend on the availability of z3 at the system level, as z3 had API incompatibilities in the past. However, if we like to maintain an apt package in Ubuntu, we have to deal with the system-level instance of z3.

**Comment by lemmy** [comment]
As an intermediate step for a web IDE, apalache.jar (without z3) could - like tla2tools.jar - be bundled with the VSCode extension and (implicitly) depend on the current z3 version available in Ubuntu 20.04.  The z3 version is fixed as per the Ubuntu package policy and we have two years to the next Ubuntu LTS, which Codespaces or Gitpod will eventually switch to.

**Comment by konnov** [comment]
Two years sounds like a lot to be stuck with the same version of z3... Not that we jump to the new versions all the time, but the new versions sometimes boost the tool's performance for free.

**Comment by lemmy** [comment]
You could deliberately decide to use an Unstable/PPA with a newer version of z3.  I'd just say that this is a decision to be made by whoever maintains the IDE and not the individual users.

**Comment by lemmy** [comment]
I've updated https://github.com/lemmy/BlockingQueue/tree/apalache to use the docker image `apalache/mc` on [Github Codespaces](https://github.com/features/codespaces).  If there is interest to try it out, please [request early access](https://github.com/features/codespaces) and get back to me (I should be able to fast-track your request).

**Comment by konnov** [comment]
Hi Markus! Yes, that sounds interesting. I have requested early access. If you could fast-track, that would be great.

**Comment by konnov** [comment]
Wow. That looks great! Thanks!

**Comment by lemmy** [comment]
A few issues that I've observed:

* Codespace suspends on inactivity despite Apalache running in the background
* Apalache docker image:
  * bash not default shell
  * Runs as root (cosmetic issue)

**Comment by shonfeder** [comment]
Between @lemmy's work on codespaces and the sandbox here https://github.com/informalsystems/apalache-sandbox, we effectively have this.

But we've de-prioritized expanding on it for the time being.
