### ISSUE TITLE
Regression: Checker reports no error up to computation length None

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#2087]
We don't have the following test:

```sh
$ apalache-mc check test/tla/y2k_instance.tla
...
Checker reports no error up to computation length 10
```

In `v0.28.0-15-g0c2f4eded`, it prints:

```sh
...
Checker reports no error up to computation length None
```

**Comment by thpani** [comment]
This was introduced in https://github.com/informalsystems/apalache/commit/720e3b75597b76b2536cd1e5a93995741d0969a2#diff-dc42a88d8e6c0f0411f8d16e261dcc88792debe82a9d04b0b0dd9a7082229773 when we turned all the clist `opt`s into `Option`s.

I don't think we generally print anything in the `Cmd`s, but may be worth a sanity check.

**Comment by thpani** [comment]
FYI @shonfeder, this indicates that we'd need access to the merged option groups of #2080 inside the clist `Cmd`s. Is that feasible?

**Comment by shonfeder** [comment]
Clist `Cmd`s should have access to the merged configs currently via https://github.com/informalsystems/apalache/blob/0c2f4eded0d85faf14165095a2a3dcc1b6d89b15/mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ApalacheCommand.scala#L131-L138

Tho as you noted in the meeting, perhaps this should be derived from the options? The options are currently available here via the `passOptions` map in the executor:

https://github.com/informalsystems/apalache/blob/0c2f4eded0d85faf14165095a2a3dcc1b6d89b15/mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala#L91-L113

**Comment by thpani** [comment]
Thanks @shonfeder, got it working! Will open a PR tomorrow.
