### ISSUE TITLE
Introduce the Options.tla module

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#2097]
@shonfeder has written a nice explanation of option types in the tlaplus group:

https://groups.google.com/g/tlaplus/c/XiiJ2zg_f3U/m/RJbHjVx1AQAJ

It probably makes sense to extract this example into a module called like `Options.tla`. This module could also introduce the default value for the `UNIT` type, which seems to be a common question too.

**Comment by shonfeder** [comment]
Thank you for creating the issue! I'd like to do this work, if there are no objections. It's a nice exercise to improve my TLA+ :)
