### ISSUE TITLE
[BUG] Building Apalache from source with Zulu JDK and Maven fails on MacOS

### ISSUE THREAD

**Issue by istoilkovska** [informalsystems/apalache#213]
**Describe the bug**
I tried to build Apalache 0.7.2 from sources on MacOS 10.15.5, using Zulu JDK8 and Apache Maven 3.6.3. Running `make` failed while testing `tla-assignments`, because the Z3 Java library cannot be loaded. I get the following exception:
```
java.lang.UnsatisfiedLinkError: no libz3java in java.library.path
```
although both `libz3.dylib` and `libz3java.dylib` are in `/path/to/apalache/3rdparty/lib`.

**To Reproduce**
 1. Install Zulu JDK8. Running `java -version` outputs:
```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (Zulu 8.48.0.53-CA-macosx) (build 1.8.0_265-b11)
OpenJDK 64-Bit Server VM (Zulu 8.48.0.53-CA-macosx) (build 25.265-b11, mixed mode)
```
 2. Install Apache Maven 3.6.3. Running `mvn -v` outputs:
```
Apache Maven 3.6.3 
Maven home: /opt/apache-maven-3.6.3
Java version: 1.8.0_265, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.5", arch: "x86_64", family: "mac"

```
 3. Running `make` in the `apalache` directory outputs:
```
...
[INFO] ----------------< at.forsyte.apalache:tla-assignments >-----------------
[INFO] Building tla-assignments 0.7.2-RELEASE                            [7/10]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ tla-assignments ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/ilina/apalache/tla-assignments/src/main/resources
[INFO] 
[INFO] --- scala-maven-plugin:4.4.0:add-source (scala-compile-first) @ tla-assignments ---
[INFO] Add Source directory: /Users/ilina/apalache/tla-assignments/src/main/scala
[INFO] Add Test Source directory: /Users/ilina/apalache/tla-assignments/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:4.4.0:compile (scala-compile-first) @ tla-assignments ---
[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiler bridge file: /Users/ilina/.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.12-1.3.5-bin_2.12.0__52.0-1.3.5_20200330T000931.jar
[INFO] Compiling 15 Scala sources to /Users/ilina/apalache/tla-assignments/target/classes ...
[INFO] Done compiling.
[INFO] compile in 8.5 s
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ tla-assignments ---
[INFO] Changes detected - recompiling the module!
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default) @ tla-assignments ---
[INFO] Changes detected - recompiling the module!
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ tla-assignments ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 31 resources
[INFO] 
[INFO] --- scala-maven-plugin:4.4.0:testCompile (scala-test-compile) @ tla-assignments ---
[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiler bridge file: /Users/ilina/.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.12-1.3.5-bin_2.12.0__52.0-1.3.5_20200330T000931.jar
[INFO] Compiling 4 Scala sources to /Users/ilina/apalache/tla-assignments/target/test-classes ...
[INFO] Done compiling.
[INFO] compile in 7.6 s
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ tla-assignments ---
[INFO] Changes detected - recompiling the module!
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ tla-assignments ---
[INFO] Surefire report directory: /Users/ilina/apalache/tla-assignments/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running at.forsyte.apalache.tla.assignments.TestAssignmentStrategyEncoder
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.549 sec
Running at.forsyte.apalache.tla.assignments.TestSymbTransPass
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.04 sec <<< FAILURE!
at.forsyte.apalache.tla.assignments.TestSymbTransPass  Time elapsed: 0.027 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: no libz3java in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
	at java.lang.Runtime.loadLibrary0(Runtime.java:872)
	at java.lang.System.loadLibrary(System.java:1124)
	at com.microsoft.z3.Native.<clinit>(Native.java:14)
	at com.microsoft.z3.Context.<init>(Context.java:41)
	at at.forsyte.apalache.tla.assignments.SMTInterface.apply(SMTInterface.scala:55)
	at at.forsyte.apalache.tla.assignments.TestSymbTransPass.$anonfun$new$2(TestSymbTransPass.scala:73)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
	at org.scalatest.FunSuite.run(FunSuite.scala:1560)
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:99)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running at.forsyte.apalache.tla.assignments.TestSymbTransGenerator
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.044 sec
Running at.forsyte.apalache.tla.assignments.TestAlphaTransform
Parsing file /Users/ilina/apalache/tla-assignments/src/test/resources/assignmentSolver/Paxos.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/Integers.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/Naturals.tla
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.348 sec

Results :

Tests in error: 
  at.forsyte.apalache.tla.assignments.TestSymbTransPass: no libz3java in java.library.path

Tests run: 22, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for APALACHE project 0.7.2-RELEASE:
[INFO] 
[INFO] APALACHE project ................................... SUCCESS [  0.993 s]
[INFO] tlair .............................................. SUCCESS [01:07 min]
[INFO] infra .............................................. SUCCESS [ 24.228 s]
[INFO] tla-import ......................................... SUCCESS [ 46.659 s]
[INFO] tla-pp ............................................. SUCCESS [ 54.156 s]
[INFO] tla-types .......................................... SUCCESS [ 29.994 s]
[INFO] tla-assignments .................................... FAILURE [ 17.611 s]
[INFO] tla-bmcmt .......................................... SKIPPED
[INFO] tool ............................................... SKIPPED
[INFO] apalache-pkg ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:01 min
[INFO] Finished at: 2020-09-08T14:24:04+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project tla-assignments: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/ilina/apalache/tla-assignments/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :tla-assignments
make: *** [apalache] Error 1
```

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.5
 - JDK version: OpenJDK Runtime Environment (Zulu 8.48.0.53-CA-macosx)
 - Version: 0.7.2

**Additional context**
I have tried several fixes, to no avail:
 - setting the environment variable `JAVA_LIBRARY_PATH` and `DYLD_LIBRARY_PATH` to `/path/to/apalache/3rdparty/lib`
 - running `java -Djava.library.path=/path/to/apalache/3rdparty/lib`  
 - passing `-DargLine='-Djava.library.path=/path/to/apalache/3rdparty/lib'` as an argument to the `mvn` command in the Makefile
 
Building Apalache with `make build-quick` succeeds. However, the error persists when running `apalache-mc check spec.tla`.

**Comment by shonfeder** [comment]
I can easily reproduce (thanks to the fantastic bug report). Strangely, if I look at `tla-assignments/target/surefire-reports/TEST-at.forsyte.apalache.tla.assignments.TestSymbTransPass.xml` the `java.library.path` **is** set. I see

```
    <property name="java.library.path" value="<APALACHE_HOME>/3rdparty/lib:<HOME>/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:."/>
```

**Comment by shonfeder** [comment]
I wonder if we are hitting this: https://support.azul.com/hc/en-us/articles/360039650212-On-MacOS-10-15-3-and-later-Zulu-Java-doesn-t-load-the-JNI-Libraries-my-Application-needs

> Apple now requires Application executables like Java to be Notarized. As part of this process, with MacOS 10.15.3, the executables must be Hardened Runtime. In order to be Notarized, and once the Hardened Runtime executables and libraries are installed in the /System and /Library hierarchies, they cannot load libraries which have not been Notarized. Note that Apple has been tightening this up progressively.

**Comment by lemmy** [comment]
> I wonder if we could be hitting something related to: https://support.azul.com/hc/en-us/articles/360039650212-On-MacOS-10-15-3-and-later-Zulu-Java-doesn-t-load-the-JNI-Libraries-my-Application-needs
> 
> > Apple now requires Application executables like Java to be Notarized. As part of this process, with MacOS 10.15.3, the executables must be Hardened Runtime. In order to be Notarized, and once the Hardened Runtime executables and libraries are installed in the /System and /Library hierarchies, they cannot load libraries which have not been Notarized. Note that Apple has been tightening this up progressively.

@shonfeder If it turns out you have to notarize apalache, you can probably save yourself some time and [copy&paste much of what I did for the Toolbox](https://github.com/tlaplus/tlaplus/blob/fc24bcbb9905d97a0dab9bcdd1c2f201c94a6500/.github/workflows/main.yml#L199-L244).

**Comment by shonfeder** [comment]
Thanks, @lemmy! 

iiuc, if this does turn out to be problem (I still haven't managed to confirm it), we'll actually need to get z3 notarized. That said, notarizing apalche should be done eventually too I imagine.

**Comment by romac** [comment]
FWIW I am also unable to compile Apalache (full log below).

I wonder whether it might be worth porting the build to sbt at some point, and see if that smoothes things out?

<details>
<summary>Click to show full log</summary>
<pre>
[INFO] ------------------------------< Box:box >-------------------------------
[INFO] Building box 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ box ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/coromac/Informal/Code/Apalache/apalache/3rdparty/Box/Box/src/main/resources
[INFO]
[INFO] --- scala-maven-plugin:3.1.6:add-source (scala-compile-first) @ box ---
[INFO] Add Source directory: /Users/coromac/Informal/Code/Apalache/apalache/3rdparty/Box/Box/src/main/scala
[INFO] Add Test Source directory: /Users/coromac/Informal/Code/Apalache/apalache/3rdparty/Box/Box/src/test/scala
[INFO]
[INFO] --- scala-maven-plugin:3.1.6:compile (scala-compile-first) @ box ---
[WARNING]  Expected all dependencies to require Scala version: 2.12.0
[WARNING]  org.scalatest:scalatest_2.12:3.0.4 requires scala version: 2.12.3
[WARNING] Multiple versions of scala libraries detected!
[INFO] /Users/coromac/Informal/Code/Apalache/apalache/3rdparty/Box/Box/src/main/scala:-1: info: compiling
[INFO] Compiling 3 source files to /Users/coromac/Informal/Code/Apalache/apalache/3rdparty/Box/Box/target/classes at 1600251995957
[ERROR] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.$anonfun$getModuleOrClass$4(Mirrors.scala:54)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:54)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:267)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:267)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1447)
[ERROR] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1126)
[ERROR] 	at scala.tools.nsc.MainClass.doCompile(Main.scala:24)
[ERROR] 	at scala.tools.nsc.Driver.process(Driver.scala:55)
[ERROR] 	at scala.tools.nsc.Driver.main(Driver.scala:68)
[ERROR] 	at scala.tools.nsc.Main.main(Main.scala)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[ERROR] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.620 s
[INFO] Finished at: 2020-09-16T12:26:36+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.6:compile (scala-compile-first) on project box: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
</pre>
</summary>

**Comment by shonfeder** [comment]
I've been advocating porting the build system :)

**Comment by shonfeder** [comment]
@romac I think this is an unrelated issue. Could you post it as it's own issue?

**Comment by shonfeder** [comment]
I haven't been able to workaround this problem following the guidance at
https://support.azul.com/hc/en-us/articles/360039650212-On-MacOS-10-15-3-and-later-Zulu-Java-doesn-t-load-the-JNI-Libraries-my-Application-needs, which I think would count as confirmation. However, I am seeing the same behavior using AdoptOpenJDK on MacOS 10.15.4.

**Comment by shonfeder** [comment]
I checked out a commit from before I reworked the `pom.xml` and hit the same error on a clean build, so I think we can at least rule out a problem introduced by my refactoring of the build configuration.

**Comment by konnov** [comment]
I am wondering, how it is related to OpenJDK. Is anybody successful with Oracle JDK on Mac OS? It worked for me.

**Comment by shonfeder** [comment]
I've reproduced the same behavior with Oracle JDK :/

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/sf/opt/apache-maven-3.6.3
Java version: 1.8.0_261, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"
```

**Comment by konnov** [comment]
Does not one have to notarize apps for the end-users? I guess, if somebody goes as far as building the project from sources, we should consider them developers. Is there a simple approach for the developers?

**Comment by shonfeder** [comment]
**If** the notarization is the problem here, then, iiuc, the problem would be with the z3 JNI not being notarized (perhaps related to the binary also not being notarized, see Z3Prover/z3#2690), as per the [Azule documentation](https://support.azul.com/hc/en-us/articles/360039650212-On-MacOS-10-15-3-and-later-Zulu-Java-doesn-t-load-the-JNI-Libraries-my-Application-needs):

> In order to ensure that your application is able to continue to load any third-party libraries in the future, contact the library authors and let them know that you need them to submit their libraries for Notarization.

However, as I noted, I used the workaround Azule describes there, and it didn't resolve issue. So I'm really not sure that this is the problem.

Note that MacOS users have reported problems loading the Java API for Z3 since at least 2015 on mac 10.10.4: Z3Prover/z3#384

I would surely be useful to notarize Apalache itself at some point for end users, as part of the packaging effort, but afaict that is orthogonal to this issue.

> Is there a simple approach for the developers?

I'm sure! I continue investigating. I am going to experiment with using [z3-turnkey](https://github.com/tudo-aqua/z3-turnkey) today, which is aimed at addressing precisely this kind of problem.
