### ISSUE TITLE
Implement ADR-020

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#2184]
[ADR-020](https://apalache.informal.systems/docs/adr/020adr-arenas.html) introduced a refactoring that can potentially speed up the model checker.

The preliminary plan is as follows:

 - [ ] Refactor `Z3SolverContext` to deal with arena pointers. The core method is in:
    https://github.com/informalsystems/apalache/blob/acf9841bad35c536efb336a7c8ac903ff55a4a0d/tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala#L203

**Comment by Kukovec** [comment]
Per our recent discussion offline, the plan is to start with the following:
  - [ ] Implement a version of `Arena`s, with `ElemPtr`s and _no_ `SolverContext`
  - [ ] Create a class `X` (name TBD) that wraps an `Arena` and `SolverContext` pair, so they can be modified in lockstep
  - [ ] Replace the current arena use with the above structure

Basically, the idea is that arenas always perform the `-NoSmt` versions of their methods, and `X` declares the interface that the current arenas use, prompting the solver context to declare variables and push constraints whenever the arena gets extended.

**Comment by Kukovec** [comment]
Completed a while ago
