### ISSUE TITLE
Shai: Check multiple invariants against a loaded model

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#2196]
@hvanz requested a feature exposed by the server that would allow loading a model, and submitting queries to check different invariants.

I think it's unclear yet what kind of performance or usability improvement this would provide over just checking a spec multiple times with different invariants, but perhaps in the context of the transition explorer this could allow to benefit from previous checking progress to avoid having to recompute symbolic state spaces?

Filing an issue to record the idea for brainstorming.

**Comment by thpani** [comment]
I believe we can disregard this, given the discontinuation of MBT and lack of other consumers for this feature.
