### ISSUE TITLE
Expose functionality to negate an invariant and check the result

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#2198]
Requested by @andrey-kuprianov as a relatively high-priority need for MBT.

Two possible UI's to expose this functionality were discussed:

1. Add a flag to the `check` command, like `--inv-not` that works like `--inv` but negates the named operators on preprocessing.
2. Implement a new subcommand with dedicated support for this functionality. Andre suggested thinking of this a "trace generation mode".

If we opt for (2) we'll also need to expose this new command via the server. If we opt for (1), then server support comes out of the box.

**Comment by thpani** [comment]
Closing for
1. discontinuation of MBT, and
2. support of this functionality in [Quint](https://github.com/informalsystems/quint) (where `--invariant` takes an expression)
