### ISSUE TITLE
Run-specific output directory does not contain `log0.smt`

### ISSUE THREAD

**Issue by thpani** [informalsystems/apalache#2206]
## Description

A run-specific output directory specified via `--run-dir=` does not contain all logs present in the output manager directory.
At least `log0.smt` is missing.

## The command line parameters used to run the tool

```sh
$ apalache-mc check --inv=Mutex --discard-disabled=false --length=5 --run-dir=my-run-dir test/tla/MC_LamportMutexTyped.tla
...
$ ls _apalache-out/MC_LamportMutexTyped.tla/2022-10-13T12-52-46_10973399926204913460
detailed.log log0.smt     run.txt
$ ls my-run-dir
detailed.log run.txt
```

**Comment by Kukovec** [comment]
Have you tried the same command + `write-intermediate=true`?

**Comment by thpani** [comment]
Intermediate files are working, as far as I can tell this only affects the SMT log for now.

**Comment by thpani** [comment]
I'm gonna take a look.

**Comment by thpani** [comment]
Related to #1320
