### ISSUE TITLE
Implement a `Gen` for well-typed expressions

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#2211]
`IrGenerators` construct arbitrarily-typed expressions, which cannot be used in tests requiring type-correctness (e.g. JSON (de)serializaiton via ScopedBuilder). We should extend these generators, so we can construct expressions, which are guaranteed to be well-typed.

**Comment by thpani** [comment]
There is also https://github.com/informalsystems/apalache/issues/1379, we can close either one.

**Comment by Kukovec** [comment]
Ah, so I was right, we did have an issue already. I'll close this one,
