### ISSUE TITLE
Extend `SourceOption` with ITF format support

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#2222]
Currently, `SourceOption.FileSource.apply` uses `FilenameUtils.getExtension` to determine the file extension. Unfortunately, ITF file names have the shape `<name>.itf.json`. As `getExtension("a.b.c")` will return `c` we should either:

- Change the ITF file names to just `<name>.itf`, or
- Implement a custom `getExtension`

**Comment by Kukovec** [comment]
@shonfeder thoughts?

**Comment by shonfeder** [comment]
I've suggested an alternative via composition of a couple `FilenemUtils` method in #2233
