### ISSUE TITLE
Introduce the module `Lists`

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#2227]
It's hard to translate an algorithm using vectors/lists/sequences from virtually any programming language to TLA+. The need for adjusting indices and slices from `1..Len(s)` to `0..Len(s) - 1` and back explodes my brain. Even simple specs have plenty of bugs caused by that.

Since `Sequences` is an add-on to TLA+ and does not belong to the core of the logic anyhow, I propose to introduce the module `Lists` which would mirror the operators of `Sequences` but has 0-based indices.

**Comment by konnov** [comment]
My backlog is too long. So it would be great, if somebody else could write this TLA+ module.

**Comment by thpani** [comment]
It seems like we have better support for this through https://github.com/informalsystems/quint.
@konnov do you think this is still relevant?

**Comment by konnov** [comment]
Yeah, it's not hard to write such a module, but this is probably less relevant in the presence of quint
