### ISSUE TITLE
[FEATURE] Standalone command to run type inference

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#225]
Similar to `apalache typecheck`, introduce the command:

```
apalache typeinfer <spec>
```

This command would run type inference and produce type annotations that can be consumed by `typecheck`. The passes and modules can be copied from the type checker.

**Comment by konnov** [comment]
See `TypeCheckCmd` and `TypeCheckerModule`. The type inference command should behave in a similar way.

**Comment by Kukovec** [comment]
We've agreed to abandon type inference in favor of type-checking.
