### ISSUE TITLE
Simplify ITF collection representation

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#2266]
If #2258 gets implemented, we can drop the single `#`-prefixed object wrapper, as types will then be able to guide reconstruction from a json array. 
E.g. instead of
```
"mapVariable": {
  "#map": [ [k1, v1], ..., [kn, vn] ]  
}
```
we could just have 
```
"mapVariable": [ [k1, v1], ..., [kn, vn] ]
```
because the `"vars"` field would already contain `{ ... "mapVariable": "a -> b" }`.

**Comment by rnbguy** [comment]
- Having an option to switch between these formats would be nice.
- Is it possible to encode types in JSON rather than a simple string?

For example, `{"Fun": {"inputs": ["a"], "output": "b"}}` instead of `"a -> b"`.

**Comment by Kukovec** [comment]
> Having an option to switch between these formats would be nice.

I don't think so, especially since the "ITF-with-types" variant contains strictly more information than the normal one. If you don't need types, just ignore them.

> Is it possible to encode types in JSON rather than a simple string?

Yes, but `{"inputs": ["a"], "output": "b"}` is not a representation of any valid TlaType1 type. Having e.g.
```js
"type": {
  "kind": "FunT1"
  "args": {
    "from": "StrT1"
    "to": "IntT1"
  }
}
```
is the alternative, because both that and the string version can be parsed into a TT1 type from within Apalache. Any homebrew json representation of a type is useless to us.

**Comment by rnbguy** [comment]
> I'm not opposed per se, but I still don't see the value in having this intermediate wrapper.

It is mainly for back compatibility.

> is not a representation of any valid TlaType1 type

Mine was an example. I am okay with your example.

**Comment by rnbguy** [comment]
I agree with you. Human readability will be improved for sure. But this adds extra overhead at machine parsing.

Nonetheless, adding type info (#2258) would be helpful for Atomkraft's reactor generation !

**Comment by shonfeder** [comment]
> Human readability will be improved for sure

To be clear, I think human readability with *NOT* improve: I think it will get worse :) This is because, looking a state `{"v" : [1, 2], "x" : [2,1]}` humans will have no way of knowing whether or not "v" should equal "x", because they won't know whether these are sets or sequences without consulting the types for the variables stored in a different key. This problem could occur any number of times in more complex cases.

I agree #2258 should go forward regardless! :)

**Comment by Kukovec** [comment]
Alright, since the consensus seems to be "keep #-tags" I'll close this issue, and just implement #2258.
