### ISSUE TITLE
Extend builder with tupled bound variable methods

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#2292]
The `ScopedBuilder` offers methods with which one can produce IR in normalized form. As such, it cannot be used to construct, e.g.
`\E <<x,y>> \in S: P(x,y)`, since `\E` expects a single variable name.
Instead of modifying `ScopedBuilder`, we should add tupled alternatives to any method, which may introduce bound variables (`\E, \A`, map, filter) in an extension.

**Comment by Kukovec** [comment]
Potentially rolled into #2301, closing as standalone

**Comment by shonfeder** [comment]
As discussed in our meeting today this will unblock #2454.
