### ISSUE TITLE
`Print()` and `Assert()` from TLC module does not work

### ISSUE THREAD

**Issue by kikimo** [informalsystems/apalache#2336]
While verify a [raft](https://github.com/kikimo/apa-raft/blob/master/Raft.tla) tla spec using Apalache, I found two problem:

1. The `Printf()` from TLC module does not print anything in the console
2. The `Assert()` from TLC module also seems not work, eg. typing `/\ Assert(FALSE, "violation meet")` in the spec does making Apalanche to report error as expected

So does these two functions supported in Apalanceh? How can we make theses two functions work, they are so useful when debuging a spec.

Apalache version: 0.30.1

**Comment by Kukovec** [comment]
They are not supported and will _never_ be supported, because Apalache, unlike TLC, does not explore traces one-by-one, but creates a constraint representation of all n-step reachable states. In the constraint encoding, printing/asserting isn't really well defined.

**Comment by Kukovec** [comment]
If you find yourself needing assert, you can check out [Quint](https://github.com/informalsystems/quint). It's an alternative input language to TLA+, which will eventually become supported as input for Apalache. It has an [assert](https://github.com/informalsystems/quint/blob/main/doc/lang.md#assert), and a simulator you can experiment with, which should help with your debugging.

**Comment by kikimo** [comment]
@Kukovec got it, thanks a lot, and so I'm going to close this issue.
