### ISSUE TITLE
Using Variants in heterogeneous sets

### ISSUE THREAD

**Issue by czhang-fm** [informalsystems/apalache#2361]
## Description

In Section 9. "How to write type annotations", Recipe 4 "Using variants in heterogeneous sets"

I've been trying with the example from downloaded "TwoPhase.tla" and "Commit.tla"
I embedded the type alias declaration and the Variants constructors.

```tla
(*
 @typeAlias: message = Commit(NIL) | Abort(NIL) | Prepared(RM);
 *)

\* @type: $message;
MkCommit == Variant("Commit", "0_OF_NIL")

\* @type: $message;
MkAbort == Variant("Abort", "0_OF_NIL")

\* @type: RM => $message;
MkPrepared(rm) == Variant("Prepared", rm)
```

However, the type checker keeps on complaining 

```
[TwoPhase.tla:72:3-72:68]: An operator with the signature ((Set(a159), Set(a159)) => Set(a159)) cannot be applied to the provided arguments of type Set({ rm: R, type: Str }) and Set({ type: Str }) E@08:57:36.434
```

which seems to be the line in TwoPhase.tla even with the type annotation.

```tla
\* @type: Set($message);
Message ==
  (*************************************************************************)
  (* comments omitted here  *)
  (*************************************************************************)
  [type : {"Prepared"}, rm : RM]  \cup  [type : {"Commit", "Abort"}] 
```

Could you kindly point out what the problem is?
Thanks.

## System information

- Apalache version [`apalache-mc version`]: 0.30.1
- OS [e.g. Ubuntu Linux or Mac OS, and the current version]: Mac OS, 13.0.1 (22A400)
- JDK version [e.g. OpenJDK 0.8.0]: "11.0.16.1" 2022-08-18 LTS
[TwoPhase.tla.txt](https://github.com/informalsystems/apalache/files/10484375/TwoPhase.tla.txt)

## Triage checklist (for maintainers)

- [ ] Reproduce the bug on the main development branch.
- [ ] Add the issue to the apalache GitHub project.
- [ ] If the bug is high impact, ensure someone available is assigned to fix it.

**Comment by Kukovec** [comment]
Hi @czhang-fm! I'm not at my machine to fully test this right now, but one thing that sticks out to me is that 
```tla
(*
https://github.com/typealias: message = Commit(NIL) | Abort(NIL) | Prepared(RM);
*)
```
does not seem to be attached to an operator. Try:
```tla
(*
https://github.com/typealias: message = Commit(NIL) | Abort(NIL) | Prepared(RM);
*)
ALIASES == TRUE
```
if this doesn't fix it I'll look into it tomorrow.

**Comment by czhang-fm** [comment]
Thanks so much for the reply ! 

I've made a second try on the windows laptop (with a bash shell), trying apalache version 0.29.0, and it showed up the following outputs (I suspect that may be the problem of the MKPrepared Variant). Source files are attached at the end.

$ apalache-mc typecheck TwoPhaseTyped.tla
16:22:51.652 [main] INFO at.forsyte.apalache.tla.tooling.opt.TypeCheckCmd - Loading configuration
# Usage statistics is OFF. We care about your privacy.
# If you want to help our project, consider enabling statistics with config --enable-stats=true.

Output directory: D:\TLA+\tendermint-fork-cases-annotations\_apalache-out\TwoPhaseTyped.tla\2023-01-24T16-22-52_3074909238948826598
# APALACHE version: 0.29.0 | build: 83dc095                       I@16:22:52.448
Type checking TwoPhaseTyped.tla                                   I@16:22:52.729
PASS #0: SanyParser                                               I@16:22:52.729
Parsing file D:\TLA+\tendermint-fork-cases-annotations\TwoPhaseTyped.tla
Parsing file D:\TLA+\tendermint-fork-cases-annotations\TwoPhaseTyped_typedefs.tla
Parsing file C:\Users\admin\AppData\Local\Temp\Variants.tla
Parsing file D:\TLA+\tendermint-fork-cases-annotations\TCommit.tla
PASS #1: TypeCheckerSnowcat                                       I@16:22:53.337
 > Running Snowcat .::.                                           I@16:22:53.337
[TwoPhaseTyped.tla:61:4-63:45]: An operator with the signature ((Set(a159), Set(a159)) => Set(a159)) cannot be applied to the provided arguments of type Set({ rm: RM, type: Str }) and Set({ type: Str }) E@16:22:53.822
[TwoPhaseTyped.tla:52:1-63:46]: Error when computing the type of Message E@16:22:53.837
 > Snowcat asks you to fix the types. Meow.                       I@16:22:53.837
Type checker [FAILED]                                             I@16:22:53.837
It took me 0 days  0 hours  0 min  1 sec                          I@16:22:53.837
Total time: 1.389 sec                                             I@16:22:53.837
EXITCODE: ERROR (120)


[TwoPhaseTyped.tla.txt](https://github.com/informalsystems/apalache/files/10486869/TwoPhaseTyped.tla.txt)
[TwoPhaseTyped_typedefs.tla.txt](https://github.com/informalsystems/apalache/files/10486870/TwoPhaseTyped_typedefs.tla.txt)

**Comment by Kukovec** [comment]
So the problem you have is that
```
[type : {"Prepared"}, rm : RM]  \cup  [type : {"Commit", "Abort"}] 
```
are _not_ sets of variants. You cannot just use type annotation to force records to be interpreted as variants. If you wanted to construct the set of variants, you'd need to use the variant constructors.
```
{MkPrepared(rm): rm \in RM } \cup {MkCommit, MkAbort}
```

Side note: I don't see this set being used anywhere besides `TypeOK`. `TypeOK` operators are actually redundant in Apalache, since we have a static typechecker.

**Comment by czhang-fm** [comment]
Thanks so much! 
This indeed solved the issue (as I tested). Now I notice that "Variant" is actually a different type from the "Record" type, but it can be used to encode mixed records. This also means that it will take (sometimes significant amount of) rewriting to make an old model that has mixed records to work with the new type system.
