### ISSUE TITLE
Benchmark assumptions with push/pop

### ISSUE THREAD

**Issue by thpani** [informalsystems/apalache#2369]
Subtask of #2137 to empirically evaluate #2369

**Comment by konnov** [comment]
Wow! That's not what we expected, right? Maybe it's worth comparing to the same experiments when using `--discard-disabled=false`.

**Comment by thpani** [comment]
As the current evaluation is a bit inconclusive, @konnov suggested to benchmark in offline mode instead.

That should give us a full assumption-based encoding for further benchmarking, without the implementation friction of figuring out how to handle caches.

Following up in a separate issue: #2412
