### ISSUE TITLE
Rework set-generating rules to leverage pointers: ITE

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#2377]
A set generated by ITE has a fixed pointer to `c` iff both the then- and the else-branch sets contain a fixed pointer to `c`.
In general, it contains `SmtExprPtr`s.

**Comment by Kukovec** [comment]
@konnov  we should consider skipping this intermediate-step issue and implementing the change directly as it would be after #2384.

The reason for this is the following:
ITF, when returning sets (or more precisely, cherry-pick) implements an optimization, which bounds the size of the resulting set in the arena.
Concretely, `ITF(_, c_T, c_E)`, where `c_T` and `c_E` are set cells, gets rewritten into a cell `c`, such that `c` has `max(n, m)` edges in the arena, where `n` is the number of has-edges belonging to `c_T`, and `m` is the number of has-edges belonging to `c_E`.

Each element pointed to by `c` is determined by cherry-picking from same-indexed (w.r.t. the has-relation enumeration with padding) elements from `c_T` and `c_E`. However, this approach does not combine nicely with `FixedElemPtr`s. Consider the following expression:

```tla
IF ... THEN {1,2} ELSE {2,3}
```

After rewriting, the arena has `c_T -(has)-> c_1,c_2` and `c_E -(has)-> c_2,c_3`, where, importantly, the literal 2 gets rewritten into the same cell `c_2` in both translations. Both `c_T` and `c_E` point at all of their elements via fixed pointers.

Since both `c_T` and `c_E` have fixed pointers to `c_2`, it should be the case that `c` does as well. However, given the cherry-pick approach, we would end up with `c -(has)-> c_x,c_y`, where, depending on the oracle value, either `c_x` or `c_y` may equal `c_2` (but always exactly one of them, since they use the same oracle). The pointers from `c` to `c_x,c_y` cannot always be fixed, because it may happen that one of the sets is empty, in general.

In the final version of this rule, the has-construction for `c` should be done as follows (in the general cherry-pick set case of N sets):
  - Assume we have an oracle `o`, with oracle values `1,...,N` determining which element (set) gets picked
  - Collect all of the cells pointed to by at least one candidate set
    - if a cell is pointed to by all of the candidates via fixed pointers, then it is pointed to by `c` via fixed pointer
    - if a cell is pointed to by candidates `i_1,...,i_m`, via pointers `p_i_1, ..., p_i_m` (some of which may be fixed, but either not all of them are, or `i_m < N`), then `c` points to it via a pointer `p`, such that `p.toSmt :=  \/_(j=1)^m (o = i_j /\ p_i_j.toSmt)`

The maximal size of the has-relation of `c` is then `n_1 + ... + n_N`, instead of `max(n_1, ..., n_N)`, where `n_i` is the number of has-edges belonging to the i-th set (however, no additional cells and edges need to be constructed in the arena to represent the individual sub-cherrypicks of the zipped elements, so the _total_ size of the arena doesn't actually increase, but in fact decreases)

**Comment by konnov** [comment]
I think I understand the issue. My proposal would be to turn all pointers to smt pointers and introduce `max(n, m)` pointers (as it is done now). Otherwise, multiple applications of cherry pick (e.g., via multiple assignments) may introduce more and more pointers, if we do as explained in the last point.

**Comment by Kukovec** [comment]
> I think I understand the issue. My proposal would be to turn all pointers to smt pointers and introduce `max(n, m)` pointers (as it is done now). Otherwise, multiple applications of cherry pick (e.g., via multiple assignments) may introduce more and more pointers, if we do as explained in the last point.

The thing is that the current implementation actually introduces _more_ pointers total. While it's true that the set cell only has `max(n, m)` edges, the process actually introduces `max(n, m)` cells, each with 2 additional edges. With this proposal, you don't need to introduce intermediate cells at all, just the edges. Basically one wide tree vs a number of less-wide trees.
