### ISSUE TITLE
Incorrect type signature on `Print` and `PrintT` from TLC module

### ISSUE THREAD

**Issue by BGR360** [informalsystems/apalache#2448]
## Description

Snowcat reports a type error when passing anything except a string as `Print` or `PrintT` from the TLC module.

Real TLC accepts any type of value in these positions.

## Impact

Can't use Apalache to typecheck all valid TLA+ specs.

## Input specification

```tla
---- MODULE PrintProblem ----

EXTENDS TLC

VARIABLES
    \* @type: Str;
    a,
    \* @type: Bool;
    b,
    \* @type: Int;
    c,
    \* @type: Set(Str);
    d,
    \* @type: Seq(Str);
    e,
    \* @type: { x: Str, y: Str };
    f

Init ==
    /\ a = "hello world"
    /\ b = TRUE
    /\ c = 0
    /\ d = {"hello", "world"}
    /\ e = <<"hello", "world">>
    /\ f = [x |-> "hello", y |-> "world"]

Next ==
    /\ a = Print("", "hello world")                     \* ok
    /\ b = Print("", TRUE)                              \* ok
    /\ c = Print("", 0)                                 \* ok
    /\ d = Print("", {"hello", "world"})                \* ok
    /\ e = Print("", <<"hello", "world">>)              \* ok
    /\ f = Print("", [x |-> "hello", y |-> "world"])    \* ok
    /\ a = Print(a, "hello world")                      \* ok
    /\ b = Print(b, TRUE)                               \* ERROR
    /\ c = Print(c, 0)                                  \* ERROR
    /\ d = Print(d, {"hello", "world"})                 \* ERROR
    /\ e = Print(e, <<"hello", "world">>)               \* ERROR
    /\ f = Print(f, [x |-> "hello", y |-> "world"])     \* ERROR
    /\ PrintT(a)    \* ok
    /\ PrintT(b)    \* ERROR
    /\ PrintT(c)    \* ERROR
    /\ PrintT(d)    \* ERROR
    /\ PrintT(e)    \* ERROR
    /\ PrintT(f)    \* ERROR
    /\ UNCHANGED <<a, b, c, d, e, f>>

Spec == Init /\ [][Next]_<<a, b, c, d, e, f>>

====
```

## The command line parameters used to run the tool

```
apalache-mc typecheck PrintProblem.tla
```

## Expected behavior

`Print` and `PrintT` accept any type of input.

Type sigs should probably be:

```tla
\* @type: (a, b) => b;
Print(a, b) == (* ... *)

\* @type: (a) => Bool;
PrintT(a) == (* ... *)
```

## System information

- Apalache version [`apalache-mc version`]: 0.30.2

## Triage checklist (for maintainers)

- [ ] Reproduce the bug on the main development branch.
- [x] Add the issue to the apalache GitHub project.
- [ ] If the bug is high impact, ensure someone available is assigned to fix it.

**Comment by Kukovec** [comment]
`Print` is a TLC operator, not an Apalache operator. We have no plans for supporting it. See #2336

**Comment by BGR360** [comment]
@Kukovec I know that, and I am not asking for support for these operators in Apalache. I'm asking for Snowcat to not fail typechecking because of it. If you read my issue again, I said that the impact of this issue is that I cannot use Apalache to *typecheck* a TLA+ spec. I already know Apalache isn't suitable for model checking my spec.

Apalache already has some understanding of the type signature of these operators, it's just incorrect. I'm just asking for that to be fixed.

**Comment by Kukovec** [comment]
> Apalache already has some understanding of the type signature of these operators, it's just incorrect. I'm just asking for that to be fixed.
Why do you believe the type signature is incorrect?

**Comment by BGR360** [comment]
> Why do you believe the type signature is incorrect?

Because it's more restrictive than what actual TLC accepts. If you run the example I provided, you'll see that Apalache believes the type to be `Print: (Str, a) => a` and `PrintT: (Str) => Bool`. Those `Str`s should also be type vars.

**Comment by konnov** [comment]
Hi @BGR360!

We have assigned type signatures kind of randomly, since I could not find (or did not care much about finding) good documentation on the expected behavior of `Print` and `PrintT`. Now looking at `PrintT`, our type signature for it seems to be wrong. Not sure about the signature `Print`, but it is also trivial to fix.

The type signatures for `Print` and `PrintT` are defined here:

https://github.com/informalsystems/apalache/blob/e38fb1fccb28b31979d01c4874c9c53ed0e9e537/src/tla/__rewire_tlc_in_apalache.tla#L43-L53

If you could create a pull request that contains the following items, that would help:

 - a two-line fix to `__rewire_tlc_in_apalache.tla`,
 - your test,
 - an entry in the [test suite](https://github.com/informalsystems/apalache/blob/main/test/tla/cli-integration-tests.md), see the documentation in the file.
