### ISSUE TITLE
Convert quint's `nondet x = oneOf(...); A` to a nondet existential quantification.

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#2450]
This will require special treatment in 

https://github.com/informalsystems/apalache/blob/ecdc52ff5cd383ffef03f56a525101608610d679/tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala#L90-L99

We'll be mapping

```
nondet x = oneOf(S); A
```

to

```
\E x \in S: A
```

Thanks to @konnov and @gabrielamafra for the pointers here.

**Comment by konnov** [comment]
I realized a few days ago that `nondet x = oneOf(S); A` should be translated to:

```
S /= {} /\ \E x \in S: A
```

Since `oneOf` is a function, it requires non-emptiness of `S`, whereas `\E x \in S: A` simply returns `FALSE` when `S` is empty.

**Comment by thpani** [comment]
> Since `oneOf` is a function, it requires non-emptiness of `S`, whereas `\E x \in S: A` simply returns `FALSE` when `S` is empty.

I don't get it, what does the `S /= {}` do, on top of making the expression evaluate to `FALSE`?

**Comment by konnov** [comment]
> > Since `oneOf` is a function, it requires non-emptiness of `S`, whereas `\E x \in S: A` simply returns `FALSE` when `S` is empty.
> 
> I don't get it, what does the `S /= {}` do, on top of making the expression evaluate to `FALSE`?

Oh, I think you are right. It's actually the other way around: `\E x \in S: A` of TLA+ should be understood as `any { S == Set(), nondet x = oneOf(S); A }`.

**Comment by thpani** [comment]
Still not sure I understand. In the case where `S = {}`, wouldn't

```
any { S == Set(), all { S != Set(), nondet x = oneOf(S); A } }
```

be true, and `\E x \in S: A` be false?

**Comment by konnov** [comment]
> Still not sure I understand. In the case where `S = {}`, wouldn't
> 
> ```
> any { S == Set(), all { S != Set(), nondet x = oneOf(S); A } }
> ```
> 
> be true, and `\E x \in S: A` be false?

Sorry. I am a bit tired today :)

Yes, you are right. We need only the `all` part. Fixed in the comment above.
