### ISSUE TITLE
Make tests compatible with scalatest 3.3

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#247]
We are currently 3 minor versions behind in our use of the ScalaTest library. It seems they made breaking changes in later versions (see #233), and we'll need to adapt if we want to keep that dependency up to date.

For details on the failures see https://github.com/informalsystems/apalache/pull/233/checks?check_run_id=1157162892

**Comment by konnov** [comment]
This issue is older than one year. Shall we close it?

**Comment by thpani** [comment]
The ScalaTest version we use is from 2016 and the "hello world" example from scalatest.org doesn't build against our dependency. I think we should keep this open.

**Comment by konnov** [comment]
Right. I am not sure about how extensively we are using ScalaTest. It would be good to estimate how much work this could imply.

**Comment by shonfeder** [comment]
I'd be in favor of closing this... by completing it :)
