### ISSUE TITLE
Update to Scala 2.13

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#248]
See #235 

When time permits, we should probably update our code so we can use the latest Scala. For details on the current failures, see https://github.com/informalsystems/apalache/pull/235/checks?check_run_id=1157163965

**Comment by konnov** [comment]
It looks like scala-library is not really backwards compatible. Yes, let's plan for the change. It doesn't seem to be a lot of work.

**Comment by konnov** [comment]
This one has been done some months ago

**Comment by thpani** [comment]
Closed by #1509
