### ISSUE TITLE
[FEATURE] Return a non-zero exit code when model checking fails

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#249]
Currently users have to inspect stdout in order to determine whether `check` succeeds or fails. It would help with command-line usability to also signal this result with a meaningful error code.

**Comment by lemmy** [comment]
In the interest of compatibility between Apalache and TLC (e.g. Toolbox integration), please consider mapping to the same exit/error codes as TLC:

https://github.com/tlaplus/tlaplus/blob/d5654d93bc5787026382201fda7aa3fbb55222c6/tlatools/org.lamport.tlatools/src/tlc2/output/EC.java#L303-L418

**Comment by konnov** [comment]
I am not sure I like the idea of error codes for every kind of a situation, as it is hard to enforce. I would rather produce a few error codes and think about the message format in the log file or a separate file.

**Comment by konnov** [comment]
Does Toolbox process all of these exit codes from TLC?

**Comment by lemmy** [comment]
The Toolbox parses a (disjunct) set of codes that are printed as part of TLC's `stdout` output.  (Process) exit codes came later to more easily integrated with e.g., scripts, CI, ... (CommunityModules fail tests via exit codes in Github Actions).

In hindsight, parsing TLC's output was a bad design choice.  Even with codes, the schema- and version-less format caused many bugs and even performance problems.  Instead, for the TLC <> Toolbox communication, something like RMI would have been a much saner interface (although restricted to the JVM).  Today, I would lean towards an architecture like LSP/DAP but with XML as the data-interchange format.  The interactive mode of Apalache discussed elsewhere is obviously related.
