### ISSUE TITLE
Normal form for TLA+ operators

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#26]
Handling LET-IN is tedious. Shall we introduce top-level operators instead?

For instance:

```tlaplus
A(x) ==
  \E y \in S:
    LET z = x + y IN
      x * y * z
```

should become:

```tlaplus
A_z(x, y) == x + y

A(x) ==
  \E y \in S:
    x * y * A_z(x, y)
```

**Comment by konnov** [comment]
Alternatively, we can turn all operator declarations into LET-IN operators:

```
A(x, y) == x + y

Next == A(3, 4)
```

becomes

```
Next ==
  LET A(x, y) == x + y IN
  A(3, 4)
```

**Comment by quicquid** [comment]
The second option would need alpha renaming - consider the specification:

     A(x, y) == x + y
    VARIABLE x
    Next == A(3, 4)

Then moving the definition of `A(x,y)` over the variable declaration leads to a name clash unless the parameter `x` is renamed.

**Comment by konnov** [comment]
That is true. We will need renaming. We are trying to minimize the internal representation of the language, so we either have only operator definitions without let-in, or only let-in without operator definitions. The latter seems to be closer to the functional languages.

**Comment by konnov** [comment]
This issue seems to be complicated. There is no easy way of transforming LET-IN definitions to the operators in the following example:

```tla
A(B(_), x) == B(x)

C(x) ==
  LET D(y) == x + y IN
  A(D, x)

(* an intuitive but incorrect translation would be: *)
A(B(_), x) == B(x)

C_D(x, y) == x + y

C(x) == A(C_D, x)
  (* it does not work,
      as the arity of C_D is different from the arity of B(_) *)

```

The example above will require us to clone the definitions such as `A` and probably propagate the cloning all the way in the call graph. Postponing this issue for a later milestone.

**Comment by konnov** [comment]
The solution with replacing all operators by LET-IN definitions is not satisfactory either, as we would have to duplicate LET-IN definitions for `Init` and `Next`.

**Comment by konnov** [comment]
When I wrote that almost a year ago, I was more stupid than now. We still can have a whole TLA+ spec as a single expression:

```tla
LET ... IN
LET Init == ... IN
LET Next == ... IN
TRUE
```

If we convert a TLA+ spec into this normal form, many annoying issues about module transformation will go away. For instance, we can use just fold.

**Comment by Kukovec** [comment]
I think we've moved in the opposite direction here; we're introducing more local definitions, not fewer. This normal form is likely not something we want anymore. If you agree, this can be closed.

**Comment by konnov** [comment]
perhaps. Let's close it. If we need it again, it will surface in a new issue.
