### ISSUE TITLE
Support binding Quint tuples to operator arguments

### ISSUE THREAD

**Issue by thpani** [informalsystems/apalache#2670]
Quint supports binding tuple elements to operator formal parmeters, e.g.

```bluespec
  pure def c(tup, f) = Set(tup).map(f)
  pure def func(p, g) = p
  pure val test = c((1, 2), func)
```

We need to do this explicitly in Apalache.
An example can be found in https://github.com/informalsystems/quint/blob/99c0c60c600e9b1fef15239c9f46938ea0c3e2c0/examples/language-features/tuples.qnt

**Comment by Kukovec** [comment]
Hmm, I don't think the example in https://github.com/informalsystems/quint/blob/99c0c60c600e9b1fef15239c9f46938ea0c3e2c0/examples/language-features/tuples.qnt _should_ work. You're essentially overloading `combineTuples` to work with tuples of any arity, which I don't think I've seen any of the common languages do.

**Comment by shonfeder** [comment]
This is using the row-ploymorphism of the tuples. If we annotate it, it would be

```
  def combineTuples(t1: (a | r1), t2: (b, c | r2)): (a, c) = (t1._1, t2._2)
  val combined = combineTuples((true, 1, 2), (false, 2, 2))
```

This is just a special case of our support for row-polymorphic records (tuples are records with `_n` labeled fields.

**Comment by thpani** [comment]
This is on-hold until we address https://github.com/informalsystems/quint/discussions/1080

**Comment by thpani** [comment]
Superseded by https://github.com/informalsystems/quint/issues/1113
