### ISSUE TITLE
Error using transpile

### ISSUE THREAD

**Issue by rahildoshi97** [informalsystems/apalache#2672]
## Description

I tried to to transpile the file below to VMT and got an error.

## Input specification

```
---------------------------- MODULE example --------------------------
VARIABLE
    \* @type: Bool;
    val

Init == val = FALSE
Next == val' = ~val
=================================================================
```

## The command line parameters used to run the tool

`transpile example.tla`

## Log files

```
PASS #7: WatchdogPass                                             I@10:54:19.741
<unknown>: internal error in type checking: Expected Typed(_: TlaType1), found: Untyped E@10:54:19.766
at.forsyte.apalache.infra.AdaptedException: <unknown>: internal error in type checking: Expected Typed(_: TlaType1), found: Untyped
        at at.forsyte.apalache.infra.passes.PassChainExecutor$.run(PassChainExecutor.scala:39)
        at at.forsyte.apalache.tla.tooling.opt.TranspileCmd.run(TranspileCmd.scala:25)
        at at.forsyte.apalache.tla.Tool$.runCommand(Tool.scala:138)
        at at.forsyte.apalache.tla.Tool$.run(Tool.scala:118)
        at at.forsyte.apalache.tla.Tool$.main(Tool.scala:40)
        at at.forsyte.apalache.tla.Tool.main(Tool.scala)
Please report an issue at [https://github.com/informalsystems/apalache/issues]: at.forsyte.apalache.infra.AdaptedException: <unknown>: internal error in type checking: Expected Typed(_: TlaType1), found: Untyped
```

## System information

- Apalache version [`apalache-mc version`]: 0.41.0
- OS [e.g. Ubuntu Linux or Mac OS, and the current version]: Windows 10
- JDK version [e.g. OpenJDK 0.8.0]: openjdk 17.0.8 2023-07-18

## Triage checklist (for maintainers)

- [ ] Reproduce the bug on the main development branch.
- [ ] Add the issue to the apalache GitHub project.
- [ ] If the bug is high impact, ensure someone available is assigned to fix it.

**Comment by rodrigo7491** [comment]
@Kukovec Me and @rahildoshi97 started working with the VMT transpilation and run into this. Maybe we can fix it by ourselves when exploring the codebase, but I thought it would be good to log this here. If you have any advice let us know.

**Comment by Kukovec** [comment]
Hey, sorry for the delay, I've just come back from vacation, and I'll take a look at this soon.

**Comment by rahildoshi97** [comment]
Hi,

Together with @rodrigo7491 , we think we found the source of the problem. It seems to be a missing `TypeTag` in line 54 of file on file [PrimingPassImpl.scala](https://github.com/informalsystems/apalache/blob/main/passes/src/main/scala/at/forsyte/apalache/tla/passes/assignments/PrimingPassImpl.scala).

We'll try to fix it in our fork and make a PR here.
