### ISSUE TITLE
Nix Package

### ISSUE THREAD

**Issue by lorenzleutgeb** [informalsystems/apalache#2715]
Regarding #1037: I packaged Apalache in order to use it for the VTSA summer school (presentation held by @konnov). It's a little ad-hoc, but still might be useful to you. It also includes a systemd user service to run the server. See https://github.com/lorenzleutgeb/nur/commit/d307e4b4dd36b1e9d420c242fe37daf025c84444

I could PR a package based on https://github.com/zaninime/sbt-derivation if you like.

/cc: @JonathanLorimer @shonfeder

**Comment by JonathanLorimer** [comment]
@lorenzleutgeb This is awesome. If you wanted to PR this, could you make it against https://github.com/informalsystems/cosmos.nix 

I believe there is already an [apalache derivation](https://github.com/informalsystems/cosmos.nix/blob/master/resources/apalache.nix)

**Comment by lorenzleutgeb** [comment]
Yeah. I could refactor the inline patch there, and add a home manager module for the service. 

And maybe a PR to this repo that advertises cosmos.nix in `flake.nix`? Would have saved me some work. I saw that there's a `flake.nix` but gave up as soon as I saw.that it does not output any packages but only a development shell. For an outsider like me, better discoverability would help. Another option would be to consume the cosmos.nix flake as an input and output the respective Apalache package...

**Comment by JonathanLorimer** [comment]
Agreed that better discoverability would be good. In my ideal world each project would export its own package, but we decided to keep the nix minimal in project specific repos as a courtesy to non-nix users.

I don't think we would want a home manager module for the service, but rather a NixOS module? I'd be interested what the use case for a home-manager module would be.

**Comment by lorenzleutgeb** [comment]
> Agreed that better discoverability would be good. In my ideal world each project would export its own package, but we decided to keep the nix minimal in project specific repos as a courtesy to non-nix users.

Fair. A hint in `flake.nix` would not impact other users and still help.

> I don't think we would want a home manager module for the service, but rather a NixOS module? I'd be interested what the use case for a home-manager module would be.

My idea was that I would probably not want to expose my Apalache instance to other users (not on the same machine and not via the network). Again, I am not as familiar with your software. If sharing an Apalache instance over the network is a common use case, then yes, a NixOS module would be appropriate. If individual users that work on verification projects are meant to spawn the server for their own work in isolation, and especially if configuration is scoped per-user, then home manager might be better. So, excuse my ignorance, and educate me which solution fits better :)

**Comment by JonathanLorimer** [comment]
> Fair. A hint in flake.nix would not impact other users and still help.

Oh yeah, I agree that a hint in `flake.nix` would be great

I am totally cool with a home-manager module. The distinction I am drawing is mostly an imaginary one. My thinking here is that home-manager is mainly for configuring a personal environment (what colorscheme do I use or something like that), whereas NixOS modules are more for system level software. For example I configure postgres (and other things like tailscale,  with NixOS modules, but only ever use it as a single user on my machine. I guess the advantage is that home-manager precludes a non-home-manager environment, whereas NixOS modules can be used in in home-manager environments or not.

**Comment by shonfeder** [comment]
Thanks very much for the contributions and packaging @lorenzleutgeb and @JonathanLorimer! This is great, and the team really appreciates it :)

(We were on an odd week last week, thus the slower reply here.)

**Comment by lorenzleutgeb** [comment]
Sure thing. I just PRed some improvements to the package for now. What's still open though is the question regarding the systemd service. Maybe you can clarify the usage-pattern for Apalache to help decide whether a system or user service should be preferred?
