### ISSUE TITLE
[FEATURE] Friendly assignment analysis

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#298]
The new `CoverAnalysisPass` produces extremely useful output about the state variables assigned in every operator. However, it is mostly unreadable on large examples:

```
TRUSTING_PERIOD covers: 
...
SwitchToPrimary covers: Faulty, blockchain, commonHeight, evidences, fetchedLightBlocks1, fetchedLightBlocks1b, fetchedLightBlocks2, lightBlockStatus1, lightBlockStatus1b, lightBlockStatus2, nextHeightToTry, now, state
Next covers: Faulty, blockchain, commonHeight, evidences, fetchedLightBlocks1, fetchedLightBlocks1b, fetchedLightBlocks2, lightBlockStatus1, lightBlockStatus1b, lightBlockStatus2, nextHeightToTry, now, state
TARGET_HEIGHT covers: 
...
```

(Note that `TRUSTING_PERIOD` and `TARGET_HEIGHT` are constants in this example, so the users are not interested in that output.)

Moreover, the users would not know what `cover` means and expect branch coverage, statement coverage, or similar.

A more informative output for the possible assignments may look like follows:

```
Foo.tla:200:8-200:75: SwitchToPrimary may update nextHeightToTry' 
Foo.tla:201:8-201:47: SwitchToPrimary may update state' 
Foo.tla:202:8-202:50: SwitchToPrimary may update blockchain' 
```

If you pad this info into three columns, that will be extremely useful to see, even if there are no bugs in the assignments.

**Comment by Kukovec** [comment]
Closed by #366.
