### ISSUE TITLE
[FEATURE] Checkpointing

### ISSUE THREAD

**Issue by lemmy** [informalsystems/apalache#300]
TLC can take checkpoints to pause and resume model-checking later (on other machines).  For models that take longer to check, it would be useful if Apalache had a similar feature.

**Comment by konnov** [comment]
This is in principle possible, but I am not sure about its value. Do you, whether anybody is using this feature nowadays?

**Comment by lemmy** [comment]
Yes, users still rely on this TLC feature and it would probably be even more useful if one could trigger a checkpoint dynamically.

**Comment by konnov** [comment]
I don't know how to do it in Apalache. Perhaps, virtualization tools could be of help here.
