### ISSUE TITLE
[FEATURE] Remove unused definitions in the early stages of preprocessing

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#310]
Since the [community modules](https://github.com/tlaplus/CommunityModules) are growing, it may happen that we would not be able to handle some of the operators, even though they are actually not used in a spec, but merely imported via `EXTENDS`. Hence, we should perform a simple recursive use analysis from `Init`, `Next`, `Inv`, and other relevant operators and prune the unused operators.

**Comment by Kukovec** [comment]
You can use `DependencyGraph` from the types branch to check this. If it's a root in the forest it is not called inside `Init` or `Next`

**Comment by konnov** [comment]
Inline pass removes unused operators.
