### ISSUE TITLE
[BUG] Inlining over the boundaries of recursive functions

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#313]
This issue demonstrates a minimal working example that pops up in #297 after the fixes.

```tla
----------------- MODULE Rec13 ----------------------                           
EXTENDS Integers

VARIABLE y

LOCAL Send[x \in { 1, 2}] ==
    x \* at this point, we expect x = 2, not x = 1

SendAll(x) == Send[x + 1]

Init == y = SendAll(1)

Next == UNCHANGED y

Inv == y = 2
=====================================================
```

Here is the result of inlining, which is obviously broken:

```tla
----- MODULE Rec13 -----                                                        
VARIABLE y

Init ==
  y = LET Send == [ 1 \in { 1, 2 } |-> 1 ] IN [ x \in { 1, 2 } |-> x ][(1 + 1)]

Next == UNCHANGED y

Inv == y = 2
===============
```

I suspect that `Inliner` does not take into account the parameter definitions inside `TlaFunOper.recFunDef`. Instead, it erroneously propagates `1` from the upper call.

**Comment by Kukovec** [comment]
I don't know what part of this spec is recursive, but I'd wager the real problem is inlining not working with global function domains.

**Comment by Kukovec** [comment]
As in, they are treated as expressions to be inlined, instead of a special kind of formal parameters.

**Comment by konnov** [comment]
Internally, `Send` is translated into `recFunDef`. It just happens never use `recFunRef` in the body.
