### ISSUE TITLE
[FEATURE] Add support for Seq

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#314]
At the moment, Apalache does not translate the `Seq` operator. We should add support similar to TLC. Given an option or a predefined operator that encodes the bound on the length of sequences, we can produce the set of all sequences up to that length.

**Comment by lemmy** [comment]
Perhaps relevant: https://github.com/tlaplus/CommunityModules/blob/2ebcbd910bcf5a2cc7f62cdb3a11c9e2f2d15641/modules/SequencesExt.tla#L47-L59

**Comment by konnov** [comment]
This is discussed in: https://apalache.informal.systems/docs/apalache/known-issues.html#using-seqs
