### ISSUE TITLE
Feature FAF: Stabilizing the assignment finder

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#353]
This is a meta-issue that summarizes the work to be done to stabilize the assignment finder. All issues for this feature are labeled with [FAF](https://github.com/informalsystems/apalache/issues?q=is%3Aopen+is%3Aissue+label%3AFAF).

As the assignment finder is one of the key preprocessing steps, we have to finally stabilize it and test rigorously.

 - [x] A much simpler approach to finding assignments without SMT: #366
 - [x] A manual chapter: #368 
 - [x] A tutorial #369

**Comment by konnov** [comment]
Just a note on the tutorial. I don't think that a video would be a good idea, as we would have to record the video once again when we change the command options or the tool output. Text tutorials are much easier to change in this respect.

**Comment by konnov** [comment]
@Kukovec I guess, we can finally close this one, right?

**Comment by Kukovec** [comment]
I guess so.
