### ISSUE TITLE
Feature FARR: new SMT encoding with arrays

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#360]
This is a meta-issue on implementing a new SMT encoding that efficiently uses arrays. All issues in this feature are labeled with FARR.

**Comment by rodrigo7491** [comment]
The initial idea is to have an alternative SMT encoding using arrays as an experimental feature, enabled under a CLI option.

- [ ] Write an ADR to describe the new encoding
- [ ] Add `encoding` option to CLI `check` command
- [ ] Replace uninterpreted functions by arrays in the encoding of KerA+ sets into SMT formulas

**Comment by rodrigo7491** [comment]
@konnov after #2549 is merged, only #1589 will remain open. Should we close this issue?

**Comment by konnov** [comment]
Yes, definitely!
