### ISSUE TITLE
Feature FTI: Type inferer testing and integration

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#362]
This is a meta-issue on documenting the type checker. All issues in this feature are labeled with FTI.

The [TLAPS](https://tla.msr-inria.inria.fr/tlaps/content/Home.html) developers would like to use our type inference.

**Motivation**: The model checker runs its own type inference on the preprocessed code. In many cases, it requires additional annotations of the TLA+ code. Most importantly, the users fail to understand, where and how they should introduce annotations. This process is tedious and frustrating. In this feature, we integrate the types produced by the new type checker/type inferer into the model checker.

**Comment by Kukovec** [comment]
We've agreed to abandon type inference in favor of type-checking.
