### ISSUE TITLE
[FEATURE] Clean up deprecated assignment-solver infrastructure

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#367]
The assignment rework #366 makes a lot of code, that was previously used to generate or interact with SMT encodings, as well as `CoverAnalysisPass` and the like redundant. This unused code should be removed.

**Comment by konnov** [comment]
Shall we remove it, or shall we isolate it in a clearly-marked package, like `assignments.old`. We might want to use the code in the future.

**Comment by shonfeder** [comment]
IMO, we shouldn't keep dead code around in files in the working tree. The code is available in the git history if we want to retrieve it.

However, if what we want is to potentially *use* that code, the I'd recommend adding a feature flag that lets one use the old assignment solver, which can be marked as deprecated.

This may be the most sustainable way to make the transition in any case :)

**Comment by konnov** [comment]
Ok. How about tagging the commit that comes right before #366 ? I just don't want to lose the previous solution by Jure, even if we don't know how to fix it now.

**Comment by shonfeder** [comment]
Sounds good to me.

**Comment by konnov** [comment]
We should remove the old code. As the type integration showed, we don't want to have too much unsupported code lying around.
