### ISSUE TITLE
[FEATURE] Tutorial on assignments

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#369]
We need a short tutorial on how Apalache finds assignments. Describe when it finds assignments and when it does not.

Introduce one in `doc/tutorials`?

**Comment by konnov** [comment]
@Kukovec what is the status of that? Do we still need a tutorial?

**Comment by Kukovec** [comment]
I guess #428 covers this, so we probably don't need an additional tutorial.

**Comment by konnov** [comment]
I agree it is detailed enough. Maybe, it is not exactly a tutorial, but it gives an explanation.
