### ISSUE TITLE
[BUG] Docker shell is suboptimal

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#372]
Reported at https://github.com/informalsystems/apalache/issues/207#issuecomment-740794043:

- Make bash the default shell
- Add a user, instead of running as root

**Comment by konnov** [comment]
Shall we de-prioritize this one, since docker is now optional?

**Comment by shonfeder** [comment]
Yeah, let's. I'm actually not clear on the benefits of changing either of things either.

If someone cares enough to comment on this issue to help motivate the change, we can reopen.
