### ISSUE TITLE
Feature FMBT: Support for model-based testing

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#379]
Model-based Testing v0.1 should include a runnable, user-friendly way of translating an Apalache counterexample into an integration test for Tendermint in Rust LightClient.

@andrey-kuprianov is our internal customer for this feature.

**Comment by konnov** [comment]
@andrey-kuprianov is it still relevant? You are doing all of it now.

**Comment by andrey-kuprianov** [comment]
yes, this can be considered implemented. closing it
