### ISSUE TITLE
[FEATURE] Document how to run the jar directly

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#395]
This is to provide an easy, cross-platform solution for users who are comfortable with the jvm. It may also help peel back some of the magic for prospective developers.

**Comment by konnov** [comment]
Added directly in https://github.com/informalsystems/apalache/pull/400

**Comment by konnov** [comment]
This needs a fix: use `java -jar` instead of `java -cp`. Also installing OpenJDK is tough. We should point to https://adoptopenjdk.net/

**Comment by lemmy** [comment]
FWIW: On Linux, one can simply run TLC with `./tla2tools.jar SomeSpec` because the system uses some clever trick.  I've always assumed the same could be possible on macOS.

**Comment by konnov** [comment]
It does not seem to work on MacOS. But we are actually more concerned about Windows, as `apalache-mc` works both on Linux and MacOS. For the moment, Windows users have to run java directly.
