### ISSUE TITLE
[FEATURE] Package for homebrew

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#397]
Towards #159.

Add the brew formula to our https://github.com/informalsystems/homebrew-pkgs

**Comment by shonfeder** [comment]
Igor suggested looking at jpackage: https://github.com/informalsystems/apalache/pull/1700#pullrequestreview-958831981

**Comment by thpani** [comment]
I think we've stepped away from the idea of maintaining OS-specific packages.
If we want to, [Coursier](https://get-coursier.io/) may be a good, OS-agnostic, Scala-specific option.
