### ISSUE TITLE
[FEATURE] Package for ubuntu

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#398]
Towards #159

**Comment by shonfeder** [comment]
Igor suggested looking at jpackage: https://github.com/informalsystems/apalache/pull/1700#pullrequestreview-958831981

**Comment by shonfeder** [comment]
@bugarela suggested we provide a snap, rather than fussing with apt. I think this is a good idea. See https://ubuntu.com/tutorials/create-your-first-snap#1-overview

**Comment by thpani** [comment]
I think we've stepped away from the idea of maintaining OS-specific packages.
If we want to, [Coursier](https://get-coursier.io/) may be a good, OS-agnostic, Scala-specific option.

See also #397.
