### ISSUE TITLE
[FEATURE] Turn manuals into books with mdbook

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#399]
It would be nice to turn [Apalache manual](https://github.com/informalsystems/apalache/blob/unstable/docs/manual.md), [Idiomatic TLA+](https://github.com/informalsystems/apalache/tree/unstable/docs/idiomatic) and [Language manual](https://github.com/informalsystems/apalache/tree/unstable/docs/lang) into books by running [mdbook](https://github.com/rust-lang/mdBook)

**Comment by shonfeder** [comment]
There are lots of options for generating documentation from markdown.  Should we perhaps survey what's available and what features they offer before picking one? 

E.g., (just the first answers in a google search):

- https://www.mkdocs.org/
- https://docsify.js.org/#/
- https://docusaurus.io/
- https://dotnet.github.io/docfx/

**Comment by shonfeder** [comment]
Nevermind my last comment. MD book looks good.
