### ISSUE TITLE
[FEATURE] Deploy the latest stable version of the docs separately

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#402]
As a followup to #400, we should also build and deploy and unstable version of the documentation.

(At some future point, we'll want to keep different versions of the manual available for different versions, but I think that's overkill before we are at major versions).

**Comment by konnov** [comment]
I thought that one has been solved already. If so, shall we close it?

**Comment by shonfeder** [comment]
The idea here was that we'd build and deploy two different versions of the docs: one for the latest stable release, and one that follows our trunk, and is updated continuously.

**Comment by thpani** [comment]
Since we're regularly cutting releases, in particular for breaking changes, and Apalache has reasonably matured, this does not seem to be an issue. Closing as wontfix for now.
