### ISSUE TITLE
[FEATURE] Include a simple TLA+ benchmark in a release

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#410]
Currently, the zip/tgz file contains only `apalache-mc` and the distribution jar.

**Comment by shonfeder** [comment]
I don't understand the motive for this. As a user, why would I want my release package to include stuff that seems to only be relevant for development? Or is this rather saying to include tools for users to run benchmarks on their own specs?

**Comment by konnov** [comment]
What I meant is that we need at least one TLA+ file in the distribution, so the users could quickly test, whether the tool is working at all

**Comment by konnov** [comment]
on related note, maybe we also have to include `Apalache.tla` and `Typing.tla`

**Comment by shonfeder** [comment]
We have CI to test that we are releasing working artifacts, no? Bundling specs with the release just we can test the thing we're testing in CI actually works doesn't seem very clean to me. Is this done in some other mature software deployments to your knowledge?

As an alternative, we could supply a simple curl command that would let users pull down an example spec and run it locally. This would seem to be a better separation of concerns IMO.

**Comment by shonfeder** [comment]
> on related note, maybe we also have to include `Apalache.tla` and `Typing.tla`

Oh yes! If we're not we should. Those are part of the release, right? :D

**Comment by konnov** [comment]
Apparently, we did not include them in the jar file :(

**Comment by lemmy** [comment]
As inspiration: TLC has a little known feature that a spec & model files can be dropped into a special package of the jar file where TLC will find it.  In other words, it loads the spec & model from its own jar.

**Comment by konnov** [comment]
Yes, since we are using SANY, the same should work for Apalache.

**Comment by konnov** [comment]
This does not seem to be in demand.
