### ISSUE TITLE
Feature FSE: Symbolic execution

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#445]
This is a meta-issue for symbolic execution.

The old version of Apalache supported what people usually understood by symbolic execution: collect a symbolic path and fork new search in case of branching. Although we have never emphasized that, the versions prior to 0.8.1 had the flag `--search=dfs`. Moreover, this search could be randomized with `--randomizeDfs`.

The new implementation does not support this anymore, but it is very easy to recover this feature with the new transition architecture. If you need this feature, please let us know.

**Comment by konnov** [comment]
@andrey-kuprianov do you need this for model-based testing? I realized that we killed this feature.

**Comment by konnov** [comment]
This should not be a lot of work. We should prioritize it for February.

**Comment by andrey-kuprianov** [comment]
yes, would be very-very valuable for model-based testing; see #79

**Comment by konnov** [comment]
These are two different issues: symbolic execution lets us enumerate different symbolic paths and produce one example per execution, whereas #79 would allow us to produce different examples along the same path. But yes, they are related.

**Comment by konnov** [comment]
@andrey-kuprianov please upvote the issue then :)

**Comment by konnov** [comment]
This feature seems to be less demanded than #542

**Comment by konnov** [comment]
We kind of implemented similar functionality with `simulate`. Closing this one.
