### ISSUE TITLE
[FEATURE] Automatically update the website links to the package downloads

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#477]
Because we stick the version number in the packages, we can't take advantage of GitHub's `download/latest` link, and need to update the links on the website each time we cut a new release. So we need to either

- Stop including the version number in the compressed package names
- Automate updating the website link as part of our CI process

**Comment by konnov** [comment]
I would prefer to keep the version number in the distribution package.

**Comment by thpani** [comment]
Closed in #722
