### ISSUE TITLE
[FEATURE] Add syntax highlighting to manual

### ISSUE THREAD

**Issue by Alexander-N** [informalsystems/apalache#478]
While mdbook is nice, one disadvantage compared to the markdown display on github is that the TLA+ syntax highlighting is lost.

This might not be possible without a 3rd party plugin to highlight.js, some previous work is at https://github.com/highlightjs/highlight.js/pull/1658

**Comment by konnov** [comment]
Good point. I am copying the text of #403 and closing #403:

@shonfeder:
> A followup to #400.
> 
> Currently I don't see any off-the shelf way of generating this, but perhaps github shares the code they use for this? To be investigated.

**Comment by konnov** [comment]
Shall we re-evaluate this issue, since the [new tutorial](https://apalache.informal.systems/docs/tutorials/entry-tutorial.html) contains plenty of code snippets.

**Comment by thpani** [comment]
I played around a bit with mdbook today, and I think I figured out how hook up the highlighting file from https://github.com/highlightjs/highlight.js/pull/1658.
@shonfeder You're assigned here, do you want to sync or would you mind if I take this one?

**Comment by shonfeder** [comment]
You’re welcome to take it on! I haven’t looked into it all. But let me know if you’d rather explain the approach and have me to implement it when I have time :)
