### ISSUE TITLE
[BUG] Emojis are not displayed in the manual

### ISSUE THREAD

**Issue by Alexander-N** [informalsystems/apalache#479]
The github emojis are not displayed in the mdbook manual, for example in https://apalache.informal.systems/docs/lang/index.html there are only the text representations like `:electric_plug:` and `:bulb:`. Maybe they could simply be replaced with unicode characters?

**Comment by konnov** [comment]
Good point. We started to use mdbook recently, and this issue has not been resolved yet.

**Comment by shonfeder** [comment]
mdBook has a pending issue to include this in their compilation (https://github.com/rust-lang/mdBook/issues/771), but it should be easy for us to add a preprocessor in the emantime.

**Comment by shonfeder** [comment]
I'm nearly done with a sustainable fix for this (have been noodling on it as a side project off hours).
