### ISSUE TITLE
[BUG] 0.8.2 ZIP distribution is broken

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/apalache#500]
**The archive structure of apalache-v.0.8.2.zip is broken**

instead of `mod-distribution` it contains `/home/runner/work/apalache/apalache/mod-distribution/`

**To Reproduce**

Download from https://github.com/informalsystems/apalache/releases

**Comment by konnov** [comment]
@shonfeder , could you have a look? I guess it is an artifact of the automatic release process.

**Comment by shonfeder** [comment]
Whoop, I was checking the tar.

**Comment by shonfeder** [comment]
Thanks for the report, @andrey-kuprianov. the workaround for the time being is to use the tgz: https://github.com/informalsystems/apalache/releases/download/v0.8.2/apalache-v0.8.2.tgz
