### ISSUE TITLE
[FEATURE] Run formatting in pre-commit hooks

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#515]
Followup to #492

**Comment by konnov** [comment]
Yes. Let's do it. There is no point of doing it by hand, if the github action is rejecting the otherwise formatted code anyway.

**Comment by konnov** [comment]
Is it still an issue, or we are happy about our editors running `scalafmt`?

**Comment by shonfeder** [comment]
If you're happy with your editors, I say we close this. It'll add a few seconds to every commit and if some individual wants such hooks later they can write it themselves and share it in the repo for others to enable if they wish.
