### ISSUE TITLE
Improve JSON format for counterexamples

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/apalache#530]
The current JSON format for counterexamples follows the general TLA+ to JSON formatting of Apalache. As correctly pointed out by @vitorenesduarte, counterexamples have much simpler structure than the general TLA+ -- only ground formulas. So the facilities provided by JSON (maps and arrays) should be essentially enough to represent everything needed, without the special syntax.

It would be nice to implement this specialised syntax for counterexamples -- this would simplify the task of integrating with Apalache and counterexample parsing substantially.

**Comment by konnov** [comment]
Yes. It would be a nice feature. Let's discuss at the planning meeting when we like to schedule some work on it.

**Comment by konnov** [comment]
Shall we produce the same JSON structure as TLC: https://github.com/tlaplus/CommunityModules/blob/master/modules/Json.tla

**Comment by konnov** [comment]
Following the discussion in #599, that does not look like a priority any longer. Do you still want it implemented in Apalache or shall we close the issue?

**Comment by andrey-kuprianov** [comment]
I think for usability it would be still nice to generate JSON counterexamples directly from Apalache. But taking into account that there is a workaround present, it becomes less urgent, so let's move this issue to a backlog, may be.

**Comment by konnov** [comment]
If there is a need for this, we could implement a simplifier in an external script, e.g., in python. However, since JSON is not human-readable, I do not see value in supporting two formats. It only can lead to more bugs.

**Comment by konnov** [comment]
I have reopened the issue. In the hindsight, it is actually an important issue. It will let us to decouple testing tools from Apalache/TLC.

**Comment by konnov** [comment]
This is done: https://apalache.informal.systems/docs/adr/015adr-trace.html
