### ISSUE TITLE
[FEATURE] Evaluate switching build systems

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#549]
Maven causes us a fair bit of pain (from the slow, non-incremental builds, to the noisy output, to the verbose and unchecked XML config files). We might consider switching to a more advanced build system. Options to evaluate:

- SBT: standard in scala community, highly configurable, incremental builds
- Gradel: noted for being fast, support native compilation, incremental builds, build caches
- Bazel: multi-language, blazingly fast, incremental and cloud builds, could replace all of our use of make (including the benchmarks)

Each has tradeoffs, so in evaluating whether we should switch we should also evaluate which to switch to.

**Comment by konnov** [comment]
One point to take into account. We should evaluate how much bootstrapping these tools require, if a new user wants to use them to build apalache.

**Comment by shonfeder** [comment]
In our standup today yesterday and today we decided it was worth attempting a switch to SBT.

While Gradle and Bazel both have some notable benefits, they were much more appealing when we were still building a custom Z3. Now that our only dependencies are JVM based, the simplicity and ubiquity off SBT (for Scala projects) seems to recommend it.

I am going to spend up to 1 day of work on this to get a sense for how involved it will be to make the switch.

I'll do the timeboxed work on SBT under this ticket, as it is technically part of evaluation.
