### ISSUE TITLE
[FEATURE] Rewrite TestIDAllocation and remove TlaSpec

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#572]
The tests in `TestIDAllocation` were created in 2016. Instead of using `assert`, they are using print statements. Let's fix this zombie test.

Also, use `TlaModule` instead of `TlaSpec`. When it's done, remove `TlaSpec`.

**Comment by Kukovec** [comment]
Hmm, looking at it, `TestIDAllocation` doesn't actually have any tests, it's just leftover code from the very first time we attached UIDs to expressions. Printing, at the time, would display `(ex, UID)`, and I guess this file ran a bunch of specs for visual inspection. My suggestion is just deleting the lot, there's really no added value to this "test" file.
