### ISSUE TITLE
Parsed spec replaces standard module operators with `true`

### ISSUE THREAD

**Issue by yagehu** [informalsystems/apalache#595]
I'm using Apalache to parse TLA+ specs with the `parse` command and the `--output` option to obtain a JSON syntax tree for further processing. However, it seems that built-in standard module operators like `Len` and `Seq` all turns into `true` in the output JSON.

Here's a minimal example:

```
---- MODULE Spec ----
EXTENDS Sequences

VARIABLE
    state

Init == state = <<>>

Next == Len(state) = 0 /\ state' = <<1>>

Spec == Init /\ [][Next]_state
====
```

Gets parsed into:

```
{
  "module": "Spec",
  "declarations": [
    {
      "variable": "state"
    },
    {
		// snip
    },
    {
      "operator": "Next",
      "body": {
        "and": [
          {
            "eq": true,    <---------------!!!
            "arg": 0
          },
          {
            "eq": {
              "prime": "state"
            },
            "arg": {
              "tuple": [
                1
              ]
            }
          }
        ]
      },
      "params": [
        
      ]
    },
    {
		// snip
    }
  ]
}
```

My questions are:

1. Am I abusing the parse command? My goal is to get a syntax tree of a TLA+ spec.
2. Do you have any suggestions? Should I write my program in a JVM language and integrate directly with SANY?

**Comment by konnov** [comment]
Hi @yagehu! Thank you for the report. You have a totally valid use case of json, which we also had in mind. That must be a bug in the JSON writer.  We will have a look.

**Comment by konnov** [comment]
As for integrating with SANY, this is always an option. However, in my experience, dealing with `SemanticNode` of SANY is not easy. What your use case?

**Comment by yagehu** [comment]
My use case is analyzing TLA+ specs and generate tests for a piece of software. I'm aware of the model-based testing you've done with Apalache. AFAIK it involves writing a test spec in which each TLA+ declaration is a test case.

I'm investigating if it's possible to generate tests without having to write these test cases in a test spec. I'm only interested in testing each state transition as opposed to the integration tests generated from your MBT work.

I just learned from #598 and #125 that there's an Apalache IR. Does Apalache expose an API for working with it? I'm guessing I have to use Scala or some other JVM language?

**Comment by konnov** [comment]
Cool! We are happy to help, if you like to integrate with Apalache. As you have seen, we are going to reimplement the JSON writer in #598. Feel free to give us feedback on the format.

As for IR, we kept it simple. You can find all the related classes in the package [`at.forsyte.apalache.tla.lir`](https://github.com/informalsystems/apalache/tree/unstable/tlair/src/main/scala/at/forsyte/apalache/tla/lir). The core classes can be found in [`TlaEx`](https://github.com/informalsystems/apalache/blob/unstable/tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaEx.scala), [`TlaDecl`](https://github.com/informalsystems/apalache/blob/unstable/tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaDecl.scala), [`TlaValue`](https://github.com/informalsystems/apalache/blob/unstable/tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaValue.scala). The standard operators are defined in [`at.forsyte.apalache.tla.lir.oper`](https://github.com/informalsystems/apalache/tree/unstable/tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper).

If you like to download stable jars from maven central, please let us know. For the moment, you can download one of the [release packages](https://github.com/informalsystems/apalache/releases). It should be possible to use Scala classes in JVM, though it may require some conversions, e.g., here is a [Stackoverflow discussion](https://stackoverflow.com/questions/48619101/how-to-bridge-scala-case-classes-and-collections-to-java). So using the JSON output is probably the easiest approach.

**Comment by lemmy** [comment]
FWIW: SANY has an XML exporter that a postdoc spent quality time on and that was meant to replace TLAPS' own TLA+ parser.

**Comment by konnov** [comment]
Ho @yagehu. We have completely reimplemented the JSON parser and writer. It's documented in https://apalache.informal.systems/docs/adr/005adr-json.html. If it is still relevant to you, give it a try.

**Comment by konnov** [comment]
There is no progress on this issue. Closing it.
