### ISSUE TITLE
[FEATURE] New Json format

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#598]
Apalache's current Json output format is a) not well documented, b) fairly ad hoc, and c) incomplete (see #595).
We should implement a more standardized json output format, which mirrors the internal representation.

**Comment by konnov** [comment]
The idea is to:

- use a standard JSON serializers of our IR, e.g., https://circe.github.io/circe/codec.html
- By documenting our IR once, we can simply map it to different formats, e.g., JSON, XML, S-expressions, without the need for documenting the format multiple times.

**Comment by shonfeder** [comment]
As per discussion in slack, @andrey-kuprianov is OK with this change, and doesn't require any backward compatibility support, even for a limited time. He will just pin to the version they need until they have time to update their handling of the JSON format.
