### ISSUE TITLE
How to model state that can be Const or Int?

### ISSUE THREAD

**Issue by yagehu** [informalsystems/apalache#600]
This spec fails `apalache check` due to type errors:

```
---- MODULE Spec ----
EXTENDS Naturals

CONSTANT Null, Unspecified

VARIABLE exitCode

ExitCodes == { Null, Unspecified } \union Nat

Init == exitCode = Null

Next ==
    /\ exitCode = Null
    /\ exitCode' = 1

Spec == Init /\ [][Next]_exitCode

TypeOk == exitCode \in ExitCodes
====
```

```
Step 0, level 0: checking if 1 transition(s) are enabled and violate the invariant I@07:14:54.383
Spec.tla:18:24-18:32, \union(...), type error: Unexpected types for \union: FinSet[Const], InfSet[Int] E@07:14:54.457
Spec.tla:18:11-18:32, \in(...), type error: Unexpected types for \in: Const, Unknown E@07:14:54.458
<unknown origin>, ~(...), type error: Expected type Bool, found Unknown E@07:14:54.460
```

I'm relatively new to TLA+. How would I model a state/value that can be either an `Int` or a `Const` model value if I want to use Apalache? I understand that TLC imposes no such restrictions but Apalache requires elements of a set be the same type.

In this contrived example, `ExitCodes` is a set of possible exit codes of a program, which can be `Null`, `Unspecified`, or some integer.

**Comment by konnov** [comment]
There are three answers to your question. The general answer is that you can wrap values of different types in records. This is similar to unions in C and algebraic datatypes in functional languages:

```tla
---- MODULE Spec2 ----
EXTENDS Integers

\* old apalache type annotations, see:
\* https://apalache.informal.systems/docs/apalache/types-and-annotations.html
a <: b == a

CodeType == [ type |-> STRING, value |-> Int ]

\* note that the type annotations will change very soon (February or March):
\* https://apalache.informal.systems/docs/HOWTOs/howto-write-type-annotations.html

\* CONSTANT Null, Unspecified
Null == [ type |-> "Null" ] <: CodeType
Unspecified == [ type |-> "Unspecified" ] <: CodeType

VARIABLE exitCode

\*ExitCodes == { Null, Unspecified }
\*                \union OkExitCodes

Init == exitCode = Null

Next ==
    /\ exitCode = Null
    /\ exitCode' = [ type |-> "OK", value |-> 1 ]

Spec == Init /\ [][Next]_exitCode

TypeOk ==
    \* Apalache does not support finite sets of records yet.
    \* We can rewrite it like below. However, this would require
    \* a universal quantifier over an infinite set. Not yet supported.
    \* Instead we can access the record fields.
    \/ exitCode.type = "OK" /\ exitCode.value \in Nat
    \/ exitCode \in { Null, Unspecified }
====
```

Note that we annotate records with a record type that has all potential fields. In this case: `type` and `value`. This may change in the future, if we introduce a stricter approach to record types.

**Comment by konnov** [comment]
In your specific example, we can cheat a little bit and extend `exitCode` to integers, so the error codes would have negative values:

```tla
---- MODULE Spec ----
EXTENDS Integers

CONSTANT Null, Unspecified

VARIABLE exitCode

ConstInit ==
    /\ Null = -1
    /\ Unspecified = -2

ExitCodes == { Null, Unspecified } \union Nat

Init == exitCode = Null

Next ==
    /\ exitCode = Null
    /\ exitCode' = 1

Spec == Init /\ [][Next]_exitCode

\*TypeOk == exitCode \in ExitCodes
TypeOk == exitCode \in Nat \/ exitCode \in { Null, Unspecified }
====
```

In this case, we tell Apalache to use the constant initializer as follows:

```sh
apalache check --cinit=ConstInit --inv=TypeOk Spec.tla
```

**Comment by konnov** [comment]
Alternatively, we could define `Null` and `Unspecified` with operator definitions:

**Comment by konnov** [comment]
Finally, we have been integrating the new type checker for some time. It will take us a few weeks to finish this work. With the new type checker type annotations will be much easier to write:

```tla
---- MODULE Spec3 ----
EXTENDS Integers

\* using new apalache type annotations, see:
\* https://apalache.informal.systems/docs/HOWTOs/howto-write-type-annotations.html

\* CONSTANT Null, Unspecified
Null == [ type |-> "Null" ]
Unspecified == [ type |-> "Unspecified" ]

VARIABLE
    \* @type: [ type: Str, value: Int ];
    exitCode

Init == exitCode = Null

Next ==
    /\ exitCode = Null
    /\ exitCode' = [ type |-> "OK", value |-> 1 ]

Spec == Init /\ [][Next]_exitCode

TypeOk ==
    \* Apalache does not support finite sets of records yet.
    \* We can rewrite it like below. However, this would require
    \* a universal quantifier over an infinite set. Not yet supported.
    \/ exitCode.type = "OK" /\ exitCode.value \in Nat
    \/ exitCode \in { Null, Unspecified }
====
```

The model checker does not support yet the types that are inferred by the new type checker.

**Comment by yagehu** [comment]
Thanks for the detailed answer! However, this also fails due to:

```
Spec.tla:10:17-13:1: unexpected expression: STRING                E@03:33:04.863
Unexpected expressions in the specification (see the error messages) E@03:33:04.866
```

```
---- MODULE Spec ----
EXTENDS Integers

VARIABLE exitCode

a <: b == a

U32 == 0..15

TypeExitCode == [
    type  : STRING,
    value : U32
]

ExitCodeNull == [
    type |-> "Null",
    value |-> 0
] <: TypeExitCode
ExitCodeUnspecified == [
    type |-> "Unspecified",
    value |-> 0
] <: TypeExitCode

Init == exitCode = ExitCodeNull

Next ==
    /\ exitCode = ExitCodeNull
    /\ exitCode' = ExitCodeUnspecified

Spec == Init /\ [][Next]_exitCode

TypeOk == exitCode \in TypeExitCode
====
```

I tried replacing `STRING` with `{ "Ok", "Null", "Unspecified" }` but it still fails.

**Comment by konnov** [comment]
Here is how we can fix it:

```tla
---- MODULE Spec ----
EXTENDS Integers

VARIABLE exitCode

a <: b == a

TypeExitCode == [
    type  |-> STRING,
    value |-> Int
]

ExitCodeNull == [
    type |-> "Null",
    value |-> 0
] <: TypeExitCode
ExitCodeUnspecified == [
    type |-> "Unspecified",
    value |-> 0
] <: TypeExitCode

Init == exitCode = ExitCodeNull

Next ==
    /\ exitCode = ExitCodeNull
    /\ exitCode' = ExitCodeUnspecified

Spec == Init /\ [][Next]_exitCode

\*TypeOk == exitCode \in TypeExitCode

TypeOk == /\ exitCode.type \in {"Ok", "Null", "Unspecified"}
          /\ exitCode.value \in Int
====
```

**Comment by konnov** [comment]
I see where the confusion is coming from. Our old type annotations look a lot like the expressions that one would typically write in `TypeOK`. But they are not the same. `TypeOK` is basically the TLC way to check that the state variables have certain shape. Since this check is done dynamically, when TLC does state exploration, you can write virtually any predicate in `TypeOK`. In contrast, the type checker has to find types statically, and our type system is fairly simple.

We introduced the old type annotations a few years ago, when we felt it was a good idea to use TLA+ itself to express the types. However, that happened to be a very bad idea. For instance, your are trying to use `TypeExitCode` both as a type annotation and as a set of possible values. Some people also tried to use operators inside type annotations. So this old approach really has a lot of issues.

That is why we are now writing type annotations as strings that are parsed by a dedicated parser: https://apalache.informal.systems/docs/adr/002adr-types.html

**Comment by konnov** [comment]
@yagehu shall we close this issue?

**Comment by yagehu** [comment]
Closed. Thanks! Very helpful.
