### ISSUE TITLE
[FEATURE] Add type support for TLC!RandomElement

### ISSUE THREAD

**Issue by Isaac-DeFrain** [informalsystems/apalache#601]
I find myself using the RandomElement operator from the TLC module in several specs. It would be great to have Snowcat support typechecking when I use the TLC module in a spec.

**Comment by lemmy** [comment]
FWIW: Heavy use of `TLC!RandomElement` is considered a "code smell".

**Comment by Isaac-DeFrain** [comment]
Point taken.

Yes, I want to make (pseudo)random selections of peers to exchange messages with. I know I can override definitions with my own Java classes. Is there another, more accepted approach for achieving this goal?

**Comment by konnov** [comment]
That is easy. See #602. A few notes though:

1. `Any` and `TLCGet` return values of arbitrary types that are not related to the arguments at all, so the type checker will most likely complain there.
2. `Assert` is not well-typed by the definition. We force it to return `Bool`, but some existing TLA+ specs may fail on that.
