### ISSUE TITLE
LET-IN Branch Indistinguishability

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#62]
Currently, branches inside LET-IN assignments may not be reported as expected.
Consider the following:
```
LET X == a' = 1 : UID(u)
IN \/ X /\ A
   \/ X /\ B
```
Because assignments/branches are found based on UIDs, branches of the disjuncts `X /\ A` and `X /\ B` are indistinguishable, in the sense that they intersect the set `{u}` in the same way (assuming no assignments in `A` or `B`). Consequently, slices of the formula would contain either both disjuncts or neither.

Fundamentally, the `\/`-invariant - that at most one branch of a sub-term intersects any given assignment selection - does not hold under LET-IN assignment.

We need to rethink assignment strategies/branches/slicing if LET-IN operators may contain assignments.

**Comment by Kukovec** [comment]
This is not really a bug, but more of an issue with expectations. Additionally, there's no problem from a correctness perspective. The only downside is that there are now potentially fewer symbolic transitions (i.e. 2 or more of what would previously have been separate transitions now come merged), which might be slower (though unlikely by any OOM).

**Comment by konnov** [comment]
Well, it is true, that in this case it should not hurt. However, this is counterintuitive.

**Comment by konnov** [comment]
Shall we closed it as a result of #366?

**Comment by Kukovec** [comment]
Yes
