### ISSUE TITLE
[FEATURE] Introduce generators of data structures

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#622]
This is a first step towards the command `test`, which was requested in #191. We can start working on this feature when the integration of the type checker is over, see #350. To improve the quality of the produced values, we probably have to solve #401, but this is not a prerequisite for this feature.

It often happens that I want to quickly test an operator definition that I have written. The only way to do it with Apalache and TLC is to write a specialized version of `TypeOK` for the operator parameters and state variables and then run the model checker, to produce a counterexample that serves as an example of one computation of the operator. This is quite cumbersome. Moreover, `TypeOK` is usually written in the general form, so it can produce quite large data structures. As a result, it may be hard for TLC and Apalache to find small examples.

TLC offers partial remedies to this problem by allowing the user to override operator definitions. For instance, it is quite common to override the definition of `Seq(S)`. Also, one can also evaluate constant expressions in the [VSCode plugin for TLA+](https://marketplace.visualstudio.com/items?itemName=alygin.vscode-tlaplus). However, it all feels like higher-order magic for the ultimate experts of TLA+.

**Our solution.** We can borrow the idea of generators from property-based testing. (For example, here is a high-level [intro in PBT](https://medium.com/criteo-engineering/introduction-to-property-based-testing-f5236229d237).) For instance, this is how we could generate a set of integers that contains up to 10 elements, and then test, whether the produced set contains the constant 3:

```tla
Test1 ==
  LET \* @type: Set(Int);
          set == Gen(10) IN
  3 \in set
```

By expanding on this idea, we could generate a function of integers to Booleans such that the function's domain contains at most 10 elements:

```tla
Test2 ==
  LET \* @type: Int -> Bool;
         f == Gen(10) IN
  \* we can add constraints on the generated data
  /\ 1 \in DOMAIN f => f[1] = 2
  /\ 3 \in DOMAIN f => f[2] = 3
  \* here is what we want to test
  /\ {1, 3} \in DOMAIN f => f[1] + f[3] > 0
```

**How will it work?** The idea is quite simple. We introduce the operator `Gen` that produces values of arbitrary types, by taking into account an upper bound on the number of the elements in every composite data structure. Hence, `Gen` has the type `Int => a`. By annotating a LET-definition as in the examples above, we tell the model checker the type of the value to be generated.

The model checker will have generators for all data types. For instance, to produce a set that contains up to 10 values, the model checker would generate 10 values of the set element type and leave it to the SMT solver to decide which of these values actually belong to the set. All ten values will be registered in the model checker's memory arena as potential values for the set.

Obviously, we don't need any PBT-like "properties" in TLA+, as we have the whole logic to write the properties.

**Comment by lemmy** [comment]
It sounds to me as if `Gen` is an operator that is related to [`Randomization.tla`](https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/src/tla2sany/StandardModules/Randomization.tla).  What about adding it to `Randomization` with the type made an argument of `Gen`, i.e. `Gen(10, "Set(Int)")`.

**Comment by konnov** [comment]
It is true that generators in PBT are usually random. But we have the whole SMT solver. Why should we do random things?

**Comment by konnov** [comment]
What I had in mind is #717
