### ISSUE TITLE
[FEATURE] An integer variable as the tuple argument

### ISSUE THREAD

**Issue by banhday** [informalsystems/apalache#637]
Reported: Expected an integer constant as the tuple argument. 
Reason: MySeq is a sequence, and argument k is a variable.

```tla
MySeq == << 1, 2, 3 >>

VARIABLE s

Init == s = << >>

Next == 
  /\ \A k \in DOMAIN MySeq : MySeq[k] < 4
  /\ s' = << 3 >>
```

With APALACHE version 0.11.1-SNAPSHOT

**Comment by konnov** [comment]
Well, Apalache does not know that you like to treat the tuple `MySeq` as a sequence. You would have to give it a type annotation, e.g., `<< >> <: Seq(Int)`. Note though that type annotations will change very soon to the new ones: https://apalache.informal.systems/docs/apalache/typechecker-snowcat.html

**Comment by banhday** [comment]
I see. We should mention that APALACHE prefers tuples to records. They are common data structures and have the same syntax. However, I think that records are used more frequently than tuples.

**Comment by konnov** [comment]
We can solve the problem by using annotations:

```
MySeq == << 1, 2, 3 >> <: Seq(Int)

VARIABLE s

Init == s = << >> <: Seq(Int)

Next == 
  /\ \A k \in DOMAIN MySeq : MySeq[k] < 4
  /\ s' = << 3 >> <: Seq(Int)
```
