### ISSUE TITLE
[FEATURE] Printing record types

### ISSUE THREAD

**Issue by banhday** [informalsystems/apalache#638]
The syntax of type annotations for records is [f_1 |-> T_1, ..., f_k |-> T_k]. However, when APALACHE cannot unify types of records, it currently prints ["f_1" -> T_1, ..., "f_k" -> T_k].

With APALACHE version 0.11.1-SNAPSHOT

**Comment by konnov** [comment]
I agree it is annoying. We will use new type annotations very soon: https://apalache.informal.systems/docs/apalache/typechecker-snowcat.html
