### ISSUE TITLE
[BUG] Disabled transitions in a specification of the algorithm Skeen

### ISSUE THREAD

**Issue by banhday** [informalsystems/apalache#639]
**Describe the bug**
This specification ([link](https://github.com/banhday/multicast-algorithms/tree/main/Skeen3_disable_symbolic_transitions)) is about the multicast algorithm Skeen with 3 processes and 3 multicast messages. TLC generated about 195K distinct states to check three properties AsymDeliveryOrder, DeliveryOrder, and GlobalTotalDeliveryOrder, and did not find any counterexamples. However, APALACHE showed only that transitions were disabled in the first four steps. I didn't figure out why it happened.

Moreover, at step 5, APALACHE showed an error message about "Expected a constant integer range in ..". However, I don't think that it is a reason for disabled transitions.

**To Reproduce**
Run the command: apalache-mc check --length=10 Skeen3_disable_symbolic_transitions.tla 

**Desktop (please complete the following information):**
 - With APALACHE version 0.11.1-SNAPSHOT

**Comment by konnov** [comment]
Resolved over zoom. Changed the spec to avoid introducing a dynamic range
