### ISSUE TITLE
[BUG] Errors in rewriting another specification of Skeen

### ISSUE THREAD

**Issue by banhday** [informalsystems/apalache#640]
**Describe the bug**
This [link](https://github.com/banhday/multicast-algorithms/tree/main/Skeen3_bugs_in_reduction_rules)  is another specification of the algorithm Skeen. This specification is very similar to one in #639 . The difference is the way I wrote type annotations for empty sequences and empty sets in Init. For example, here I wrote 
```tla
rcvdMcastID = [p \in Proc |-> {} ] <: [ Int -> {Int} ]
```
and in the spec in #639 , I wrote 
```tla
rcvdMcastID = [p \in Proc |-> ({} <: {Int})]
```
When checking this specification with APALACHE, I received an error message about rewriting steps.

**To Reproduce**
Run the command: apalache-mc check --length=10 Skeen3_bugs_in_reduction_rules.tla 

**Desktop:**
 - With APALACHE version 0.11.1-SNAPSHOT

**Comment by konnov** [comment]
The issue is with the old type annotations. The first annotation should look like:

```tla
rcvdMcastID = [p \in Proc |-> {} <: {Int} ]
```
