### ISSUE TITLE
[BUG] RewriterException for Variation of Bakery

### ISSUE THREAD

**Issue by leuschel** [informalsystems/apalache#672]
Running 
```
java -jar apalache-pkg-0.8.0-RELEASE-full.jar check --init=Init  --inv=Inv --length=5 Apalache/Bakery-Inductive/Bakery.tla
```
on a small variation of the Bakery.tla example produces this error message:
```
The problem occurs around the source location Bakery.tla:176:24-179:58 E@18:47:09.094
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],at.forsyte.apalache.tla.bmcmt.RewriterException: SubstRule: Variable nxt' is not assigned a value)
<unknown>: rewriter error: SubstRule: Variable nxt' is not assigned a value E@18:47:09.107
at.forsyte.apalache.tla.bmcmt.RewriterException: SubstRule: Variable nxt' is not assigned a value
	at at.forsyte.apalache.tla.bmcmt.rules.SubstRule.apply(SubstRule.scala:30)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:325)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:374)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:383)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:405)
```

The location of the file is artifact/scripts/ind_inv/exp/001/
Github does not allow me to attach the file.
Apalache was run on macOS big Sur.

**Comment by konnov** [comment]
Hi Michael,

The attachments on github are annoying. You should be able to attach a zip file though.

I just checked [APABakery.tla](https://github.com/informalsystems/apalache-tests/blob/master/performance/Bakery-Boulangerie/APABakery.tla) in our benchmarks repo, and it is working. Are you using the benchmarks from the OOPSLA19 artifact?

**Comment by leuschel** [comment]
Yes, I am using the files from the OOPSLA artifact.

**Comment by konnov** [comment]
Thanks! I have reproduced it in the unstable version too: [APABakeryTyped.tla](https://github.com/informalsystems/apalache-tests/blob/master/performance/Bakery-Boulangerie/APABakeryTyped.tla)

I think we have tweaked the benchmark a bit when things did not work and forgot to recover it.

**Comment by Kukovec** [comment]
I ran Apalache (current unstable) with your input parameters on [APABakery.tla](https://github.com/informalsystems/apalache-tests/blob/master/performance/Bakery-Boulangerie/APABakery.tla) and this behaviour is no longer present, so I'm closing the issue.
