### ISSUE TITLE
[BUG] Link to manual seems incorrect

### ISSUE THREAD

**Issue by leuschel** [informalsystems/apalache#678]
**Describe the bug**
I have tried to write an N-Queens version suitable for Apalache and get this message:
To understand the error, read the manual:                         I@12:51:18.308
  [https://github.com/informalsystems/apalache/blob/unstable/docs/manual.md#assignments] I@12:51:18.308
Assignment error: No assignments found for: queens  

The issue was caused by using FALSE for the next predicate (everything is in the initialisation).

However, the link to the manual seems outdated and should possibly be https://apalache.informal.systems/docs/idiomatic/001assignments.html

**Comment by konnov** [comment]
Thanks! There is another page in the manual that also explains assignments: https://apalache.informal.systems/docs/apalache/assignments.html

**Comment by shonfeder** [comment]
@leuschel thanks for the report! Could you also indicate what version of apalache you currently using (just for the record)?

That is given by

```
apalache-mc version
```

Thanks!

**Comment by leuschel** [comment]
# APALACHE version 0.8.0-RELEASE build v0.8.0-0-g05dfdb8

**Comment by lemmy** [comment]
FWIW: I also observed a broken link a few days ago with a recent unstable build.

**Comment by shonfeder** [comment]
Thank, @leuschel!

@lemmy are you noting there was a different, additional link broken?

**Comment by lemmy** [comment]
@shonfeder I don't remember what the link pointed to (it might have been `assignments.html`), but it was definitely shown as part of Apalache's error reporting.

**Comment by shonfeder** [comment]
Ok, thanks.
