### ISSUE TITLE
[FEATURE] Introduce type aliases in Snowcat

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#703]
As the example of [Raft](https://github.com/informalsystems/apalache-tests/blob/master/performance/raft/APAraft.tla) shows, the type annotations may be quite large. To this end, we should introduce type aliases. It is not obvious, where to place such aliases. The easiest solution is to allow the user to write a type alias in the place, where they can write `@type`. For instance:

```tla
VARIABLE
  @typeAlias("entry", "[term: Int, contents: Str]")
  @type: Set([seqno: Int, entry: entry]);
  messages
```

To introduce a type alias, we would have to use the general syntax of Java-like annotations, which is a bit harder to read than the single-argument syntax. The above type alias can be used in the type annotations that are below the alias, in the syntactic order of the specification.

**Comment by vitorenesduarte** [comment]
Would something like `@typeAlias(entry): [term: Int, contents: Str];` instead of `@typeAlias("entry", "[term: Int, contents: Str]")` work? I believe this keeps it closer to the existing `@type` annotations.

**Comment by konnov** [comment]
This is not how the general syntax of Java-like annotations looks like: https://apalache.informal.systems/docs/adr/004adr-annotations.html

**Comment by vitorenesduarte** [comment]
Oh, I see, thanks. Maybe `@typeAlias: entry ~ [term: Int, contents: Str];` or `@typeAlias: entry = [term: Int, contents: Str];`

**Comment by konnov** [comment]
Yes, this should be possible by extending the type parser:
