### ISSUE TITLE
[FEATURE] Warn about unmatched type annotations

### ISSUE THREAD

**Issue by lemmy** [informalsystems/apalache#705]
Beginner problem but I just wasted 10-15 minutes banging my head:

```shell
Checker options: filename=EWD840, init=, next=, inv=              I@09:21:26.881
Tuning:                                                           I@09:21:27.338
PASS #0: SanyParser                                               I@09:21:27.339
Parsing file /home/markus/src/TLA/_specs/models/tutorials/ewd840/EWD840.tla
Parsing file /tmp/Naturals.tla
PASS #1: TypeCheckerSnowcat                                       I@09:21:27.976
 > Running Snowcat .::.                                           I@09:21:27.976
[EWD840.tla:9:14-9:14]: Undefined name N. Introduce a type annotation. E@09:21:28.124
 > Snowcat asks you to fix the types. Meow.                       I@09:21:28.124
Checker has found an error                                        I@09:21:28.124
It took me 0 days  0 hours  0 min  1 sec                          I@09:21:28.125
Total time: 1.247 sec                                             I@09:21:28.125
EXITCODE: OK
```

 ```tla
------------------------------ MODULE EWD840 -------------------------------
EXTENDS Naturals

\* @type: Int;
CONSTANT  N

ASSUME NAssumption == N \in (Nat \ {0})

Node == 0 .. N-1

black == "black"
white == "white"
Color == {black, white}

...
```

It would be nice if snowcat would warn about the unmatched type annotation on line four.

**Comment by lemmy** [comment]
Btw. the error message should probably quote the identifier to avoid warnings such as the one below (for a spec with a variable `name`):

```
[EWD840.tla:9:14-9:14]: Undefined name name. Introduce a type annotation. E@09:21:28.124
```

**Comment by konnov** [comment]
> It would be nice if snowcat would warn about the unmatched type annotation on line four.

Do you mean that Snowcat should complain as soon as it meets a constant or a variable without an annotation? That makes sense to me.

**Comment by lemmy** [comment]
Maybe I'm mistaken, but a while ago you mention upcoming type inference that would handle the basic if not most constructs.  Have you dropped that goal?

**Comment by konnov** [comment]
We still have a type inference prototype by Jure. However, it requires more work to: decode type errors from SMT and compute principle types (the most general ones). The type checker does not have these problems, as the user has to help it.

I am actually less certain now that one needs a completely automatic type inference in the presence of a reasonably simple type checker. Many languages do it fine with a good enough type checker. Do you think there is a strong case for a tool that does not need type annotations?

**Comment by lemmy** [comment]
I would have to use the type annotations in the scope of a real-world spec to have an opinion.  Strategically, I have the feeling that good type inference will help narrow the gap between the specs that can be checked with both Apalache and TLC.
