### ISSUE TITLE
Add an artifact without version suffix to each release

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#716]
Suggested by Markus here: https://twitter.com/lemmster/status/1379283134861123586 to support code spaces dev. This will also also fix #477.

**Comment by lemmy** [comment]
Not elegant but may be useful: the CommunityModules simply [upload the release assets twice](https://github.com/tlaplus/CommunityModules/blob/4337afb74653cedcc2a24107759bf1613812db34/.github/workflows/main.yml#L41-L84).

**Comment by shonfeder** [comment]
Yep, that's my plan too. Thanks :)
