### ISSUE TITLE
Conduct survey of TLA users

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#721]
We'd like to develop a user survey to understand the interest, needs, and ambitions of people who write TLA. 

We'd like to inquire about things such as:

- What do you do with it?
- What do you want to do with it?
- How long have you been using it?
- What do you use it for?
- What industry do you work in?

We especially want to learn about aspiring non-users: people who are interested in TLA  but have been blocked or otherwise.

This is low priority for the time being, as our immediate focus is on understanding our internal users (see #720).

**Comment by konnov** [comment]
Let's close this issue for now and reopen when there is a need for it.
