### ISSUE TITLE
[FEATURE] Server Mode

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#730]
This is probably a better solution for #542 and #79.

In the current implementation, when one wants to run the commands `check` and `test` multiple times, one has to wait for the bootstrapping times of Java/Scala and the preprocessing steps by Apalache. We considered adding the `--continue` flag, similar to TLC. Now I think that it would be a bad design choice.

Since the number of use cases is proliferating, it is better to build a JSON server in Apalache. This server would serve model checking queries. For better UX, we would write problem-specific scripts that interact with the Apalache server, in order to solve a specific task that the user has in mind.

----

## Sub issue tracking

- Design: #815
- Features: 
  -  #529
  -  #1114
  -  #1116
  - #1117
- Infrastructure:
  - #906 
  - #1115
  - #1113
  - #1118

**Comment by konnov** [comment]
We have to find a good library to serve http requests in json. For instance, here is Akka HTTP: https://doc.akka.io/docs/akka-http/current/common/json-support.html

**Comment by shonfeder** [comment]
Does it have to be HTTP?

**Comment by lemmy** [comment]
FWIW: One design bug of TLC (perhaps down to SANY) has always been that it cannot check two (or more) specs within the same JVM instance.  Not sure if that's relevant here, but this restriction has turned out to be a pain.  In light of refinement, a "model-checking query" might include a spec.

**Comment by konnov** [comment]
> FWIW: One design bug of TLC (perhaps down to SANY) has always been that it cannot check two (or more) specs within the same JVM instance. Not sure if that's relevant here, but this restriction has turned out to be a pain. In light of refinement, a "model-checking query" might include a spec.

That's a good point. However, we are spending most of the time on spec preprocessing. So I would fix the spec. However, we definitely have to figure out how not to restart the tool, if the user wants to check several properties. I believe that annotations would help us here. E.g., by annotating invariants with `@invariant`, we can tell the tool to do all preprocessing upfront and then let the user to run the queries.

**Comment by konnov** [comment]
@Kukovec would you like to write an RFC, similar to [RFC001](https://github.com/informalsystems/apalache/blob/unstable/docs/internal/rfc/001rfc-types.md). I remember that the discussion in RFC001 was a big success. The RFC should also relate to [ADR003](https://github.com/informalsystems/apalache/blob/unstable/docs/internal/adr/003adr-trex.md).

**Comment by konnov** [comment]
On a second thought, we have all passes integrated via Guice, so reloading a spec via a new pipeline should be really easy.

**Comment by shonfeder** [comment]
This is all tracked in the milestone now: https://github.com/informalsystems/apalache/milestone/42
