### ISSUE TITLE
[BUG] `typecheck` command returns exit code 0 (success) even when type-checking fails

### ISSUE THREAD

**Issue by romac** [informalsystems/apalache#740]
## Description

The `typecheck` command returns a successful (ie. 0) exit code even when type-checking fails.

This makes it difficult to use on CI or in scripts, as one cannot rely on the exit code to either abort the script or mark the CI job as failed.

It's possible to work around that by using `grep` to figure if the output contains `Type checker [FAILED] `, but that approach depends on the specific output emitted by the tool (and therefore seems unreliable in general) and does not match the general UNIX way of dealing with errors.

## Input specification

```tla
---------------------- MODULE HourClock ----------------------

EXTENDS Naturals

VARIABLE
    \* @type: Bool;  <===== Type error
    hr

HCini  ==  hr \in (1 .. 12)
HCnxt  ==  hr' = IF hr # 12 THEN hr + 1 ELSE 1
HC     ==  HCini /\ [][HCnxt]_hr

TypeOK == hr \in (1 .. 12)

==============================================================
```

## The command line parameters used to run the tool

```
$ apalache-mc typecheck HourClock.tla
Type checking HourClock.tla                                       I@13:10:50.759
PASS #0: SanyParser                                               I@13:10:50.965
Parsing file /var/apalache/HourClock.tla
Parsing file /tmp/Naturals.tla
PASS #1: TypeCheckerSnowcat                                       I@13:10:51.263
 > Running Snowcat .::.                                           I@13:10:51.263
[HourClock.tla:9:12-9:27]: No match between operator signature ((g, Set(g)) => Bool) and arguments Bool and Set(Int) E@13:10:51.365
[HourClock.tla:9:1-9:27]: Error when computing the type of HCini  E@13:10:51.370
 > Snowcat asks you to fix the types. Meow.                       I@13:10:51.371
Type checker [FAILED]                                             I@13:10:51.372
It took me 0 days  0 hours  0 min  0 sec                          I@13:10:51.374
Total time: 0.616 sec                                             I@13:10:51.375
EXITCODE: OK                 <==========
```

```
$ echo $?
0
```

## Expected behavior

```
$ apalache-mc typecheck HourClock.tla
Type checking HourClock.tla                                       I@13:10:50.759
PASS #0: SanyParser                                               I@13:10:50.965
Parsing file /var/apalache/HourClock.tla
Parsing file /tmp/Naturals.tla
PASS #1: TypeCheckerSnowcat                                       I@13:10:51.263
 > Running Snowcat .::.                                           I@13:10:51.263
[HourClock.tla:9:12-9:27]: No match between operator signature ((g, Set(g)) => Bool) and arguments Bool and Set(Int) E@13:10:51.365
[HourClock.tla:9:1-9:27]: Error when computing the type of HCini  E@13:10:51.370
 > Snowcat asks you to fix the types. Meow.                       I@13:10:51.371
Type checker [FAILED]                                             I@13:10:51.372
It took me 0 days  0 hours  0 min  0 sec                          I@13:10:51.374
Total time: 0.616 sec                                             I@13:10:51.375
EXITCODE: ERROR            <==========
```

```
$ echo $?
1
```

## Log files

N/A

## System information

- Apalache version [`apalache-mc version`]: 0.15.2 build v0.15.2-0-geb20fdf
- OS [e.g. Ubuntu Linux or Mac OS, and the current version]: macOS 11.2.3
- JDK version [e.g. OpenJDK 0.8.0]: OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 25.282-b07-jvmci-21.0-b06, mixed mode)

## Additional context

This is currently an issue when running the type checker on the IBC specifications as a GitHub Action in the `ibc-rs` repository.

**Comment by romac** [comment]
This seems to be an issue for other commands as well, eg. `check`.

**Comment by konnov** [comment]
I think we have reserved non-zero exit code for tool failures. @shonfeder what is your opinion on that?

**Comment by romac** [comment]
To me, the end user does not care whether a) the tool experienced an internal error or b) their specification failed to check. In both cases, the result is that their specific did not through successfully, and imho both those cases would warrant a (potentially different) exit code.

**Comment by konnov** [comment]
It's not obvious with exit codes. Afaik, SAT solver are using a completely non-standard exit codes :)

**Comment by konnov** [comment]
It's really easy to change the exit codes. I just remember that @shonfeder and I had a discussion on that. We need his opinion.

**Comment by shonfeder** [comment]
I fully agree with @romac :) See https://github.com/informalsystems/apalache/issues/249

**Comment by romac** [comment]
> Ah, actually this is a duplicate of #249

Sorry about that, I should've searched before opening an issue.

**Comment by shonfeder** [comment]
No, no, no. Don't be sorry ;) It's a good reminder and helps motivate that one. 

Duplicate issues is the price paid for big back logs :)

**Comment by konnov** [comment]
Cool. Then we introduce error codes. I will introduce the error codes in the tool, but some scripting and CI may break. @shonfeder, I will ping you if that happens.

**Comment by shonfeder** [comment]
Closing in favor of #249
