### ISSUE TITLE
[FEATURE] Implement TagReader for TlaType1

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#780]
Needed for recovery of types from JSON.

**Comment by konnov** [comment]
We have a whole parser for that in `DefaultType1Parser`. Why would you need an additional reader?

**Comment by Kukovec** [comment]
Huh, guess it didn't show up in my search, since it doesn't extend the tag reader trait from the JSON IO, but it should be easy enough to add that.

**Comment by Kukovec** [comment]
Side note though, we have to move these classes from types to a lower-level package, so they're accessible during ParserPass

**Comment by konnov** [comment]
That makes sense. Let's move `at.forsyte.apalache.tla.typecheck.parser` to `tla-import` under `at.forsyte.apalache.io.typecheck.parser`. Also, if you like to rename `tla-import` to `tla-io`, that would be great!
