### ISSUE TITLE
[FEATURE] Preprocessed TLA+ files should have the same name as the module names

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#785]
To be able to feed the files back to SANY.

**Comment by lemmy** [comment]
FYI: Only the first module in a .tla has to match the file name, but there is no limit on the number of modules in a .tla file.  For other reasons, I've considered even relaxing (removing) the first constraint.

**Comment by konnov** [comment]
Is there any reason for having that constraint? It just introduces extra steps in tooling.

**Comment by lemmy** [comment]
I haven't found a (code) comment that explains it.  Let's ask Leslie next Tuesday.  He added the constraint a few years ago.
