### ISSUE TITLE
[FEATURE] Add type description to error message when overriding type doesn't match

### ISSUE THREAD

**Issue by klinvill** [informalsystems/apalache#823]
**Is your feature request related to a problem? Please describe.**
The error message for when an overriding type doesn't match the original type currently does not give any information on how the types are different. E.g. `The types of Acceptor and OVERRIDE_Acceptor do not match.`

**Describe the solution you'd like**
The error message should ideally display the mismatched types. E.g. `The types of Acceptor (Set(ACCEPTOR)) and OVERRIDE_Acceptor (Set(Str)) do not match.`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by konnov** [comment]
Good point. We will fix that.
