### ISSUE TITLE
[BUG] snowcat does not use type aliases

### ISSUE THREAD

**Issue by svalaskevicius** [informalsystems/apalache#920]
## Description

There is a type alias `MESSAGE` defined as a record.

Also, there is this function:

```
\* @type: (MESSAGE, MESSAGE) => Bool;
Name(m1, m2) ==  <...> m1.field = m2.field <...>
```

Result:
```
[MessageTransmission.tla:75:9-75:16]: Need annotation. Found 2 matching operator signatures (((Str -> a504), Str) => a504) or (([robot: a504], Str) => a504) for arguments MESSAGE and Str E@20:11:40.709
```

If the message type is expanded the full record description in the function declaration, typecheck passes.

## Expected behavior

Type aliases accepted and resolved.

## System information

`0.15.12-SNAPSHOT build v0.15.11-6-gce8dcf8`, running from docker image

**Comment by shonfeder** [comment]
Thanks for the report! 

Could you provide a minimum working spec?  In particular (or at least) it would help to see how you are defining the type alias.

**Comment by svalaskevicius** [comment]
hmm I think I rushed to create this... I had a type alias w/o the dummy expression, so probably it just didn't take that as an alias... could have reported or just accepted it :) but I'll close this as I got it working... thanks for the super quick response though!

**Comment by shonfeder** [comment]
No problem! Let us know if you end up hitting a snag here, or if you think the reporting or handling of this could be better.

Thank again for filing the issue!
