### ISSUE TITLE
[FEATURE] Implement an Apalache operator for the sequence <<1,...,N>>

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#945]
One cannot define a (non-literal) sequence in base TLA+, without using a function constructor `{x \in 1..N |-> F(x)}` and, in Apalache, a cast `FunAsSeq(fn, N)`, i.e. 
```
FunAsSeq({x \in 1..N |-> F(x)}, N)
```
We should implement an Apalache operator (and possibly an IR representation), for constructing the sequence `<<1,...,N>>` (or `<<F(1),...,F(N)>>`) directly.

**Comment by konnov** [comment]
This looks like band aid. If we want to introduce a new operator anyways, would not it make sense to introduce an operator that properly constructs a sequence by calling an operator? For instance:

```tla
\* The standard idiom is to construct a sequence by using the function constructor.
\* Apalache implements it more efficiently under the hood. 
MkSeq(len, F(_)) == [ n \in 1..len |-> F(n) ]
```

If we introduce this operator in Apalache, we can think of adding it in the community modules as well.

**Comment by Kukovec** [comment]
Yes, that's what I had in mind with "or <<F(1),...,F(N)>>) directly".

**Comment by konnov** [comment]
Let's implement `FunAsSeq` first and define `MkSeq` via `FunAsSeq` in `Apalache.tla`. There would be no performance gain in implementing `MkSeq` in Apalache directly. Essentially, `MkSeq` would be a safer version of `FunAsSeq({x \in 1..N |-> F(x)}, N)`. We know that people mess up indices sometimes.

**Comment by konnov** [comment]
Requires #569

**Comment by konnov** [comment]
I was wrong. `FunAsSeq` requires `O(n^2)` constraints, as it has to apply `F[i]` for every `i \in 1..len`. The solution with `MkSeq` would be more efficient. However, it would require an operator call, similar to `FoldSeq`.
