### ISSUE TITLE
Draft RFC on disjoint union representation for type-safe representation of heterogenouss sets of records 

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#947]
As discussed in our retro last week and planning meeting yesterday.

This is associated with #938 and bears upon the discussion in https://github.com/informalsystems/apalache/discussions/789.

The proposal suggests an alternative perspective on the typing of records, and has will have bearing on the question of sensible representations of algebraic data types in the context of TLA+ specs. 

I should have time to a PR in place for sometime next week.

We do not anticipate any substantive implementation work around this until next quarter, so there should be ample to gather feedback.

**Comment by konnov** [comment]
I just thought about your approach a bit. It could sit between the type checker and the model checker. So the type checker will accept sets of discriminated unions. The preprocessor would turn sets of discriminated unions into records of sets. The model checker would deal only with simple sets of records.

**Comment by konnov** [comment]
We should not forget about counterexamples. If the preprocessing changes the representation of a set, then the counterexamples will not shown in the form expected by the user.

**Comment by shonfeder** [comment]
> So the type checker will accept sets of discriminated unions. The preprocessor would turn sets of discriminated unions into records of sets. The model checker would deal only with simple sets of records.

That would definitely make sense if just having a record of sets was more efficient for model checking. Tho I think Jure suggested the opposite seemed to be the case?

**Comment by Kukovec** [comment]
No, the record of sets was faster than the set of records iirc.

**Comment by shonfeder** [comment]
That's what I thought. So, if anything, we might want to convert sets of records into a record of sets as an optimization, even if we end up finding a way of doing sum types with sets of records.

**Comment by shonfeder** [comment]
Instead of an RFC document, this ended up as a discussion comment. See https://github.com/informalsystems/apalache/discussions/789#discussioncomment-1592118
